In [7]:
import math
import os.path


def highlight_row_max(s):
    if s.name == "Dataset":
        return [""] * len(s)
    if s.name == "Avg Rank":
        is_min = s == s.min()
        return ["background-color: green; color: white" if v else "" for v in is_min]
    is_max = s == s.max()
    return ["background-color: green; color: white" if v else "" for v in is_max]


def highlight_row_min(s):
    if s.name == "Dataset":
        return [""] * len(s)
    if s.name == "Wins":
        is_max = s == s.max()
        return ["background-color: green; color: white" if v else "" for v in is_max]
    is_min = s == s.min()
    return ["background-color: green; color: white" if v else "" for v in is_min]


def sort_dataset(df):
    desired_order = [
        "fingerprint_high_freq",
        "fingerprint_mid_freq",
        "fingerprint_low_freq",
        "fingerprint_cardiac",
        "fingerprint_ten",
        "fingerprint_ten_mid",
        "CPI_high_freq",
        "CPI_mid_freq",
        "CPI_low_freq",
        "CPI_cardiac",
        "CPI_ten",
        "CPI_ten_mid",
        "CPI+fingerprint_high_freq",
        "CPI+fingerprint_mid_freq",
        "CPI+fingerprint_low_freq",
        "CPI+fingerprint_cardiac",
        "CPI+fingerprint_ten",
        "CPI+fingerprint_ten_mid",
        "Avg Rank",
        "Wins"
    ]
    order_map = {name: i for i, name in enumerate(desired_order)}
    df["__order"] = df["Dataset"].map(order_map)
    df_sorted = df.sort_values("__order").drop(columns="__order")
    return df_sorted

In [8]:
import pandas as pd
import numpy as np

XofN_none_results = pd.read_csv("../XofN_none/table_results.csv", index_col=0)
XofN_none_results["XofN method"] = "XofN_none"
XofN_none_results["include_original_features"] = "N/A"
XofN_none_results["XofN time (s); PCT tr. time (s)"] = XofN_none_results["PCT tr. time (s)"]
XofN_none_results = XofN_none_results.drop(columns=["PCT tr. time (s)"])

# XofN_naive_results = pd.read_csv("XofN_naive/table_results.csv", index_col=0)
# XofN_naive_results["XofN method"] = "XofN_naive"

XofN_jaccard_max_results = pd.read_csv("../XofN_jaccard/table_results.csv", index_col=0)
XofN_jaccard_max_results["XofN method"] = "XofN Jac-max"

XofN_filter_results = pd.read_csv("../XofN_filter/table_results.csv", index_col=0)
XofN_filter_results["XofN method"] = "XofN VarRed"

# XofN_filter_jaccard_results = pd.read_csv("XofN_filter_jaccard/table_results.csv", index_col=0)
# XofN_filter_jaccard_results["XofN method"] = "XofN_filter_jaccard"

# XofN_jaccard_min_results = pd.read_csv("XofN_jaccard_min/table_results.csv", index_col=0)
# XofN_jaccard_min_results["XofN method"] = "XofN_jaccard_min"

# XofN_wrapper_results = pd.read_csv("XofN_wrapper/table_results.csv")
# XofN_wrapper_results["XofN method"] = "XofN_wrapper"

XofN_Vouk_results = pd.read_csv("../../single_label_approach/vouk/table_results.csv")
XofN_Vouk_results["XofN method"] = "XofN Vouk"

In [9]:
all_cols = set(XofN_none_results.columns) | set(XofN_filter_results.columns)
df1 = XofN_none_results.reindex(columns=all_cols)
# df2 = XofN_naive_results.reindex(columns=all_cols)
df3 = XofN_jaccard_max_results.reindex(columns=all_cols)
df4 = XofN_filter_results.reindex(columns=all_cols)
# df5 = XofN_filter_jaccard_results.reindex(columns=all_cols)

# df5 = XofN_wrapper_results.reindex(columns=all_cols)
# df6 = XofN_jaccard_min_results.reindex(columns=all_cols)
df7 = XofN_Vouk_results.reindex(columns=all_cols)

combined_df = pd.concat([df1, df3, df4, df7], ignore_index=True)

column_map = {
    "dataset": "Dataset",
    "XofN method": "XofN method",
    "include_original_features": "Ung or Org",
    'averageAUROC': 'Macro-AUROC',
    'HammingLoss': 'Hamming Loss',
    'SubsetAccuracy': 'Subset Accuracy',
    'MacroFOne': 'Macro-F1',
    'MacroRecall': 'Macro-Recall',
    'MacroPrecision': 'Macro-Precision',
    'RankingLoss': 'Ranking Loss',
    'Nodes; Leaves': 'Nodes; Leaves',
    '#XofN; #Feat/XofN': '#XofN; #Feat/XofN',
    '# Ung. Feats': '#Ung. Feats',
    'XofN time (s); PCT tr. time (s)': 'XofN time (s); PCT tr. time (s)'
}
column_order = [column_map[col] for col in column_map]
combined_df = combined_df.rename(columns=column_map)
combined_df = combined_df.reindex(columns=column_order)
combined_df["Ung or Org"] = combined_df["Ung or Org"].map({
    "no_org": "Ung",
    "with_org": "Org",
    "N/A": "N/A"
})
combined_df['#XofN; #Feat/XofN'] = combined_df['#XofN; #Feat/XofN'].replace(np.nan, "N/A")
combined_df['#Ung. Feats'] = combined_df['#Ung. Feats'].replace(np.nan, "N/A")
combined_df.to_csv("all_results_table.csv", index=False)
print(combined_df.to_string())

                       Dataset   XofN method Ung or Org  Macro-AUROC  Hamming Loss  Subset Accuracy  Macro-F1  Macro-Recall  Macro-Precision  Ranking Loss Nodes; Leaves #XofN; #Feat/XofN #Ung. Feats XofN time (s); PCT tr. time (s)
0         fingerprint_mid_freq     XofN_none        N/A        0.574         0.386            0.231     0.415         0.373            0.474         0.258   161.0; 81.0               N/A         N/A                             1.1
1         fingerprint_low_freq     XofN_none        N/A        0.511         0.246            0.371     0.020         0.017            0.077         0.302      8.8; 4.9               N/A         N/A                             1.1
2        fingerprint_high_freq     XofN_none        N/A        0.517         0.227            0.519     0.870         0.983            0.782         0.164     18.8; 9.9               N/A         N/A                             1.0
3          fingerprint_cardiac     XofN_none        N/A        0.517         0.256            0.383     0.016         0.015            0.038         0.231      8.6; 4.8               N/A         N/A                             1.1
4                 CPI_mid_freq     XofN_none        N/A        0.583         0.385            0.241     0.428         0.376            0.511         0.264   127.8; 64.4               N/A         N/A                             2.5
5                 CPI_low_freq     XofN_none        N/A        0.594         0.263            0.330     0.187         0.147            0.422         0.294    49.4; 25.2               N/A         N/A                             2.5
6                CPI_high_freq     XofN_none        N/A        0.550         0.216            0.535     0.877         0.981            0.794         0.162    22.4; 11.7               N/A         N/A                             2.4
7                  CPI_cardiac     XofN_none        N/A        0.561         0.283            0.341     0.204         0.156            0.424         0.244    52.0; 26.5               N/A         N/A                             2.8
8     CPI+fingerprint_mid_freq     XofN_none        N/A        0.597         0.356            0.266     0.405         0.336            0.528         0.256   160.8; 80.9               N/A         N/A                             2.9
9     CPI+fingerprint_low_freq     XofN_none        N/A        0.591         0.241            0.357     0.241         0.164            0.516         0.287    60.0; 30.5               N/A         N/A                             3.1
10   CPI+fingerprint_high_freq     XofN_none        N/A        0.570         0.239            0.492     0.858         0.944            0.789         0.153    61.2; 31.1               N/A         N/A                             2.9
11     CPI+fingerprint_cardiac     XofN_none        N/A        0.588         0.263            0.370     0.237         0.167            0.451         0.226    75.4; 38.2               N/A         N/A                             3.2
12             fingerprint_ten     XofN_none        N/A        0.607         0.398            0.060     0.599         0.610            0.593         0.287   151.6; 76.3               N/A         N/A                             1.1
13                     CPI_ten     XofN_none        N/A        0.616         0.387            0.055     0.604         0.604            0.623         0.264   108.0; 54.5               N/A         N/A                             2.4
14         CPI+fingerprint_ten     XofN_none        N/A        0.608         0.409            0.065     0.569         0.558            0.587         0.284   171.8; 86.4               N/A         N/A                             3.0
15         fingerprint_ten_mid     XofN_none        N/A        0.580         0.350            0.110     0.323         0.248            0.504         0.350    85.6; 43.3               N/A         N/A                             1.1
16                 CPI_ten_mid     XofN_none        N/A        0.571         0.355            0.107     0.352         0.274            0.532         0.372    68.8; 34.9               N/A         N/A                             2.8
17     CPI+fingerprint_ten_mid     XofN_none        N/A        0.598         0.344            0.131     0.354         0.280            0.504         0.343   102.4; 51.7               N/A         N/A                             3.1
18        fingerprint_mid_freq  XofN Jac-max        Ung        0.605         0.368            0.237     0.404         0.343            0.499         0.258   158.0; 79.5        108.0; 5.0         0.0                       78.3; 0.7
19        fingerprint_mid_freq  XofN Jac-max        Org        0.588         0.379            0.233     0.405         0.353            0.483         0.258   164.0; 82.5        108.0; 5.0         0.0                       78.3; 1.3
20        fingerprint_low_freq  XofN Jac-max        Ung        0.500         0.243            0.374     0.000         0.000            0.000         0.302      1.0; 1.0        108.0; 5.0         0.0                       78.4; 0.7
21        fingerprint_low_freq  XofN Jac-max        Org        0.515         0.247            0.370     0.016         0.013            0.056         0.298      7.6; 4.3        108.0; 5.0         0.0                       78.4; 1.3
22       fingerprint_high_freq  XofN Jac-max        Ung        0.555         0.229            0.498     0.866         0.957            0.793         0.160    43.8; 22.4        108.0; 5.0         0.0                       78.2; 0.7
23       fingerprint_high_freq  XofN Jac-max        Org        0.551         0.235            0.499     0.863         0.951            0.791         0.160    46.4; 23.7        108.0; 5.0         0.0                       78.2; 1.3
24         fingerprint_cardiac  XofN Jac-max        Ung        0.543         0.256            0.379     0.056         0.059            0.224         0.223     18.6; 9.8        108.0; 5.0         0.0                       78.1; 0.7
25         fingerprint_cardiac  XofN Jac-max        Org        0.547         0.270            0.363     0.093         0.095            0.281         0.230    35.4; 18.2        108.0; 5.0         0.0                       78.1; 1.3
26                CPI_mid_freq  XofN Jac-max        Ung        0.599         0.367            0.244     0.436         0.370            0.544         0.267   108.8; 54.9        322.0; 5.0         0.0                      359.1; 1.0
27                CPI_mid_freq  XofN Jac-max        Org        0.594         0.379            0.237     0.433         0.380            0.519         0.265   132.8; 66.9        322.0; 5.0         0.0                      359.1; 2.9
28                CPI_low_freq  XofN Jac-max        Ung        0.592         0.260            0.331     0.192         0.148            0.510         0.293    53.2; 27.1        322.0; 5.0         0.0                      358.1; 1.1
29                CPI_low_freq  XofN Jac-max        Org        0.613         0.262            0.332     0.245         0.170            0.500         0.287    57.2; 29.1        322.0; 5.0         0.0                      358.1; 3.0
30               CPI_high_freq  XofN Jac-max        Ung        0.566         0.216            0.537     0.876         0.978            0.795         0.162     17.0; 9.0        322.0; 5.0         0.0                      356.2; 0.9
31               CPI_high_freq  XofN Jac-max        Org        0.599         0.218            0.534     0.875         0.971            0.797         0.164    29.6; 15.3        322.0; 5.0         0.0                      356.2; 2.6
32                 CPI_cardiac  XofN Jac-max        Ung        0.591         0.275            0.346     0.249         0.177            0.478         0.231    55.4; 28.2        322.0; 5.0         0.0                      355.0; 1.0
33                 CPI_cardiac  XofN Jac-max        Org        0.592         0.273            0.345     0.251         0.176            0.480         0.231    64.4; 32.7        322.0; 5.0         0.0                      355.0; 3.0
34    CPI+fingerprint_mid_freq  XofN Jac-max        Ung        0.592         0.361            0.260     0.428         0.372            0.512         0.255   150.6; 75.8        430.0; 5.0         0.0                      537.5; 1.1
35    CPI+fingerprint_mid_freq  XofN Jac-max        Org        0.597         0.360            0.266     0.423         0.364            0.513         0.263   161.0; 81.0        430.0; 5.0         0.0                      537.5; 3.5
36    CPI+fingerprint_low_freq  XofN Jac-max        Ung        0.609         0.250            0.357     0.230         0.161            0.451         0.280    61.4; 31.2        430.0; 5.0         0.0                      536.2; 1.2
37    CPI+fingerprint_low_freq  XofN Jac-max        Org        0.599         0.246            0.363     0.199         0.163            0.456         0.275    68.6; 34.8        430.0; 5.0         0.0                      536.2; 3.9
38   CPI+fingerprint_high_freq  XofN Jac-max        Ung        0.591         0.230            0.493     0.864         0.950            0.793         0.162    65.8; 33.4        430.0; 5.0         0.0                      534.4; 1.2
39   CPI+fingerprint_high_freq  XofN Jac-max        Org        0.601         0.237            0.490     0.859         0.941            0.791         0.157    76.8; 38.9        430.0; 5.0         0.0                      534.4; 3.5
40     CPI+fingerprint_cardiac  XofN Jac-max        Ung        0.583         0.269            0.357     0.223         0.176            0.430         0.222    77.8; 39.4        430.0; 5.0         0.0                      527.2; 1.2
41     CPI+fingerprint_cardiac  XofN Jac-max        Org        0.584         0.273            0.361     0.253         0.187            0.418         0.225    85.2; 43.1        430.0; 5.0         0.0                      527.2; 3.9
42             fingerprint_ten  XofN Jac-max        Ung        0.596         0.410            0.073     0.582         0.585            0.584         0.292   160.6; 80.8        108.0; 5.0         0.0                       74.4; 0.7
43             fingerprint_ten  XofN Jac-max        Org        0.601         0.406            0.054     0.587         0.589            0.589         0.293   154.4; 77.7        108.0; 5.0         0.0                       74.4; 1.3
44                     CPI_ten  XofN Jac-max        Ung        0.609         0.397            0.067     0.605         0.612            0.611         0.276    95.4; 48.2        322.0; 5.0         0.0                      343.3; 1.0
45                     CPI_ten  XofN Jac-max        Org        0.622         0.392            0.056     0.606         0.609            0.615         0.272   103.4; 52.2        322.0; 5.0         0.0                      343.3; 2.7
46         CPI+fingerprint_ten  XofN Jac-max        Ung        0.612         0.401            0.065     0.574         0.559            0.597         0.276   168.2; 84.6        430.0; 5.0         0.0                      506.8; 1.1
47         CPI+fingerprint_ten  XofN Jac-max        Org        0.613         0.400            0.075     0.585         0.582            0.594         0.284   175.2; 88.1        430.0; 5.0         0.0                      506.8; 3.6
48         fingerprint_ten_mid  XofN Jac-max        Ung        0.585         0.354            0.117     0.331         0.259            0.483         0.343    98.4; 49.7        108.0; 5.0         0.0                       75.7; 0.7
49         fingerprint_ten_mid  XofN Jac-max        Org        0.575         0.368            0.103     0.329         0.267            0.454         0.342   109.6; 55.3        108.0; 5.0         0.0                       75.7; 1.3
50                 CPI_ten_mid  XofN Jac-max        Ung        0.581         0.352            0.116     0.320         0.271            0.515         0.372    71.0; 36.0        322.0; 5.0         0.0                      349.7; 1.1
51                 CPI_ten_mid  XofN Jac-max        Org        0.593         0.358            0.108     0.383         0.320            0.501         0.368    88.0; 44.5        322.0; 5.0         0.0                      349.7; 3.1
52     CPI+fingerprint_ten_mid  XofN Jac-max        Ung        0.588         0.346            0.127     0.340         0.263            0.505         0.354    91.6; 46.3        430.0; 5.0         0.0                      574.4; 1.2
53     CPI+fingerprint_ten_mid  XofN Jac-max        Org        0.590         0.347            0.128     0.347         0.272            0.501         0.348   109.0; 55.0        430.0; 5.0         0.0                      574.4; 4.0
54        fingerprint_mid_freq   XofN VarRed        Ung        0.599         0.371            0.237     0.431         0.386            0.498         0.256   145.2; 73.1        110.1; 4.9    1.567535                       94.7; 0.7
55        fingerprint_mid_freq   XofN VarRed        Org        0.601         0.373            0.231     0.435         0.394            0.493         0.257   152.2; 76.6        110.1; 4.9    1.567535                       94.7; 1.3
56        fingerprint_low_freq   XofN VarRed        Ung        0.529         0.250            0.364     0.076         0.070            0.348         0.291    27.6; 14.3        112.0; 4.8    0.922718                       94.7; 0.7
57        fingerprint_low_freq   XofN VarRed        Org        0.527         0.250            0.363     0.054         0.071            0.364         0.292    27.2; 14.1        112.0; 4.8    0.922718                       94.7; 1.3
58       fingerprint_high_freq   XofN VarRed        Ung        0.588         0.223            0.505     0.869         0.956            0.799         0.163    42.4; 21.7        110.9; 4.9    2.051676                       94.5; 0.7
59       fingerprint_high_freq   XofN VarRed        Org        0.582         0.229            0.504     0.865         0.947            0.797         0.164    48.0; 24.5        110.9; 4.9    2.051676                       94.5; 1.3
60         fingerprint_cardiac   XofN VarRed        Ung        0.551         0.272            0.365     0.139         0.132            0.389         0.229    52.2; 26.6        111.0; 4.8    2.565816                       94.1; 0.7
61         fingerprint_cardiac   XofN VarRed        Org        0.545         0.276            0.356     0.135         0.118            0.366         0.226    55.8; 28.4        111.0; 4.8    2.565816                       94.1; 1.3
62                CPI_mid_freq   XofN VarRed        Ung        0.602         0.371            0.237     0.447         0.391            0.532         0.266    95.0; 48.0        335.6; 4.7   33.044644                      463.5; 0.9
63                CPI_mid_freq   XofN VarRed        Org        0.604         0.373            0.237     0.455         0.408            0.529         0.277   112.4; 56.7        335.6; 4.7   33.044644                      463.5; 2.5
64                CPI_low_freq   XofN VarRed        Ung        0.598         0.265            0.337     0.261         0.186            0.485         0.285    42.4; 21.7        331.2; 4.8    2.059206                      459.8; 0.9
65                CPI_low_freq   XofN VarRed        Org        0.599         0.266            0.329     0.263         0.189            0.492         0.281    49.0; 25.0        331.2; 4.8    2.059206                      459.8; 2.6
66               CPI_high_freq   XofN VarRed        Ung        0.564         0.220            0.529     0.873         0.964            0.799         0.158    28.6; 14.8        343.6; 4.6    9.274427                      466.8; 0.9
67               CPI_high_freq   XofN VarRed        Org        0.580         0.228            0.517     0.868         0.956            0.795         0.159    33.8; 17.4        343.6; 4.6    9.274427                      466.8; 2.6
68                 CPI_cardiac   XofN VarRed        Ung        0.563         0.279            0.344     0.204         0.171            0.459         0.239    46.0; 23.5        355.6; 4.4    24.99709                      464.8; 0.9
69                 CPI_cardiac   XofN VarRed        Org        0.567         0.272            0.346     0.266         0.192            0.495         0.243    57.4; 29.2        355.6; 4.4    24.99709                      464.8; 2.6
70    CPI+fingerprint_mid_freq   XofN VarRed        Ung        0.602         0.365            0.255     0.436         0.389            0.508         0.260   134.4; 67.7        448.3; 4.7   28.592341                      719.9; 1.2
71    CPI+fingerprint_mid_freq   XofN VarRed        Org        0.609         0.353            0.268     0.452         0.403            0.526         0.262   157.6; 79.3        448.3; 4.7   28.592341                      719.9; 3.6
72    CPI+fingerprint_low_freq   XofN VarRed        Ung        0.606         0.248            0.352     0.271         0.197            0.471         0.269    58.8; 29.9        439.4; 4.9    3.038093                      710.4; 1.3
73    CPI+fingerprint_low_freq   XofN VarRed        Org        0.607         0.245            0.357     0.290         0.215            0.484         0.269    61.0; 31.0        439.4; 4.9    3.038093                      710.4; 3.9
74   CPI+fingerprint_high_freq   XofN VarRed        Ung        0.585         0.249            0.482     0.850         0.921            0.790         0.158    64.2; 32.6        455.8; 4.7    8.633591                      716.8; 1.3
75   CPI+fingerprint_high_freq   XofN VarRed        Org        0.590         0.245            0.479     0.852         0.920            0.794         0.162    72.4; 36.7        455.8; 4.7    8.633591                      716.8; 3.7
76     CPI+fingerprint_cardiac   XofN VarRed        Ung        0.591         0.270            0.370     0.280         0.210            0.438         0.229    69.2; 35.1        468.7; 4.5   17.578134                      702.6; 1.3
77     CPI+fingerprint_cardiac   XofN VarRed        Org        0.589         0.272            0.368     0.270         0.201            0.426         0.230    77.4; 39.2        468.7; 4.5   17.578134                      702.6; 3.9
78             fingerprint_ten   XofN VarRed        Ung        0.583         0.420            0.064     0.575         0.584            0.572         0.295   149.4; 75.2        109.8; 4.9    0.964533                       94.2; 0.7
79             fingerprint_ten   XofN VarRed        Org        0.590         0.420            0.063     0.578         0.587            0.573         0.288   158.4; 79.7        109.8; 4.9    0.964533                       94.2; 1.4
80                     CPI_ten   XofN VarRed        Ung        0.623         0.391            0.081     0.608         0.604            0.623         0.274    88.6; 44.8        331.6; 4.8    6.534039                      421.4; 0.9
81                     CPI_ten   XofN VarRed        Org        0.619         0.398            0.070     0.597         0.587            0.619         0.275   102.0; 51.5        331.6; 4.8    6.534039                      421.4; 2.5
82         CPI+fingerprint_ten   XofN VarRed        Ung        0.608         0.399            0.075     0.582         0.575            0.595         0.283   142.8; 71.9        442.5; 4.8    6.098225                      712.8; 1.2
83         CPI+fingerprint_ten   XofN VarRed        Org        0.616         0.397            0.078     0.594         0.598            0.596         0.282   166.8; 83.9        442.5; 4.8    6.098225                      712.8; 3.9
84         fingerprint_ten_mid   XofN VarRed        Ung        0.559         0.366            0.124     0.299         0.233            0.453         0.353    89.4; 45.2        110.8; 4.9    1.479105                       96.1; 0.7

In [10]:
approaches_list = {
    "all": ["Dataset", "XofN_none N/A",
            "XofN Jac-max Ung", "XofN Jac-max Org",
            "XofN VarRed Ung", "XofN VarRed Org",
            "XofN Vouk Ung", "XofN Vouk Org",
            # "XofN_filter_jaccard Ung", "XofN_filter_jaccard Org",
            # "XofN_naive Ung", "XofN_naive Org",
            # "XofN_jaccard_min Ung", "XofN_jaccard_min Org",
            # "XofN_wrapper Ung", "XofN_wrapper Org"
            ],
    "all Ung": ["Dataset", "XofN_none N/A", "XofN Jac-max Ung", "XofN VarRed Ung", "XofN Vouk Ung"],
    "all Org": ["Dataset", "XofN_none N/A", "XofN Jac-max Org", "XofN VarRed Org", "XofN Vouk Org"],
    "Jac-max": ["Dataset", "XofN_none N/A", "XofN Jac-max Ung", "XofN Jac-max Org", "XofN Vouk Ung",
                "XofN Vouk Org"],
    "Jac-max Ung": ["Dataset", "XofN_none N/A", "XofN Jac-max Ung", "XofN Vouk Ung"],
    "Jac-max Org": ["Dataset", "XofN_none N/A", "XofN Jac-max Org", "XofN Vouk Org"],
    "VarRed": ["Dataset", "XofN_none N/A", "XofN VarRed Ung", "XofN VarRed Org", "XofN Vouk Ung", "XofN Vouk Org"],
    "VarRed Ung": ["Dataset", "XofN_none N/A", "XofN VarRed Ung", "XofN Vouk Ung"],
    "VarRed Org": ["Dataset", "XofN_none N/A", "XofN VarRed Org", "XofN Vouk Org"],
}

minimise_measures = ["Hamming Loss", "Ranking Loss"]

In [34]:
from scipy.stats import friedmanchisquare
import scikit_posthocs as sp
import shutil
from itertools import combinations
from scipy import stats


def save_measure_table(measure, comp_name):
    minimise = measure in minimise_measures
    highlight = highlight_row_min if minimise else highlight_row_max
    ascending = True if minimise else False
    path = f"{measure}/{comp_name}/{measure}"
    if os.path.exists(f"{measure}/{comp_name}"):
        shutil.rmtree(f"{measure}/{comp_name}")
    os.mkdir(f"{measure}/{comp_name}")
    all_results_table = pd.read_csv("all_results_table.csv")
    all_results_table.loc[
        all_results_table["XofN method"] == "XofN_none", "Ung or Org"
    ] = "N/A"
    all_results_table.columns = all_results_table.columns.str.strip()
    pivot = all_results_table.pivot_table(
        index=["Dataset"],
        columns=["XofN method", "Ung or Org"],
        values=measure,
        aggfunc="first"
    )
    pivot.columns = [f"{a} {b}" for a, b in pivot.columns]
    pivot = pivot.reset_index()
    pivot = pivot.sort_values(by="Dataset", ascending=False)
    pivot_column_order = approaches.copy()
    pivot = pivot.reindex(columns=pivot_column_order)
    pivot = pivot.replace("nan", np.nan)
    numeric = pivot.select_dtypes(include=["number"])
    ranks = numeric.rank(
        axis=1,
        ascending=ascending,
        method="average",
        na_option="bottom"
    )
    avg_ranks = ranks.mean(axis=0).round(2).to_frame().T
    print("\n--", measure, comp_name, "--")
    avg_ranks["Dataset"] = "Avg Rank"
    avg_ranks.index = ["Avg Rank"]
    pivot = pd.concat([pivot, avg_ranks], ignore_index=False)
    cols_to_highlight = [col for col in pivot.columns if col != "Dataset"]

    wins = pd.Series(0, index=cols_to_highlight, dtype=float)

    for idx, row in pivot.loc[pivot.index != "Avg Rank", cols_to_highlight].iterrows():
        max_val = row.min() if minimise else row.max()
        winners = row[row == max_val].index
        k = len(winners)

        frac = 1.0 / k if k > 0 else 0.0
        wins[winners] += frac

    wins_row = pd.DataFrame([wins], index=["Wins"])
    wins_row["Dataset"] = "Wins"
    pivot_with_wins = pd.concat([pivot, wins_row], axis=0)
    pivot_with_wins = sort_dataset(pivot_with_wins)

    pivot_with_wins.style.apply(highlight, subset=cols_to_highlight, axis=1).format("{:.3f}").to_excel(
        f"{path}.xlsx", engine="openpyxl", index=False)
    csv = pd.read_excel(f"{path}.xlsx", engine="openpyxl")
    csv.to_csv(f"{path}.csv", index=False)
    save_statistical_significance(path, csv, avg_ranks.iloc[0])


def highlight_significant(val):
    return "background-color: green; color: white" if val <= 0.05 else ""


def save_nemenyi_test(path, data, avg_ranks):
    nemenyi_p_values = sp.posthoc_nemenyi_friedman(data)
    # fig = plt.figure(figsize=(10, 2), dpi=100)
    # sp.critical_difference_diagram(avg_ranks, nemenyi_p_values)
    # fig.savefig(f"{path}.png", dpi=300, bbox_inches="tight")
    # plt.show()
    CD, significant_differences = calculate_nemenyi_test(avg_ranks, 18)
    print(F"\nNemenyi's test (CD = {CD:.4f}):")
    with open(f'{path}-nemenyi.txt', 'w') as f:
        f.write(f"Nemenyi's test (CD = {CD:.2f}):\n")
        for sd in significant_differences:
            print(sd)
            f.write(f"{sd}\n")

    nemenyi_p_values.columns = data.columns
    nemenyi_p_values.index = data.columns
    nemenyi_p_values.round(3).to_csv(f"{path}-nemenyi.csv")
    nemenyi_p_values.round(3).style.map(highlight_significant).to_excel(
        f"{path}-nemenyi.xlsx", engine="openpyxl", index=False)


def calculate_nemenyi_test(avg_ranks, N):
    q05 = {
        "2": 1.960,
        "3": 2.343,
        "4": 2.569,
        "5": 2.728,
        "6": 2.850,
        "7": 2.949,
        "8": 3.031,
        "9": 3.102,
        "10": 3.164
    }
    K = len(avg_ranks) - 1  # methods (need to subtract 1 because 'Dataset' column is also present)
    term = (K * (K + 1)) / (6 * N)
    sqrt = math.sqrt(term)
    CD = q05[f"{K}"] * sqrt
    significant_differences = []
    comparisons = list(combinations(avg_ranks.items(), 2))
    comparisons = [((name1, value1), (name2, value2)) for ((name1, value1), (name2, value2)) in comparisons if
                   name1 != "Dataset" and name2 != "Dataset"]
    for ((name1, value1), (name2, value2)) in comparisons:
        if name1 == name2:
            continue
        diff = abs(value1 - value2)
        significant = diff >= CD
        comparison = f"{name1} and {name2} -> |{round(value1, 4)} - {round(value2, 4)}| = {round(diff, 4)} -> {round(diff, 4)} {">=" if diff >= CD else "<"} {round(CD, 4)} ({'Significant' if significant else 'Not Significant'})"
        if significant:
            significant_differences.append(comparison)
    return CD, significant_differences


def save_holm_test(path, data, avg_ranks):
    control_name = avg_ranks.idxmin()
    control_rank = avg_ranks[control_name]
    significant_differences = calculate_holm_test(avg_ranks, 18, control_name, control_rank)
    print(F"\nHolm's test:")
    with open(f'{path}-holm.txt', 'w') as f:
        f.write(f"Holm's test (control: {control_name}):\n")
        for sd in significant_differences:
            print(sd)
            f.write(f"{sd}\n")


def calculate_holm_test(avg_ranks, N, control_name, control_rank):
    control = (control_name, control_rank)
    comparisons = [(control, (name, value)) for (name, value) in avg_ranks.items() if name != control_name]
    comparisons = [((name1, value1), (name2, value2)) for ((name1, value1), (name2, value2)) in comparisons if
                   name1 != "Dataset" and name2 != "Dataset"]
    K = len(avg_ranks) - 1  # methods (need to subtract 1 because 'Dataset' column is also present)
    term = (K * (K + 1)) / (6 * N)
    sqrt = math.sqrt(term)
    p_values = []
    for ((name1, value1), (name2, value2)) in comparisons:
        z = (value1 - value2) / sqrt
        p_value = 2 * (1 - stats.norm.cdf(abs(z)))
        p_values.append((name2, p_value))
    p_values.sort(key=lambda x: x[1])
    alpha = 0.05
    i = 1
    significant_differences = []
    for (name, p_value) in p_values:
        adj_alpha = alpha / (K - i)
        significant = p_value <= adj_alpha
        cmp = "<" if round(p_value, 4) <= round(adj_alpha, 4) else ">="
        comparison = f"{control_name} vs {name} -> p:{round(p_value, 4)} {cmp} adj_a:{round(adj_alpha, 4)} ({'Significant' if significant else 'Not Significant'})"
        significant_differences.append(comparison)
        i = i + 1
        if not significant:
            break
    return significant_differences


def save_statistical_significance(path, data, avg_ranks):
    ranks = pd.to_numeric(avg_ranks, errors="coerce")
    data.drop(columns=["Dataset"], inplace=True)
    data = data[:-2]  # get all rows except for Avg Ranks and Avg Wins
    stat, p = friedmanchisquare(*[data[col] for col in data.columns])
    significant = "(Significant)" if p <= 0.05 else "(Not Significant)"
    friedman_result = f"Friedman test: p-value = {p:.4f} {significant}"
    print(friedman_result)
    with open(f'{path}-friedman.txt', 'w') as f:
        f.write(friedman_result)
    if p <= 0.05:
        save_nemenyi_test(path, data, ranks)
        save_holm_test(path, data, ranks)

In [35]:
measures = ["Macro-AUROC", "Hamming Loss", "Subset Accuracy", "Macro-F1", "Macro-Precision", "Macro-Recall",
            "Ranking Loss"]
other_stats = ["Nodes; Leaves"]
for comp_name in approaches_list:
    approaches = approaches_list[comp_name]
    for measure in measures:
        save_measure_table(measure, comp_name)

-- Macro-AUROC all --
Friedman test: p-value = 0.0112 (Significant)

Nemenyi's test (CD = 2.1235):
XofN_none N/A and XofN VarRed Org -> |5.06 - 2.67| = 2.39 -> 2.39 >= 2.1235 (Significant)

Holm's test:
XofN VarRed Org vs XofN_none N/A -> p:0.0009 < adj_a:0.0083 (Significant)
XofN VarRed Org vs XofN Vouk Ung -> p:0.008 < adj_a:0.01 (Significant)
XofN VarRed Org vs XofN Vouk Org -> p:0.0098 < adj_a:0.0125 (Significant)
XofN VarRed Org vs XofN Jac-max Ung -> p:0.0314 >= adj_a:0.0167 (Not Significant)

-- Hamming Loss all --
Friedman test: p-value = 0.0103 (Significant)

Nemenyi's test (CD = 2.1235):
XofN_none N/A and XofN Vouk Org -> |3.14 - 5.44| = 2.3 -> 2.3 >= 2.1235 (Significant)
XofN Jac-max Ung and XofN Vouk Org -> |2.92 - 5.44| = 2.52 -> 2.52 >= 2.1235 (Significant)

Holm's test:
XofN Jac-max Ung vs XofN Vouk Org -> p:0.0005 < adj_a:0.0083 (Significant)
XofN Jac-max Ung vs XofN Vouk Ung -> p:0.0314 >= adj_a:0.01 (Not Significant)

-- Subset Accuracy all --
Friedman test: p-value = 0.0138 (Significant)

Nemenyi's test (CD = 2.1235):
XofN Jac-max Ung and XofN Vouk Org -> |3.06 - 5.25| = 2.19 -> 2.19 >= 2.1235 (Significant)

Holm's test:
XofN Jac-max Ung vs XofN Vouk Org -> p:0.0024 < adj_a:0.0083 (Significant)
XofN Jac-max Ung vs XofN Vouk Ung -> p:0.014 >= adj_a:0.01 (Not Significant)

-- Macro-F1 all --
Friedman test: p-value = 0.2945 (Not Significant)

-- Macro-Precision all --
Friedman test: p-value = 0.3414 (Not Significant)

-- Macro-Recall all --
Friedman test: p-value = 0.4505 (Not Significant)

-- Ranking Loss all --
Friedman test: p-value = 0.8846 (Not Significant)

-- Macro-AUROC all Ung --
Friedman test: p-value = 0.2689 (Not Significant)

-- Hamming Loss all Ung --
Friedman test: p-value = 0.0668 (Not Significant)

-- Subset Accuracy all Ung --
Friedman test: p-value = 0.0379 (Significant)

Nemenyi's test (CD = 1.1055):
XofN Jac-max Ung and XofN Vouk Ung -> |2.03 - 3.19| = 1.16 -> 1.16 >= 1.1055 (Significant)

Holm's test:
XofN Jac-max Ung vs XofN Vouk Ung -> p:0.007 < adj_a:0.0167 (Significant)
XofN Jac-max Ung vs XofN_none N/A -> p:0.2748 >= adj_a:0.025 (Not Significant)

-- Macro-F1 all Ung --
Friedman test: p-value = 0.3068 (Not Significant)

-- Macro-Precision all Ung --
Friedman test: p-value = 0.5712 (Not Significant)

-- Macro-Recall all Ung --
Friedman test: p-value = 0.4443 (Not Significant)

-- Ranking Loss all Ung --
Friedman test: p-value = 0.4222 (Not Significant)

-- Macro-AUROC all Org --
Friedman test: p-value = 0.0023 (Significant)

Nemenyi's test (CD = 1.1055):
XofN_none N/A and XofN VarRed Org -> |3.17 - 1.78| = 1.39 -> 1.39 >= 1.1055 (Significant)
XofN VarRed Org and XofN Vouk Org -> |1.78 - 2.94| = 1.16 -> 1.16 >= 1.1055 (Significant)

Holm's test:
XofN VarRed Org vs XofN_none N/A -> p:0.0012 < adj_a:0.0167 (Significant)
XofN VarRed Org vs XofN Vouk Org -> p:0.007 < adj_a:0.025 (Significant)
XofN VarRed Org vs XofN Jac-max Org -> p:0.4432 >= adj_a:0.05 (Not Significant)

-- Hamming Loss all Org --
Friedman test: p-value = 0.0203 (Significant)

Nemenyi's test (CD = 1.1055):
XofN_none N/A and XofN Vouk Org -> |1.89 - 3.22| = 1.33 -> 1.33 >= 1.1055 (Significant)

Holm's test:
XofN_none N/A vs XofN Vouk Org -> p:0.002 < adj_a:0.0167 (Significant)
XofN_none N/A vs XofN Jac-max Org -> p:0.1563 >= adj_a:0.025 (Not Significant)

-- Subset Accuracy all Org --
Friedman test: p-value = 0.1830 (Not Significant)

-- Macro-F1 all Org --
Friedman test: p-value = 0.2115 (Not Significant)

-- Macro-Precision all Org --
Friedman test: p-value = 0.1505 (Not Significant)

-- Macro-Recall all Org --
Friedman test: p-value = 0.2998 (Not Significant)

-- Ranking Loss all Org --
Friedman test: p-value = 0.6058 (Not Significant)

-- Macro-AUROC Jac-max --
Friedman test: p-value = 0.1142 (Not Significant)

-- Hamming Loss Jac-max --
Friedman test: p-value = 0.0034 (Significant)

Nemenyi's test (CD = 1.4378):
XofN_none N/A and XofN Vouk Org -> |2.36 - 4.08| = 1.72 -> 1.72 >= 1.4378 (Significant)
XofN Jac-max Ung and XofN Vouk Org -> |2.28 - 4.08| = 1.8 -> 1.8 >= 1.4378 (Significant)

Holm's test:
XofN Jac-max Ung vs XofN Vouk Org -> p:0.0006 < adj_a:0.0125 (Significant)
XofN Jac-max Ung vs XofN Vouk Ung -> p:0.0842 >= adj_a:0.0167 (Not Significant)

-- Subset Accuracy Jac-max --
Friedman test: p-value = 0.0538 (Not Significant)

-- Macro-F1 Jac-max --
Friedman test: p-value = 0.8827 (Not Significant)

-- Macro-Precision Jac-max --
Friedman test: p-value = 0.9381 (Not Significant)

-- Macro-Recall Jac-max --
Friedman test: p-value = 0.7931 (Not Significant)

-- Ranking Loss Jac-max --
Friedman test: p-value = 0.5284 (Not Significant)

-- Macro-AUROC Jac-max Ung --
Friedman test: p-value = 0.5015 (Not Significant)

-- Hamming Loss Jac-max Ung --
Friedman test: p-value = 0.1085 (Not Significant)

-- Subset Accuracy Jac-max Ung --
Friedman test: p-value = 0.0258 (Significant)

Nemenyi's test (CD = 0.7810):
XofN Jac-max Ung and XofN Vouk Ung -> |1.56 - 2.44| = 0.88 -> 0.88 >= 0.781 (Significant)

Holm's test:
XofN Jac-max Ung vs XofN Vouk Ung -> p:0.0083 < adj_a:0.025 (Significant)
XofN Jac-max Ung vs XofN_none N/A -> p:0.1868 >= adj_a:0.05 (Not Significant)

-- Macro-F1 Jac-max Ung --
Friedman test: p-value = 0.8425 (Not Significant)

-- Macro-Precision Jac-max Ung --
Friedman test: p-value = 0.8425 (Not Significant)

-- Macro-Recall Jac-max Ung --
Friedman test: p-value = 0.3425 (Not Significant)

-- Ranking Loss Jac-max Ung --
Friedman test: p-value = 0.0893 (Not Significant)

-- Macro-AUROC Jac-max Org --
Friedman test: p-value = 0.0560 (Not Significant)

-- Hamming Loss Jac-max Org --
Friedman test: p-value = 0.0033 (Significant)

Nemenyi's test (CD = 0.7810):
XofN_none N/A and XofN Vouk Org -> |1.5 - 2.61| = 1.11 -> 1.11 >= 0.781 (Significant)

Holm's test:
XofN_none N/A vs XofN Vouk Org -> p:0.0009 < adj_a:0.025 (Significant)
XofN_none N/A vs XofN Jac-max Org -> p:0.242 >= adj_a:0.05 (Not Significant)

-- Subset Accuracy Jac-max Org --
Friedman test: p-value = 0.4066 (Not Significant)

-- Macro-F1 Jac-max Org --
Friedman test: p-value = 0.9061 (Not Significant)

-- Macro-Precision Jac-max Org --
Friedman test: p-value = 0.9061 (Not Significant)

-- Macro-Recall Jac-max Org --
Friedman test: p-value = 0.6778 (Not Significant)

-- Ranking Loss Jac-max Org --
Friedman test: p-value = 0.8314 (Not Significant)

-- Macro-AUROC VarRed --
Friedman test: p-value = 0.0059 (Significant)

Nemenyi's test (CD = 1.4378):
XofN_none N/A and XofN VarRed Org -> |3.69 - 1.89| = 1.8 -> 1.8 >= 1.4378 (Significant)
XofN VarRed Org and XofN Vouk Org -> |1.89 - 3.33| = 1.44 -> 1.44 >= 1.4378 (Significant)

Holm's test:
XofN VarRed Org vs XofN_none N/A -> p:0.0006 < adj_a:0.0125 (Significant)
XofN VarRed Org vs XofN Vouk Org -> p:0.0063 < adj_a:0.0167 (Significant)
XofN VarRed Org vs XofN Vouk Ung -> p:0.0084 < adj_a:0.025 (Significant)
XofN VarRed Org vs XofN VarRed Ung -> p:0.0809 >= adj_a:0.05 (Not Significant)

-- Hamming Loss VarRed --
Friedman test: p-value = 0.0324 (Significant)

Nemenyi's test (CD = 1.4378):
XofN_none N/A and XofN Vouk Org -> |2.31 - 3.86| = 1.55 -> 1.55 >= 1.4378 (Significant)

Holm's test:
XofN_none N/A vs XofN Vouk Org -> p:0.0033 < adj_a:0.0125 (Significant)
XofN_none N/A vs XofN Vouk Ung -> p:0.0745 >= adj_a:0.0167 (Not Significant)

-- Subset Accuracy VarRed --
Friedman test: p-value = 0.0146 (Significant)

Nemenyi's test (CD = 1.4378):
XofN VarRed Ung and XofN Vouk Org -> |2.22 - 3.81| = 1.59 -> 1.59 >= 1.4378 (Significant)

Holm's test:
XofN VarRed Ung vs XofN Vouk Org -> p:0.0026 < adj_a:0.0125 (Significant)
XofN VarRed Ung vs XofN Vouk Ung -> p:0.0129 < adj_a:0.0167 (Significant)
XofN VarRed Ung vs XofN_none N/A -> p:0.3146 >= adj_a:0.025 (Not Significant)

-- Macro-F1 VarRed --
Friedman test: p-value = 0.3355 (Not Significant)

-- Macro-Precision VarRed --
Friedman test: p-value = 0.3454 (Not Significant)

-- Macro-Recall VarRed --
Friedman test: p-value = 0.3925 (Not Significant)

-- Ranking Loss VarRed --
Friedman test: p-value = 0.9167 (Not Significant)

-- Macro-AUROC VarRed Ung --
Friedman test: p-value = 0.1658 (Not Significant)

-- Hamming Loss VarRed Ung --
Friedman test: p-value = 0.1880 (Not Significant)

-- Subset Accuracy VarRed Ung --
Friedman test: p-value = 0.0839 (Not Significant)

-- Macro-F1 VarRed Ung --
Friedman test: p-value = 0.3577 (Not Significant)

-- Macro-Precision VarRed Ung --
Friedman test: p-value = 0.2351 (Not Significant)

-- Macro-Recall VarRed Ung --
Friedman test: p-value = 0.3955 (Not Significant)

-- Ranking Loss VarRed Ung --
Friedman test: p-value = 0.6723 (Not Significant)

-- Macro-AUROC VarRed Org --
Friedman test: p-value = 0.0020 (Significant)

Nemenyi's test (CD = 0.7810):
XofN_none N/A and XofN VarRed Org -> |2.42 - 1.33| = 1.09 -> 1.09 >= 0.781 (Significant)
XofN VarRed Org and XofN Vouk Org -> |1.33 - 2.25| = 0.92 -> 0.92 >= 0.781 (Significant)

Holm's test:
XofN VarRed Org vs XofN_none N/A -> p:0.0011 < adj_a:0.025 (Significant)
XofN VarRed Org vs XofN Vouk Org -> p:0.0058 < adj_a:0.05 (Significant)

-- Hamming Loss VarRed Org --
Friedman test: p-value = 0.0286 (Significant)

Nemenyi's test (CD = 0.7810):
XofN_none N/A and XofN Vouk Org -> |1.56 - 2.44| = 0.88 -> 0.88 >= 0.781 (Significant)

Holm's test:
XofN_none N/A vs XofN Vouk Org -> p:0.0083 < adj_a:0.025 (Significant)
XofN_none N/A vs XofN VarRed Org -> p:0.1868 >= adj_a:0.05 (Not Significant)

-- Subset Accuracy VarRed Org --
Friedman test: p-value = 0.1334 (Not Significant)

-- Macro-F1 VarRed Org --
Friedman test: p-value = 0.2111 (Not Significant)

-- Macro-Precision VarRed Org --
Friedman test: p-value = 0.3892 (Not Significant)

-- Macro-Recall VarRed Org --
Friedman test: p-value = 0.1787 (Not Significant)

-- Ranking Loss VarRed Org --
Friedman test: p-value = 0.5313 (Not Significant)

In [13]:
# reset approaches to all
approaches = [
    "Dataset",  # index column
    "XofN_none N/A",
    "XofN Jac-max Ung",
    "XofN Jac-max Org",
    "XofN VarRed Ung",
    "XofN VarRed Org",
    "XofN Vouk Ung",
    "XofN Vouk Org",
]

In [14]:
# Nodes; Leaves
all_results_table = pd.read_csv("all_results_table.csv")
all_results_table.loc[
    all_results_table["XofN method"] == "XofN_none", "Ung or Org"
] = "N/A"
all_results_table.columns = all_results_table.columns.str.strip()
pivot = all_results_table.pivot_table(
    index=["Dataset"],
    columns=["XofN method", "Ung or Org"],
    values="Nodes; Leaves",
    aggfunc="first"
)

pivot.columns = [f"{a} {b}" for a, b in pivot.columns]
pivot = pivot.reset_index()
pivot = pivot.sort_values(by="Dataset", ascending=False)
pivot_column_order = approaches.copy()
pivot = pivot.reindex(columns=pivot_column_order)
pivot = sort_dataset(pivot)
pivot.to_csv("Nodes Leaves.csv", index=False)
pivot

,Dataset,XofN_none N/A,XofN Jac-max Ung,XofN Jac-max Org,XofN VarRed Ung,XofN VarRed Org,XofN Vouk Ung,XofN Vouk Org
13,fingerprint_high_freq,18.8; 9.9,43.8; 22.4,46.4; 23.7,42.4; 21.7,48.0; 24.5,35.8; 18.4,45.0; 23.0
15,fingerprint_mid_freq,161.0; 81.0,158.0; 79.5,164.0; 82.5,145.2; 73.1,152.2; 76.6,133.6; 67.3,172.8; 86.9
14,fingerprint_low_freq,8.8; 4.9,1.0; 1.0,7.6; 4.3,27.6; 14.3,27.2; 14.1,50.0; 25.5,63.0; 32.0
12,fingerprint_cardiac,8.6; 4.8,18.6; 9.8,35.4; 18.2,52.2; 26.6,55.8; 28.4,46.6; 23.8,54.4; 27.7
16,fingerprint_ten,151.6; 76.3,160.6; 80.8,154.4; 77.7,149.4; 75.2,158.4; 79.7,136.4; 68.7,163.4; 82.2
17,fingerprint_ten_mid,85.6; 43.3,98.4; 49.7,109.6; 55.3,89.4; 45.2,95.6; 48.3,80.4; 40.7,102.8; 51.9
7,CPI_high_freq,22.4; 11.7,17.0; 9.0,29.6; 15.3,28.6; 14.8,33.8; 17.4,14.2; 7.6,32.0; 16.5
9,CPI_mid_freq,127.8; 64.4,108.8; 54.9,132.8; 66.9,95.0; 48.0,112.4; 56.7,77.8; 39.4,119.8; 60.4
8,CPI_low_freq,49.4; 25.2,53.2; 27.1,57.2; 29.1,42.4; 21.7,49.0; 25.0,53.8; 27.4,60.4; 30.7
6,CPI_cardiac,52.0; 26.5,55.4; 28.2,64.4; 32.7,46.0; 23.5,57.4; 29.2,46.2; 23.6,53.0; 27.0
10,CPI_ten,108.0; 54.5,95.4; 48.2,103.4; 52.2,88.6; 44.8,102.0; 51.5,61.4; 31.2,94.6; 47.8
11,CPI_ten_mid,68.8; 34.9,71.0; 36.0,88.0; 44.5,61.0; 31.0,78.4; 39.7,57.6; 29.3,75.2; 38.1
1,CPI+fingerprint_high_freq,61.2; 31.1,65.8; 33.4,76.8; 38.9,64.2; 32.6,72.4; 36.7,41.4; 21.2,62.4; 31.7
3,CPI+fingerprint_mid_freq,160.8; 80.9,150.6; 75.8,161.0; 81.0,134.4; 67.7,157.6; 79.3,135.6; 68.3,170.2; 85.6
2,CPI+fingerprint_low_freq,60.0; 30.5,61.4; 31.2,68.6; 34.8,58.8; 29.9,61.0; 31.0,59.8; 30.4,69.6; 35.3
0,CPI+fingerprint_cardiac,75.4; 38.2,77.8; 39.4,85.2; 43.1,69.2; 35.1,77.4; 39.2,67.0; 34.0,85.0; 43.0
4,CPI+fingerprint_ten,171.8; 86.4,168.2; 84.6,175.2; 88.1,142.8; 71.9,166.8; 83.9,139.2; 70.1,170.6; 85.8
5,CPI+fingerprint_ten_mid,102.4; 51.7,91.6; 46.3,109.0; 55.0,82.2; 41.6,96.2; 48.6,93.2; 47.1,106.6; 53.8

In [15]:
# #XofN; #Feat/XofN
all_results_table = pd.read_csv("all_results_table.csv")
all_results_table.loc[
    all_results_table["XofN method"] == "XofN_none", "Ung or Org"
] = "N/A"
all_results_table.columns = all_results_table.columns.str.strip()
pivot = all_results_table.pivot_table(
    index=["Dataset"],
    columns=["XofN method", "Ung or Org"],
    values="#XofN; #Feat/XofN",
    aggfunc="first"
)

pivot.columns = [f"{a} {b}" for a, b in pivot.columns]
pivot = pivot.reset_index()
pivot = pivot.sort_values(by="Dataset", ascending=False)
pivot_column_order = approaches.copy()
pivot = pivot.reindex(columns=pivot_column_order)
pivot = sort_dataset(pivot)
pivot.to_csv("#XofN #Feat per XofN.csv", index=False)
pivot

,Dataset,XofN_none N/A,XofN Jac-max Ung,XofN Jac-max Org,XofN VarRed Ung,XofN VarRed Org,XofN Vouk Ung,XofN Vouk Org
13,fingerprint_high_freq,NaN,108.0; 5.0,108.0; 5.0,110.9; 4.9,110.9; 4.9,78.1; 3.1,78.1; 3.1
15,fingerprint_mid_freq,NaN,108.0; 5.0,108.0; 5.0,110.1; 4.9,110.1; 4.9,78.7; 2.8,78.7; 2.8
14,fingerprint_low_freq,NaN,108.0; 5.0,108.0; 5.0,112.0; 4.8,112.0; 4.8,141.9; 3.5,141.9; 3.5
12,fingerprint_cardiac,NaN,108.0; 5.0,108.0; 5.0,111.0; 4.8,111.0; 4.8,78.0; 3.7,78.0; 3.7
16,fingerprint_ten,NaN,108.0; 5.0,108.0; 5.0,109.8; 4.9,109.8; 4.9,108.9; 2.3,108.9; 2.3
17,fingerprint_ten_mid,NaN,108.0; 5.0,108.0; 5.0,110.8; 4.9,110.8; 4.9,152.9; 2.9,152.9; 2.9
7,CPI_high_freq,NaN,322.0; 5.0,322.0; 5.0,343.6; 4.6,343.6; 4.6,87.9; 3.2,87.9; 3.2
9,CPI_mid_freq,NaN,322.0; 5.0,322.0; 5.0,335.6; 4.7,335.6; 4.7,140.2; 2.3,140.2; 2.3
8,CPI_low_freq,NaN,322.0; 5.0,322.0; 5.0,331.2; 4.8,331.2; 4.8,393.1; 2.9,393.1; 2.9
6,CPI_cardiac,NaN,322.0; 5.0,322.0; 5.0,355.6; 4.4,355.6; 4.4,385.2; 2.8,385.2; 2.8
10,CPI_ten,NaN,322.0; 5.0,322.0; 5.0,331.6; 4.8,331.6; 4.8,253.7; 3.4,253.7; 3.4
11,CPI_ten_mid,NaN,322.0; 5.0,322.0; 5.0,329.6; 4.8,329.6; 4.8,292.6; 2.5,292.6; 2.5
1,CPI+fingerprint_high_freq,NaN,430.0; 5.0,430.0; 5.0,455.8; 4.7,455.8; 4.7,72.5; 3.4,72.5; 3.4
3,CPI+fingerprint_mid_freq,NaN,430.0; 5.0,430.0; 5.0,448.3; 4.7,448.3; 4.7,126.0; 2.9,126.0; 2.9
2,CPI+fingerprint_low_freq,NaN,430.0; 5.0,430.0; 5.0,439.4; 4.9,439.4; 4.9,208.5; 3.1,208.5; 3.1
0,CPI+fingerprint_cardiac,NaN,430.0; 5.0,430.0; 5.0,468.7; 4.5,468.7; 4.5,151.4; 3.2,151.4; 3.2
4,CPI+fingerprint_ten,NaN,430.0; 5.0,430.0; 5.0,442.5; 4.8,442.5; 4.8,124.8; 2.7,124.8; 2.7
5,CPI+fingerprint_ten_mid,NaN,430.0; 5.0,430.0; 5.0,438.4; 4.8,438.4; 4.8,176.2; 2.9,176.2; 2.9

In [16]:
# #Ung. Feats
all_results_table = pd.read_csv("all_results_table.csv")
all_results_table.loc[
    all_results_table["XofN method"] == "XofN_none", "Ung or Org"
] = "N/A"
all_results_table.columns = all_results_table.columns.str.strip()
all_results_table["#Ung. Feats"] = all_results_table["#Ung. Feats"].round(2)
pivot = all_results_table.pivot_table(
    index=["Dataset"],
    columns=["XofN method", "Ung or Org"],
    values="#Ung. Feats",
    aggfunc="first"
)

pivot.columns = [f"{a} {b}" for a, b in pivot.columns]
pivot = pivot.reset_index()
pivot = pivot.sort_values(by="Dataset", ascending=False)
pivot_column_order = approaches.copy()
pivot = pivot.reindex(columns=pivot_column_order)
pivot = sort_dataset(pivot)
pivot.to_csv("#Ung. Feats.csv", index=False)
pivot

,Dataset,XofN_none N/A,XofN Jac-max Ung,XofN Jac-max Org,XofN VarRed Ung,XofN VarRed Org,XofN Vouk Ung,XofN Vouk Org
13,fingerprint_high_freq,NaN,0.0,0.0,2.05,2.05,469.8,469.8
15,fingerprint_mid_freq,NaN,0.0,0.0,1.57,1.57,461.2,461.2
14,fingerprint_low_freq,NaN,0.0,0.0,0.92,0.92,413.1,413.1
12,fingerprint_cardiac,NaN,0.0,0.0,2.57,2.57,446.2,446.2
16,fingerprint_ten,NaN,0.0,0.0,0.96,0.96,449.0,449.0
17,fingerprint_ten_mid,NaN,0.0,0.0,1.48,1.48,408.1,408.1
7,CPI_high_freq,NaN,0.0,0.0,9.27,9.27,1551.6,1551.6
9,CPI_mid_freq,NaN,0.0,0.0,33.04,33.04,1528.5,1528.5
8,CPI_low_freq,NaN,0.0,0.0,2.06,2.06,1456.7,1456.7
6,CPI_cardiac,NaN,0.0,0.0,25.00,25.00,1476.7,1476.7
10,CPI_ten,NaN,0.0,0.0,6.53,6.53,1509.5,1509.5
11,CPI_ten_mid,NaN,0.0,0.0,28.89,28.89,1481.3,1481.3
1,CPI+fingerprint_high_freq,NaN,0.0,0.0,8.63,8.63,2077.3,2077.3
3,CPI+fingerprint_mid_freq,NaN,0.0,0.0,28.59,28.59,2043.8,2043.8
2,CPI+fingerprint_low_freq,NaN,0.0,0.0,3.04,3.04,1982.6,1982.6
0,CPI+fingerprint_cardiac,NaN,0.0,0.0,17.58,17.58,2018.9,2018.9
4,CPI+fingerprint_ten,NaN,0.0,0.0,6.10,6.10,2040.4,2040.4
5,CPI+fingerprint_ten_mid,NaN,0.0,0.0,30.18,30.18,1997.2,1997.2

In [17]:
# XofN time (s); PCT tr. time (s)
all_results_table = pd.read_csv("all_results_table.csv")
all_results_table.loc[
    all_results_table["XofN method"] == "XofN_none", "Ung or Org"
] = "N/A"
all_results_table.columns = all_results_table.columns.str.strip()
pivot = all_results_table.pivot_table(
    index=["Dataset"],
    columns=["XofN method", "Ung or Org"],
    values="XofN time (s); PCT tr. time (s)",
    aggfunc="first"
)

pivot.columns = [f"{a} {b}" for a, b in pivot.columns]
pivot = pivot.reset_index()
pivot = pivot.sort_values(by="Dataset", ascending=False)
pivot_column_order = approaches.copy()
pivot = pivot.reindex(columns=pivot_column_order)
pivot = sort_dataset(pivot)
pivot.to_csv("XofN time (s) PCT tr. time (s).csv", index=False)
pivot

,Dataset,XofN_none N/A,XofN Jac-max Ung,XofN Jac-max Org,XofN VarRed Ung,XofN VarRed Org,XofN Vouk Ung,XofN Vouk Org
13,fingerprint_high_freq,1.0,78.2; 0.7,78.2; 1.3,94.5; 0.7,94.5; 1.3,4.1; 0.6,4.1; 1.4
15,fingerprint_mid_freq,1.1,78.3; 0.7,78.3; 1.3,94.7; 0.7,94.7; 1.3,4.3; 0.6,4.3; 1.2
14,fingerprint_low_freq,1.1,78.4; 0.7,78.4; 1.3,94.7; 0.7,94.7; 1.3,6.7; 0.8,6.7; 1.5
12,fingerprint_cardiac,1.1,78.1; 0.7,78.1; 1.3,94.1; 0.7,94.1; 1.3,5.7; 0.7,5.7; 1.4
16,fingerprint_ten,1.1,74.4; 0.7,74.4; 1.3,94.2; 0.7,94.2; 1.4,3.9; 0.7,3.9; 1.4
17,fingerprint_ten_mid,1.1,75.7; 0.7,75.7; 1.3,96.1; 0.7,96.1; 1.3,4.5; 0.8,4.5; 1.4
7,CPI_high_freq,2.4,356.2; 0.9,356.2; 2.6,466.8; 0.9,466.8; 2.6,16.3; 0.6,16.3; 2.7
9,CPI_mid_freq,2.5,359.1; 1.0,359.1; 2.9,463.5; 0.9,463.5; 2.5,15.8; 0.8,15.8; 2.6
8,CPI_low_freq,2.5,358.1; 1.1,358.1; 3.0,459.8; 0.9,459.8; 2.6,22.9; 1.2,22.9; 3.2
6,CPI_cardiac,2.8,355.0; 1.0,355.0; 3.0,464.8; 0.9,464.8; 2.6,26.3; 1.2,26.3; 3.4
10,CPI_ten,2.4,343.3; 1.0,343.3; 2.7,421.4; 0.9,421.4; 2.5,12.7; 0.9,12.7; 2.6
11,CPI_ten_mid,2.8,349.7; 1.1,349.7; 3.1,429.9; 0.9,429.9; 2.7,14.8; 1.0,14.8; 3.0
1,CPI+fingerprint_high_freq,2.9,534.4; 1.2,534.4; 3.5,716.8; 1.3,716.8; 3.7,13.5; 0.7,13.5; 3.5
3,CPI+fingerprint_mid_freq,2.9,537.5; 1.1,537.5; 3.5,719.9; 1.2,719.9; 3.6,16.3; 0.8,16.3; 3.6
2,CPI+fingerprint_low_freq,3.1,536.2; 1.2,536.2; 3.9,710.4; 1.3,710.4; 3.9,18.0; 1.1,18.0; 4.2
0,CPI+fingerprint_cardiac,3.2,527.2; 1.2,527.2; 3.9,702.6; 1.3,702.6; 3.9,18.8; 1.0,18.8; 4.1
4,CPI+fingerprint_ten,3.0,506.8; 1.1,506.8; 3.6,712.8; 1.2,712.8; 3.9,16.1; 0.8,16.1; 3.8
5,CPI+fingerprint_ten_mid,3.1,574.4; 1.2,574.4; 4.0,697.8; 1.2,697.8; 3.7,19.4; 0.9,19.4; 3.4