In [1]:
%load_ext autoreload
%autoreload 2
import sys, os
sys.path.insert(0, os.path.abspath("C:/Users/Voror/Projects/Personal/sep"))
from sklearn.model_selection import KFold
from SIDER_dataset.libraries.XofN_library import *
from SIDER_dataset.libraries.PCT_library import run_PCT
from SIDER_dataset.libraries.feature_evaluation_methods import feature_variance_reduction_scores
from SIDER_dataset.libraries.utils import get_clus_path

In [2]:
# Set ADR to predict and scoring
clus_path = get_clus_path()
paths = get_dataset_paths()
print(len(paths), "datasets")
paths

18 datasets

[{'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_cardiac.csv',
  'dataset_name': 'CPI+fingerprint_cardiac',
  'label_set': ['se_C0016382',
   'se_C0018799',
   'se_C0003811',
   'se_C0428977',
   'se_C0027051',
   'se_C0018790'],
  'features': 2147,
  'original_features': ['cpi_9606.ENSP00000000442',
   'cpi_9606.ENSP00000001008',
   'cpi_9606.ENSP00000003084',
   'cpi_9606.ENSP00000003100',
   'cpi_9606.ENSP00000005178',
   'cpi_9606.ENSP00000011292',
   'cpi_9606.ENSP00000011653',
   'cpi_9606.ENSP00000012443',
   'cpi_9606.ENSP00000013034',
   'cpi_9606.ENSP00000014930',
   'cpi_9606.ENSP00000019103',
   'cpi_9606.ENSP00000023897',
   'cpi_9606.ENSP00000039007',
   'cpi_9606.ENSP00000044462',
   'cpi_9606.ENSP00000054668',
   'cpi_9606.ENSP00000078429',
   'cpi_9606.ENSP00000155840',
   'cpi_9606.ENSP00000164139',
   'cpi_9606.ENSP00000171757',
   'cpi_9606.ENSP00000176183',
   'cpi_9606.ENSP00000176195',
   'cpi_9606.ENSP00000176763',
   'cpi_9606.ENSP00000178638',
   'cpi_9606.ENSP00000181383',
   'cpi_9606.ENSP00000196551',
   'cpi_9606.ENSP00000199280',
   'cpi_9606.ENSP00000200676',
   'cpi_9606.ENSP00000206249',
   'cpi_9606.ENSP00000211122',
   'cpi_9606.ENSP00000211287',
   'cpi_9606.ENSP00000212015',
   'cpi_9606.ENSP00000215659',
   'cpi_9606.ENSP00000215832',
   'cpi_9606.ENSP00000215904',
   'cpi_9606.ENSP00000215956',
   'cpi_9606.ENSP00000216024',
   'cpi_9606.ENSP00000216037',
   'cpi_9606.ENSP00000216117',
   'cpi_9606.ENSP00000216185',
   'cpi_9606.ENSP00000216341',
   'cpi_9606.ENSP00000216392',
   'cpi_9606.ENSP00000216410',
   'cpi_9606.ENSP00000216455',
   'cpi_9606.ENSP00000216465',
   'cpi_9606.ENSP00000216540',
   'cpi_9606.ENSP00000216629',
   'cpi_9606.ENSP00000216714',
   'cpi_9606.ENSP00000216797',
   'cpi_9606.ENSP00000216862',
   'cpi_9606.ENSP00000216911',
   'cpi_9606.ENSP00000216962',
   'cpi_9606.ENSP00000217133',
   'cpi_9606.ENSP00000217244',
   'cpi_9606.ENSP00000217270',
   'cpi_9606.ENSP00000217305',
   'cpi_9606.ENSP00000217386',
   'cpi_9606.ENSP00000217426',
   'cpi_9606.ENSP00000217961',
   'cpi_9606.ENSP00000218099',
   'cpi_9606.ENSP00000218388',
   'cpi_9606.ENSP00000218548',
   'cpi_9606.ENSP00000218721',
   'cpi_9606.ENSP00000218758',
   'cpi_9606.ENSP00000219070',
   'cpi_9606.ENSP00000219240',
   'cpi_9606.ENSP00000219252',
   'cpi_9606.ENSP00000219700',
   'cpi_9606.ENSP00000219794',
   'cpi_9606.ENSP00000219833',
   'cpi_9606.ENSP00000219919',
   'cpi_9606.ENSP00000220003',
   'cpi_9606.ENSP00000220616',
   'cpi_9606.ENSP00000220764',
   'cpi_9606.ENSP00000220809',
   'cpi_9606.ENSP00000221130',
   'cpi_9606.ENSP00000221138',
   'cpi_9606.ENSP00000221421',
   'cpi_9606.ENSP00000221515',
   'cpi_9606.ENSP00000221930',
   'cpi_9606.ENSP00000221972',
   'cpi_9606.ENSP00000222002',
   'cpi_9606.ENSP00000222256',
   'cpi_9606.ENSP00000222330',
   'cpi_9606.ENSP00000222381',
   'cpi_9606.ENSP00000222390',
   'cpi_9606.ENSP00000222481',
   'cpi_9606.ENSP00000222482',
   'cpi_9606.ENSP00000222553',
   'cpi_9606.ENSP00000222982',
   'cpi_9606.ENSP00000223095',
   'cpi_9606.ENSP00000223366',
   'cpi_9606.ENSP00000223642',
   'cpi_9606.ENSP00000224784',
   'cpi_9606.ENSP00000225275',
   'cpi_9606.ENSP00000225371',
   'cpi_9606.ENSP00000225426',
   'cpi_9606.ENSP00000225430',
   'cpi_9606.ENSP00000225474',
   'cpi_9606.ENSP00000225577',
   'cpi_9606.ENSP00000225740',
   'cpi_9606.ENSP00000225831',
   'cpi_9606.ENSP00000225927',
   'cpi_9606.ENSP00000225964',
   'cpi_9606.ENSP00000225992',
   'cpi_9606.ENSP00000226299',
   'cpi_9606.ENSP00000226317',
   'cpi_9606.ENSP00000226413',
   'cpi_9606.ENSP00000226444',
   'cpi_9606.ENSP00000226574',
   'cpi_9606.ENSP00000226578',
   'cpi_9606.ENSP00000226730',
   'cpi_9606.ENSP00000226840',
   'cpi_9606.ENSP00000227378',
   'cpi_9606.ENSP00000227507',
   'cpi_9606.ENSP00000227758',
   'cpi_9606.ENSP00000228476',
   'cpi_9606.ENSP00000228740',
   'cpi_9606.ENSP00000228872',
   'cpi_9606.ENSP00000229135',
   'cpi_9606.ENSP00000229239',
   'cpi_9606.ENSP00000229264',
   'cpi_9606.ENSP00000229270',
   'cpi_9606.ENSP00000229277',
   'cpi_9606.ENSP00000229319',
   'cpi_9606.ENSP00000229447',
   'cpi_9606.ENSP00000229794',
   'cpi_9606.ENSP00000230050',
   'cpi_9606.ENSP00000230671',
   'cpi_9606.ENSP00000231188',
   'cpi_9606.ENSP00000231228',
   'cpi_9606.ENSP00000231449',
   'cpi_9606.ENSP00000231454',
   'cpi_9606.ENSP00000231509',
   'cpi_9606.ENSP00000231751',
   'cpi_9606.ENSP00000231790',
   'cpi_9606.ENSP00000232219',
   'cpi_9606.ENSP00000232607',
   'cpi_9606.ENSP00000232892',
   'cpi_9606.ENSP00000233146',
   'cpi_9606.ENSP00000233242',
   'cpi_9606.ENSP00000233944',
   'cpi_9606.ENSP00000234071',
   'cpi_9606.ENSP00000234111',
   'cpi_9606.ENSP00000234310',
   'cpi_9606.ENSP00000234371',
   'cpi_9606.ENSP00000234389',
   'cpi_9606.ENSP00000234590',
   'cpi_9606.ENSP00000234961',
   'cpi_9606.ENSP00000235382',
   'cpi_9606.ENSP00000236671',
   'cpi_9606.ENSP00000236850',
   'cpi_9606.ENSP00000237014',
   'cpi_9606.ENSP00000237527',
   'cpi_9606.ENSP00000237612',
   'cpi_9606.ENSP00000237858',
   'cpi_9606.ENSP00000238018',
   'cpi_9606.ENSP00000238379',
   'cpi_9606.ENSP00000239223',
   'cpi_9606.ENSP00000239849',
   'cpi_9606.ENSP00000239938',
   'cpi_9606.ENSP00000240139',
   'cpi_9606.ENSP00000240615',
   'cpi_9606.ENSP00000240619',
   'cpi_9606.ENSP00000240652',
   'cpi_9606.ENSP00000240687',
   'cpi_9606.ENSP00000240691',
   'cpi_9606.ENSP00000240874',
   'cpi_9606.ENSP00000241052',
   'cpi_9606.ENSP00000241256',
   'cpi_9606.ENSP00000241261',
   'cpi_9606.ENSP00000241453',
   'cpi_9606.ENSP00000241600',
   'cpi_9606.ENSP00000242057',
   'cpi_9606.ENSP00000242152',
   'cpi_9606.ENSP00000242375',
   'cpi_9606.ENSP00000242839',
   'cpi_9606.ENSP00000243167',
   'cpi_9606.ENSP00000243911',
   'cpi_9606.ENSP00000244051',
   'cpi_9606.ENSP00000244137',
   'cpi_9606.ENSP00000244217',
   'cpi_9606.ENSP00000244289',
   'cpi_9606.ENSP00000244741',
   'cpi_9606.ENSP00000245206',
   'cpi_9606.ENSP00000245457',
   'cpi_9606.ENSP00000245539',
   'cpi_9606.ENSP00000245907',
   'cpi_9606.ENSP00000245983',
   'cpi_9606.ENSP00000246115',
   'cpi_9606.ENSP00000246337',
   'cpi_9606.ENSP00000246549',
   'cpi_9606.ENSP00000246553',
   'cpi_9606.ENSP00000246657',
   'cpi_9606.ENSP00000247879',
   'cpi_9606.ENSP00000247881',
   'cpi_9606.ENSP00000247883',
   'cpi_9606.ENSP00000248041',
   'cpi_9606.ENSP00000248076',
   'cpi_9606.ENSP00000248437',
   'cpi_9606.ENSP00000248553',
   'cpi_9606.ENSP00000248572',
   'cpi_9606.ENSP00000248923',
   'cpi_9606.ENSP00000248935',
   'cpi_9606.ENSP00000249016',
   'cpi_9606.ENSP00000249041',
   'cpi_9606.ENSP00000249284',
   'cpi_9606.ENSP00000249750',
   'cpi_9606.ENSP00000250378',
   'cpi_9606.ENSP00000250615',
   'cpi_9606.ENSP00000250971',
   'cpi_9606.ENSP00000251453',
   'cpi_9606.ENSP00000251535',
   'cpi_9606.ENSP00000251566',
   'cpi_9606.ENSP00000251595',
   'cpi_9606.ENSP00000251810',
   'cpi_9606.ENSP00000251849',
   'cpi_9606.ENSP00000252029',
   'cpi_9606.ENSP00000252321',
   'cpi_9606.ENSP00000252486',
   'cpi_9606.ENSP00000252519',
   'cpi_9606.ENSP00000252723',
   'cpi_9606.ENSP00000252804',
   'cpi_9606.ENSP00000252809',
   'cpi_9606.ENSP00000252945',
   'cpi_9606.ENSP00000253004',
   'cpi_9606.ENSP00000253099',
   'cpi_9606.ENSP00000253122',
   'cpi_9606.ENSP00000253303',
   'cpi_9606.ENSP00000253727',
   'cpi_9606.ENSP00000253792',
   'cpi_9606.ENSP00000253799',
   'cpi_9606.ENSP00000254066',
   'cpi_9606.ENSP00000254079',
   'cpi_9606.ENSP00000254227',
   'cpi_9606.ENSP00000254235',
   'cpi_9606.ENSP00000254488',
   'cpi_9606.ENSP00000254810',
   'cpi_9606.ENSP00000254976',
   'cpi_9606.ENSP00000255008',
   'cpi_9606.ENSP00000255030',
   'cpi_9606.ENSP00000255084',
   'cpi_9606.ENSP00000255262',
   'cpi_9606.ENSP00000255380',
   'cpi_9606.ENSP00000255409',
   'cpi_9606.ENSP00000255465',
   'cpi_9606.ENSP00000256010',
   'cpi_9606.ENSP00000256078',
   'cpi_9606.ENSP00000256104',
   'cpi_9606.ENSP00000256119',
   'cpi_9606.ENSP00000256383',
   'cpi_9606.ENSP00000256442',
   'cpi_9606.ENSP00000256578',
   'cpi_9606.ENSP00000256722',
   'cpi_9606.ENSP00000256857',
   'cpi_9606.ENSP00000256906',
   'cpi_9606.ENSP00000256958',
   'cpi_9606.ENSP00000256999',
   'cpi_9606.ENSP00000257068',
   'cpi_9606.ENSP00000257254',
   'cpi_9606.ENSP00000257290',
   'cpi_9606.ENSP00000257497',
   'cpi_9606.ENSP00000257770',
   'cpi_9606.ENSP00000258042',
   'cpi_9606.ENSP00000258317',
   'cpi_9606.ENSP00000258400',
   'cpi_9606.ENSP00000258662',
   'cpi_9606.ENSP00000258743',
   'cpi_9606.ENSP00000258749',
   'cpi_9606.ENSP00000259089',
   'cpi_9606.ENSP00000259271',
   'cpi_9606.ENSP00000259396',
   'cpi_9606.ENSP00000259457',
   'cpi_9606.ENSP00000259469',
   'cpi_9606.ENSP00000259486',
   'cpi_9606.ENSP00000259607',
   'cpi_9606.ENSP00000259631',
   'cpi_9606.ENSP00000259667',
   'cpi_9606.ENSP00000259818',
   'cpi_9606.ENSP00000260010',
   'cpi_9606.ENSP00000260102',
   'cpi_9606.ENSP00000260191',
   'cpi_9606.ENSP00000260227',
   'cpi_9606.ENSP00000260302',
   'cpi_9606.ENSP00000260356',
   'cpi_9606.ENSP00000260402',
   'cpi_9606.ENSP00000260433',
   'cpi_9606.ENSP00000260443',
   'cpi_9606.ENSP00000260600',
   'cpi_9606.ENSP00000260630',
   'cpi_9606.ENSP00000260649',
   'cpi_9606.ENSP00000260682',
   'cpi_9606.ENSP00000260970',
   'cpi_9606.ENSP00000261196',
   'cpi_9606.ENSP00000261205',
   'cpi_9606.ENSP00000261267',
   'cpi_9606.ENSP00000261386',
   'cpi_9606.ENSP00000261405',
   'cpi_9606.ENSP00000261416',
   'cpi_9606.ENSP00000261465',
   'cpi_9606.ENSP00000261479',
   'cpi_9606.ENSP00000261693',
   'cpi_9606.ENSP00000261707',
   'cpi_9606.ENSP00000261733',
   'cpi_9606.ENSP00000261755',
   'cpi_9606.ENSP00000261769',
   'cpi_9606.ENSP00000261799',
   'cpi_9606.ENSP00000261835',
   'cpi_9606.ENSP00000261937',
   'cpi_9606.ENSP00000262017',
   'cpi_9606.ENSP00000262027',
   'cpi_9606.ENSP00000262160',
   'cpi_9606.ENSP00000262178',
   'cpi_9606.ENSP00000262186',
   'cpi_9606.ENSP00000262187',
   'cpi_9606.ENSP00000262193',
   'cpi_9606.ENSP00000262290',
   'cpi_9606.ENSP00000262352',
   'cpi_9606.ENSP00000262367',
   'cpi_9606.ENSP00000262407',
   'cpi_9606.ENSP00000262441',
   'cpi_9606.ENSP00000262461',
   'cpi_9606.ENSP00000262545',
   'cpi_9606.ENSP00000262584',
   'cpi_9606.ENSP00000262623',
   'cpi_9606.ENSP00000262735',
   'cpi_9606.ENSP00000262848',
   'cpi_9606.ENSP00000262888',
   'cpi_9606.ENSP00000262948',
   'cpi_9606.ENSP00000262958',
   'cpi_9606.ENSP00000262999',
   'cpi_9606.ENSP00000263025',
   'cpi_9606.ENSP00000263088',
   'cpi_9606.ENSP00000263126',
   'cpi_9606.ENSP00000263212',
   'cpi_9606.ENSP00000263269',
   'cpi_9606.ENSP00000263321',
   'cpi_9606.ENSP00000263339',
   'cpi_9606.ENSP00000263341',
   'cpi_9606.ENSP00000263377',
   'cpi_9606.ENSP00000263431',
   'cpi_9606.ENSP00000263464',
   'cpi_9606.ENSP00000263686',
   'cpi_9606.ENSP00000263817',
   'cpi_9606.ENSP00000263857',
   'cpi_9606.ENSP00000263923',
   'cpi_9606.ENSP00000263967',
   'cpi_9606.ENSP00000263980',
   'cpi_9606.ENSP00000264071',
   'cpi_9606.ENSP00000264162',
   'cpi_9606.ENSP00000264218',
   'cpi_9606.ENSP00000264318',
   'cpi_9606.ENSP00000264357',
   'cpi_9606.ENSP00000264381',
   'cpi_9606.ENSP00000264382',
   'cpi_9606.ENSP00000264399',
   'cpi_9606.ENSP00000264426',
   'cpi_9606.ENSP00000264498',
   'cpi_9606.ENSP00000264613',
   'cpi_9606.ENSP00000264637',
   'cpi_9606.ENSP00000264657',
   'cpi_9606.ENSP00000264668',
   'cpi_9606.ENSP00000264705',
   'cpi_9606.ENSP00000264708',
   'cpi_9606.ENSP00000264818',
   'cpi_9606.ENSP00000264832',
   'cpi_9606.ENSP00000264867',
   'cpi_9606.ENSP00000264896',
   'cpi_9606.ENSP00000264932',
   'cpi_9606.ENSP00000264995',
   'cpi_9606.ENSP00000265023',
   'cpi_9606.ENSP00000265100',
   'cpi_9606.ENSP00000265164',
   'cpi_9606.ENSP00000265171',
   'cpi_9606.ENSP00000265174',
   'cpi_9606.ENSP00000265294',
   'cpi_9606.ENSP00000265403',
   'cpi_9606.ENSP00000265421',
   'cpi_9606.ENSP00000265563',
   'cpi_9606.ENSP00000265572',
   'cpi_9606.ENSP00000265643',
   'cpi_9606.ENSP00000265717',
   'cpi_9606.ENSP00000265723',
   'cpi_9606.ENSP00000265724',
   'cpi_9606.ENSP00000266376',
   'cpi_9606.ENSP00000266682',
   'cpi_9606.ENSP00000266970',
   'cpi_9606.ENSP00000267017',
   'cpi_9606.ENSP00000267101',
   'cpi_9606.ENSP00000267119',
   'cpi_9606.ENSP00000267163',
   'cpi_9606.ENSP00000267377',
   'cpi_9606.ENSP00000267549',
   'cpi_9606.ENSP00000267843',
   'cpi_9606.ENSP00000268035',
   'cpi_9606.ENSP00000268053',
   'cpi_9606.ENSP00000268124',
   'cpi_9606.ENSP00000268171',
   'cpi_9606.ENSP00000268251',
   'cpi_9606.ENSP00000268661',
   'cpi_9606.ENSP00000268695',
   'cpi_9606.ENSP00000269159',
   'cpi_9606.ENSP00000269305',
   'cpi_9606.ENSP00000269571',
   'cpi_9606.ENSP00000270142',
   'cpi_9606.ENSP00000270202',
   'cpi_9606.ENSP00000270349',
   'cpi_9606.ENSP00000270474',
   'cpi_9606.ENSP00000270570',
   'cpi_9606.ENSP00000270586',
   'cpi_9606.ENSP00000270625',
   'cpi_9606.ENSP00000270631',
   'cpi_9606.ENSP00000270776',
   'cpi_9606.ENSP00000271308',
   'cpi_9606.ENSP00000271331',
   'cpi_9606.ENSP00000271620',
   'cpi_9606.ENSP00000272065',
   'cpi_9606.ENSP00000272167',
   'cpi_9606.ENSP00000272190',
   'cpi_9606.ENSP00000272227',
   'cpi_9606.ENSP00000272298',
   'cpi_9606.ENSP00000272317',
   'cpi_9606.ENSP00000272644',
   'cpi_9606.ENSP00000272847',
   'cpi_9606.ENSP00000272928',
   'cpi_9606.ENSP00000273077',
   'cpi_9606.ENSP00000273398',
   'cpi_9606.ENSP00000273430',
   'cpi_9606.ENSP00000273550',
   'cpi_9606.ENSP00000274026',
   'cpi_9606.ENSP00000274335',
   'cpi_9606.ENSP00000274353',
   'cpi_9606.ENSP00000274545',
   'cpi_9606.ENSP00000274547',
   'cpi_9606.ENSP00000274606',
   'cpi_9606.ENSP00000274793',
   'cpi_9606.ENSP00000275216',
   'cpi_9606.ENSP00000275300',
   'cpi_9606.ENSP00000275493',
   'cpi_9606.ENSP00000275525',
   'cpi_9606.ENSP00000276198',
   'cpi_9606.ENSP00000276414',
   'cpi_9606.ENSP00000276431',
   'cpi_9606.ENSP00000276449',
   'cpi_9606.ENSP00000276571',
   'cpi_9606.ENSP00000276590',
   'cpi_9606.ENSP00000276651',
   'cpi_9606.ENSP00000277010',
   'cpi_9606.ENSP00000277120',
   'cpi_9606.ENSP00000277508',
   'cpi_9606.ENSP00000277541',
   'cpi_9606.ENSP00000277942',
   'cpi_9606.ENSP00000278175',
   'cpi_9606.ENSP00000278616',
   'cpi_9606.ENSP00000279178',
   'cpi_9606.ENSP00000279230',
   'cpi_9606.ENSP00000279387',
   'cpi_9606.ENSP00000279593',
   'cpi_9606.ENSP00000280155',
   'cpi_9606.ENSP00000280357',
   'cpi_9606.ENSP00000280701',
   'cpi_9606.ENSP00000280704',
   'cpi_9606.ENSP00000280706',
   'cpi_9606.ENSP00000281806',
   'cpi_9606.ENSP00000282018',
   'cpi_9606.ENSP00000282077',
   'cpi_9606.ENSP00000282091',
   'cpi_9606.ENSP00000282397',
   'cpi_9606.ENSP00000282561',
   'cpi_9606.ENSP00000282753',
   'cpi_9606.ENSP00000282841',
   'cpi_9606.ENSP00000282957',
   'cpi_9606.ENSP00000283254',
   'cpi_9606.ENSP00000283558',
   'cpi_9606.ENSP00000283635',
   'cpi_9606.ENSP00000283646',
   'cpi_9606.ENSP00000283916',
   'cpi_9606.ENSP00000284981',
   'cpi_9606.ENSP00000285238',
   'cpi_9606.ENSP00000285379',
   'cpi_9606.ENSP00000285381',
   'cpi_9606.ENSP00000285900',
   'cpi_9606.ENSP00000285930',
   'cpi_9606.ENSP00000285979',
   'cpi_9606.ENSP00000286091',
   'cpi_9606.ENSP00000286301',
   'cpi_9606.ENSP00000286355',
   'cpi_9606.ENSP00000286479',
   'cpi_9606.ENSP00000286548',
   'cpi_9606.ENSP00000286621',
   'cpi_9606.ENSP00000286648',
   'cpi_9606.ENSP00000286719',
   'cpi_9606.ENSP00000286758',
   'cpi_9606.ENSP00000287641',
   'cpi_9606.ENSP00000287713',
   'cpi_9606.ENSP00000287766',
   'cpi_9606.ENSP00000287820',
   'cpi_9606.ENSP00000287878',
   'cpi_9606.ENSP00000287907',
   'cpi_9606.ENSP00000287936',
   'cpi_9606.ENSP00000288022',
   'cpi_9606.ENSP00000288135',
   'cpi_9606.ENSP00000288139',
   'cpi_9606.ENSP00000288602',
   'cpi_9606.ENSP00000289753',
   'cpi_9606.ENSP00000290349',
   'cpi_9606.ENSP00000290378',
   'cpi_9606.ENSP00000290541',
   'cpi_9606.ENSP00000290866',
   'cpi_9606.ENSP00000291294',
   'cpi_9606.ENSP00000291295',
   'cpi_9606.ENSP00000291565',
   'cpi_9606.ENSP00000291700',
   'cpi_9606.ENSP00000292095',
   'cpi_9606.ENSP00000292147',
   'cpi_9606.ENSP00000292174',
   'cpi_9606.ENSP00000292301',
   'cpi_9606.ENSP00000292303',
   'cpi_9606.ENSP00000292427',
   'cpi_9606.ENSP00000292513',
   'cpi_9606.ENSP00000292896',
   'cpi_9606.ENSP00000293190',
   'cpi_9606.ENSP00000293230',
   'cpi_9606.ENSP00000293272',
   'cpi_9606.ENSP00000293275',
   'cpi_9606.ENSP00000293288',
   'cpi_9606.ENSP00000293330',
   'cpi_9606.ENSP00000293404',
   'cpi_9606.ENSP00000293636',
   'cpi_9606.ENSP00000293745',
   'cpi_9606.ENSP00000293778',
   'cpi_9606.ENSP00000293813',
   'cpi_9606.ENSP00000293842',
   'cpi_9606.ENSP00000293897',
   'cpi_9606.ENSP00000294016',
   'cpi_9606.ENSP00000294728',
   'cpi_9606.ENSP00000294954',
   'cpi_9606.ENSP00000295137',
   'cpi_9606.ENSP00000295256',
   'cpi_9606.ENSP00000295400',
   'cpi_9606.ENSP00000295448',
   'cpi_9606.ENSP00000295452',
   'cpi_9606.ENSP00000295453',
   'cpi_9606.ENSP00000295454',
   'cpi_9606.ENSP00000295491',
   'cpi_9606.ENSP00000295589',
   'cpi_9606.ENSP00000295598',
   'cpi_9606.ENSP00000295619',
   'cpi_9606.ENSP00000295683',
   'cpi_9606.ENSP00000295731',
   'cpi_9606.ENSP00000295834',
   'cpi_9606.ENSP00000295897',
   'cpi_9606.ENSP00000295930',
   'cpi_9606.ENSP00000296026',
   'cpi_9606.ENSP00000296027',
   'cpi_9606.ENSP00000296028',
   'cpi_9606.ENSP00000296046',
   'cpi_9606.ENSP00000296122',
   'cpi_9606.ENSP00000296140',
   'cpi_9606.ENSP00000296271',
   'cpi_9606.ENSP00000296277',
   'cpi_9606.ENSP00000296350',
   'cpi_9606.ENSP00000296370',
   'cpi_9606.ENSP00000296411',
   'cpi_9606.ENSP00000296412',
   'cpi_9606.ENSP00000296511',
   'cpi_9606.ENSP00000296522',
   'cpi_9606.ENSP00000296545',
   'cpi_9606.ENSP00000296641',
   'cpi_9606.ENSP00000296674',
   'cpi_9606.ENSP00000296677',
   'cpi_9606.ENSP00000296754',
   'cpi_9606.ENSP00000296871',
   'cpi_9606.ENSP00000297258',
   'cpi_9606.ENSP00000297261',
   'cpi_9606.ENSP00000297268',
   'cpi_9606.ENSP00000297313',
   'cpi_9606.ENSP00000297316',
   'cpi_9606.ENSP00000297323',
   'cpi_9606.ENSP00000297350',
   'cpi_9606.ENSP00000297469',
   'cpi_9606.ENSP00000297494',
   'cpi_9606.ENSP00000297770',
   'cpi_9606.ENSP00000297785',
   'cpi_9606.ENSP00000297792',
   'cpi_9606.ENSP00000297991',
   'cpi_9606.ENSP00000298139',
   'cpi_9606.ENSP00000298171',
   'cpi_9606.ENSP00000298283',
   'cpi_9606.ENSP00000298352',
   'cpi_9606.ENSP00000298386',
   'cpi_9606.ENSP00000298440',
   'cpi_9606.ENSP00000298472',
   'cpi_9606.ENSP00000299178',
   'cpi_9606.ENSP00000299267',
   'cpi_9606.ENSP00000299727',
   'cpi_9606.ENSP00000299766',
   'cpi_9606.ENSP00000299847',
   'cpi_9606.ENSP00000299855',
   'cpi_9606.ENSP00000300060',
   'cpi_9606.ENSP00000300061',
   'cpi_9606.ENSP00000300093',
   'cpi_9606.ENSP00000300108',
   'cpi_9606.ENSP00000300151',
   'cpi_9606.ENSP00000300289',
   'cpi_9606.ENSP00000300738',
   'cpi_9606.ENSP00000300900',
   'cpi_9606.ENSP00000301071',
   'cpi_9606.ENSP00000301072',
   'cpi_9606.ENSP00000301141',
   'cpi_9606.ENSP00000301146',
   'cpi_9606.ENSP00000301178',
   'cpi_9606.ENSP00000301420',
   'cpi_9606.ENSP00000301633',
   'cpi_9606.ENSP00000301634',
   'cpi_9606.ENSP00000301645',
   'cpi_9606.ENSP00000301891',
   'cpi_9606.ENSP00000301908',
   'cpi_9606.ENSP00000301974',
   'cpi_9606.ENSP00000302079',
   'cpi_9606.ENSP00000302111',
   'cpi_9606.ENSP00000302150',
   'cpi_9606.ENSP00000302393',
   'cpi_9606.ENSP00000302441',
   'cpi_9606.ENSP00000302486',
   'cpi_9606.ENSP00000302564',
   'cpi_9606.ENSP00000302620',
   'cpi_9606.ENSP00000302665',
   'cpi_9606.ENSP00000302707',
   'cpi_9606.ENSP00000302728',
   'cpi_9606.ENSP00000302811',
   'cpi_9606.ENSP00000302846',
   'cpi_9606.ENSP00000302886',
   'cpi_9606.ENSP00000302961',

In [3]:
paths = [path for path in paths if "ten_mid" in path["dataset_name"]]
len(paths)

3

In [4]:
k = 10
random_state = 42
performances = []
ranking_criteria = "MDI"  # or "VAR"
include_original_features_options = [True, False]
training_algorithm = "Jaccard"
eval_criteria = ["averageAUROC", "HammingLoss", "SubsetAccuracy", "RankingLoss", "MacroPrecision", "MacroRecall",
                 "MacroFOne"]
max_size = 5
cv_results = []

for idx, path in enumerate(paths, start=1):
    run_config = f"\n--- Running with label:'{path["label_set"]}' training_algorithm:'{training_algorithm}' eval_criterion:'{eval_criteria}' max_size:'{max_size}' ---"
    print(run_config)
    run_config_name = "_".join(
        [
            path["dataset_name"],
            training_algorithm,
            "_".join(eval_criteria),
            str(max_size),
        ]
    )
    logging_path = f"XofN_jaccard/logs/{run_config_name}_logs.txt"
    print(f"Logs can be found in {logging_path}.")
    logger = get_logger(logging_path)
    logger.info(run_config_name)

    # Load dataset
    current_df = pd.read_csv(path["dataset_path"])
    features = get_features(current_df, path["label_set"])
    # current_df = current_df[features[:10] + path["label_set"]]
    kf = KFold(n_splits=k, shuffle=True, random_state=random_state)
    for fold, (train_idx, test_idx) in enumerate(kf.split(current_df), start=1):
        print(f"\nFold {fold}/{k} ({path["dataset_name"]} {idx}/{len(paths)})")
        train_dataset = current_df.iloc[train_idx]
        test_dataset = current_df.iloc[test_idx]

        if ranking_criteria == "VAR":
            feature_rankings = feature_variance_reduction_scores(train_dataset[features],
                                                                 train_dataset[path["label_set"]])
        elif ranking_criteria == "MDI":
            feature_rankings = calculate_mdi_multi_rf(train_dataset, path["label_set"])
        else:
            raise NotImplementedError

        XofN_groupings, avg_features, gen_XofN_time = generate_XofN_list_multi_jaccard(
            train_dataset,
            feature_rankings,
            max_size,
            logger
        )
        if len(XofN_groupings) == 0:
            print("no XofN groupings were created")
        else:
            for include_original_features in include_original_features_options:
                current_train_dataset = group_features(
                    train_dataset,
                    path["label_set"],
                    XofN_groupings,
                    include_original_features,
                    verbose=True
                )

                current_test_dataset = group_features(
                    test_dataset,
                    path["label_set"],
                    XofN_groupings,
                    include_original_features,
                    verbose=True
                )

                current_train_dataset.to_csv(f"XofN_jaccard/tmp/train_dataset.csv", index=False)
                current_test_dataset.to_csv(f"XofN_jaccard/tmp/test_dataset.csv", index=False)

                training_start = time.perf_counter()
                original_res, pruned_res, training_time = run_PCT(clus_path,
                                                                  "XofN_jaccard/tmp/train_dataset.csv",
                                                                  path["label_set"],
                                                                  eval_criteria,
                                                                  test_dataset_path=f"XofN_jaccard/tmp/test_dataset.csv")
                pruned_performance = get_fold_results(pruned_res, eval_criteria, True, fold, include_original_features,
                                                      XofN_groupings,
                                                      gen_XofN_time,
                                                      training_time, path["dataset_name"])
                performances.append(pruned_performance)
                performance = get_fold_results(original_res, eval_criteria, False, fold, include_original_features,
                                               XofN_groupings,
                                               gen_XofN_time,
                                               training_time, path["dataset_name"])
                performances.append(performance)

    if len(performances) == 0:
        print("no XofN groupings were created in any fold")
    else:
        final_perf_df = pd.DataFrame(performances)
        averages = final_perf_df.groupby(["pruning", 'include_original_features', 'dataset'])[
            eval_criteria + ['nodes', 'leaves', 'groups',
                             'avg_group_features', 'gen_XofN_time', 'training_time']].mean().reset_index()
        print(averages)
        cv_results.append(averages)
        performances = []
# paths[0] - features[:10] desktop 0.29m
# laptop ??m
# desktop 11h

--- Running with label:'['se_C0009676', 'se_C0041657', 'se_C0002994', 'se_C0042571', 'se_C0004604', 'se_C0041834', 'se_C0085631', 'se_C0040822', 'se_C0042373', 'se_C0021053']' training_algorithm:'Jaccard' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_jaccard/logs/CPI+fingerprint_ten_mid_Jaccard_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [09:32<00:00,  3.75feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.577625, HammingLoss: 0.34964, SubsetAccuracy: 0.1223, RankingLoss: 0.3364, MacroPrecision: 0.53147, MacroRecall: 0.3331, MacroFOne: 0.40451,
pruning: False, include_original_features: with_org, averageAUROC: 0.5598991, HammingLoss: 0.42374, SubsetAccuracy: 0.035971, RankingLoss: 0.35431, MacroPrecision: 0.42807, MacroRecall: 0.48573, MacroFOne: 0.45186,
pruning: True, include_original_features: no_org, averageAUROC: 0.5665876, HammingLoss: 0.35899, SubsetAccuracy: 0.10791, RankingLoss: 0.35769, MacroPrecision: 0.50846, MacroRecall: 0.30838, MacroFOne: 0.37328,
pruning: False, include_original_features: no_org, averageAUROC: 0.5596082, HammingLoss: 0.42662, SubsetAccuracy: 0.057554, RankingLoss: 0.35056, MacroPrecision: 0.42153, MacroRecall: 0.47873, MacroFOne: 0.44634,

Fold 2/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [09:29<00:00,  3.77feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6028066, HammingLoss: 0.33885, SubsetAccuracy: 0.1223, RankingLoss: 0.35485, MacroPrecision: 0.51774, MacroRecall: 0.25558, MacroFOne: 0.34097,
pruning: False, include_original_features: with_org, averageAUROC: 0.6090106, HammingLoss: 0.38633, SubsetAccuracy: 0.064748, RankingLoss: 0.35095, MacroPrecision: 0.44388, MacroRecall: 0.54877, MacroFOne: 0.49019,
pruning: True, include_original_features: no_org, averageAUROC: 0.6162582, HammingLoss: 0.31511, SubsetAccuracy: 0.1295, RankingLoss: 0.33731, MacroPrecision: 0.59433, MacroRecall: 0.25205, MacroFOne: 0.35063,
pruning: False, include_original_features: no_org, averageAUROC: 0.6330552, HammingLoss: 0.38201, SubsetAccuracy: 0.05036, RankingLoss: 0.31777, MacroPrecision: 0.45326, MacroRecall: 0.54691, MacroFOne: 0.49222,

Fold 3/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [09:36<00:00,  3.72feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5762509, HammingLoss: 0.4, SubsetAccuracy: 0.10791, RankingLoss: 0.34956, MacroPrecision: 0.4752, MacroRecall: 0.28343, MacroFOne: 0.35426,
pruning: False, include_original_features: with_org, averageAUROC: 0.5854849, HammingLoss: 0.40647, SubsetAccuracy: 0.057554, RankingLoss: 0.35612, MacroPrecision: 0.47536, MacroRecall: 0.49963, MacroFOne: 0.48617,
pruning: True, include_original_features: no_org, averageAUROC: 0.5999331, HammingLoss: 0.38489, SubsetAccuracy: 0.11511, RankingLoss: 0.36127, MacroPrecision: 0.50762, MacroRecall: 0.27123, MacroFOne: 0.35289,
pruning: False, include_original_features: no_org, averageAUROC: 0.5700857, HammingLoss: 0.43741, SubsetAccuracy: 0.028777, RankingLoss: 0.37888, MacroPrecision: 0.43849, MacroRecall: 0.45662, MacroFOne: 0.44418,

Fold 4/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [09:36<00:00,  3.73feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5583314, HammingLoss: 0.35683, SubsetAccuracy: 0.1295, RankingLoss: 0.38362, MacroPrecision: 0.41791, MacroRecall: 0.237, MacroFOne: 0.30049,
pruning: False, include_original_features: with_org, averageAUROC: 0.5598076, HammingLoss: 0.40719, SubsetAccuracy: 0.064748, RankingLoss: 0.36357, MacroPrecision: 0.3932, MacroRecall: 0.44739, MacroFOne: 0.41808,
pruning: True, include_original_features: no_org, averageAUROC: 0.6028271, HammingLoss: 0.32446, SubsetAccuracy: 0.13669, RankingLoss: 0.36612, MacroPrecision: 0.51389, MacroRecall: 0.24075, MacroFOne: 0.32651,
pruning: False, include_original_features: no_org, averageAUROC: 0.5848288, HammingLoss: 0.38345, SubsetAccuracy: 0.043165, RankingLoss: 0.37257, MacroPrecision: 0.42383, MacroRecall: 0.45311, MacroFOne: 0.43635,

Fold 5/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [09:33<00:00,  3.75feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.6117295, HammingLoss: 0.32806, SubsetAccuracy: 0.093525, RankingLoss: 0.36149, MacroPrecision: 0.52372, MacroRecall: 0.28442, MacroFOne: 0.36305,
pruning: False, include_original_features: with_org, averageAUROC: 0.6073922, HammingLoss: 0.40144, SubsetAccuracy: 0.05036, RankingLoss: 0.36156, MacroPrecision: 0.42334, MacroRecall: 0.5257, MacroFOne: 0.46708,
pruning: True, include_original_features: no_org, averageAUROC: 0.5798754, HammingLoss: 0.34029, SubsetAccuracy: 0.093525, RankingLoss: 0.37221, MacroPrecision: 0.47908, MacroRecall: 0.23712, MacroFOne: 0.30905,
pruning: False, include_original_features: no_org, averageAUROC: 0.5926156, HammingLoss: 0.38993, SubsetAccuracy: 0.05036, RankingLoss: 0.37199, MacroPrecision: 0.42988, MacroRecall: 0.47879, MacroFOne: 0.45061,

Fold 6/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [09:34<00:00,  3.74feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5968988, HammingLoss: 0.34317, SubsetAccuracy: 0.16547, RankingLoss: 0.35525, MacroPrecision: 0.61226, MacroRecall: 0.2062, MacroFOne: 0.30494,
pruning: False, include_original_features: with_org, averageAUROC: 0.6172497, HammingLoss: 0.38489, SubsetAccuracy: 0.05036, RankingLoss: 0.31467, MacroPrecision: 0.48563, MacroRecall: 0.51716, MacroFOne: 0.49773,
pruning: True, include_original_features: no_org, averageAUROC: 0.6024777, HammingLoss: 0.33957, SubsetAccuracy: 0.16547, RankingLoss: 0.34288, MacroPrecision: 0.60438, MacroRecall: 0.26062, MacroFOne: 0.36318,
pruning: False, include_original_features: no_org, averageAUROC: 0.6013859, HammingLoss: 0.38561, SubsetAccuracy: 0.093525, RankingLoss: 0.32915, MacroPrecision: 0.48322, MacroRecall: 0.51226, MacroFOne: 0.49655,

Fold 7/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [09:36<00:00,  3.73feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5926947, HammingLoss: 0.31014, SubsetAccuracy: 0.19565, RankingLoss: 0.29279, MacroPrecision: 0.48485, MacroRecall: 0.26608, MacroFOne: 0.33991,
pruning: False, include_original_features: with_org, averageAUROC: 0.6073389, HammingLoss: 0.38986, SubsetAccuracy: 0.057971, RankingLoss: 0.29642, MacroPrecision: 0.39136, MacroRecall: 0.47603, MacroFOne: 0.42823,
pruning: True, include_original_features: no_org, averageAUROC: 0.5983954, HammingLoss: 0.30145, SubsetAccuracy: 0.2029, RankingLoss: 0.32511, MacroPrecision: 0.51389, MacroRecall: 0.25037, MacroFOne: 0.33385,
pruning: False, include_original_features: no_org, averageAUROC: 0.585861, HammingLoss: 0.41087, SubsetAccuracy: 0.050725, RankingLoss: 0.3006, MacroPrecision: 0.37168, MacroRecall: 0.48508, MacroFOne: 0.41886,

Fold 8/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [09:36<00:00,  3.73feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5733946, HammingLoss: 0.36304, SubsetAccuracy: 0.086957, RankingLoss: 0.38237, MacroPrecision: 0.47653, MacroRecall: 0.23195, MacroFOne: 0.30785,
pruning: False, include_original_features: with_org, averageAUROC: 0.5723264, HammingLoss: 0.4087, SubsetAccuracy: 0.028986, RankingLoss: 0.3691, MacroPrecision: 0.43843, MacroRecall: 0.51163, MacroFOne: 0.47118,
pruning: True, include_original_features: no_org, averageAUROC: 0.5388515, HammingLoss: 0.38116, SubsetAccuracy: 0.072464, RankingLoss: 0.39872, MacroPrecision: 0.45453, MacroRecall: 0.29121, MacroFOne: 0.35075,
pruning: False, include_original_features: no_org, averageAUROC: 0.5461676, HammingLoss: 0.44348, SubsetAccuracy: 0.0072464, RankingLoss: 0.3733, MacroPrecision: 0.39628, MacroRecall: 0.48208, MacroFOne: 0.43382,

Fold 9/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [09:35<00:00,  3.73feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.5931858, HammingLoss: 0.36232, SubsetAccuracy: 0.1087, RankingLoss: 0.33355, MacroPrecision: 0.46533, MacroRecall: 0.29075, MacroFOne: 0.35652,
pruning: False, include_original_features: with_org, averageAUROC: 0.5652097, HammingLoss: 0.42101, SubsetAccuracy: 0.021739, RankingLoss: 0.35104, MacroPrecision: 0.41275, MacroRecall: 0.4858, MacroFOne: 0.44519,
pruning: True, include_original_features: no_org, averageAUROC: 0.5503371, HammingLoss: 0.39638, SubsetAccuracy: 0.1087, RankingLoss: 0.34583, MacroPrecision: 0.36186, MacroRecall: 0.20404, MacroFOne: 0.25579,
pruning: False, include_original_features: no_org, averageAUROC: 0.5541598, HammingLoss: 0.42246, SubsetAccuracy: 0.050725, RankingLoss: 0.36813, MacroPrecision: 0.41112, MacroRecall: 0.49164, MacroFOne: 0.44658,

Fold 10/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [09:32<00:00,  3.75feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 429
pruning: True, include_original_features: with_org, averageAUROC: 0.621373, HammingLoss: 0.32029, SubsetAccuracy: 0.15217, RankingLoss: 0.32669, MacroPrecision: 0.50322, MacroRecall: 0.33249, MacroFOne: 0.39735,
pruning: False, include_original_features: with_org, averageAUROC: 0.5858583, HammingLoss: 0.41739, SubsetAccuracy: 0.050725, RankingLoss: 0.34632, MacroPrecision: 0.39522, MacroRecall: 0.5514, MacroFOne: 0.45863,
pruning: True, include_original_features: no_org, averageAUROC: 0.6281016, HammingLoss: 0.31812, SubsetAccuracy: 0.13768, RankingLoss: 0.33739, MacroPrecision: 0.5077, MacroRecall: 0.31886, MacroFOne: 0.38582,
pruning: False, include_original_features: no_org, averageAUROC: 0.5693189, HammingLoss: 0.42246, SubsetAccuracy: 0.028986, RankingLoss: 0.3561, MacroPrecision: 0.37855, MacroRecall: 0.49102, MacroFOne: 0.4264,
   pruning include_original_features                  dataset  averageAUROC  \
0    False                    no_org  CPI+fingerprint_ten_mid      0.579709
1    False                  with_org  CPI+fingerprint_ten_mid      0.586958
2     True                    no_org  CPI+fingerprint_ten_mid      0.588364
3     True                  with_org  CPI+fingerprint_ten_mid      0.590429

   HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
0     0.410430        0.046142     0.351905        0.420784     0.487624
1     0.404702        0.048316     0.346406        0.428724     0.504924
2     0.346042        0.126995     0.354453        0.504574     0.263463
3     0.347234        0.128448     0.347657        0.500823     0.272100

   MacroFOne   nodes  leaves  groups  avg_group_features  gen_XofN_time  \
0   0.449191  1029.2   515.1   430.0            4.993023     574.383363
1   0.461434  1025.2   513.1   430.0            4.993023     574.383363
2   0.340175    91.6    46.3   430.0            4.993023     574.383363
3   0.346985   109.0    55.0   430.0            4.993023     574.383363

   training_time
0       1.181200
1       3.951507
2       1.181200
3       3.951507

--- Running with label:'['se_C0009676', 'se_C0041657', 'se_C0002994', 'se_C0042571', 'se_C0004604', 'se_C0041834', 'se_C0085631', 'se_C0040822', 'se_C0042373', 'se_C0021053']' training_algorithm:'Jaccard' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_jaccard/logs/CPI_ten_mid_Jaccard_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [05:50<00:00,  4.59feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5610568, HammingLoss: 0.39459, SubsetAccuracy: 0.081081, RankingLoss: 0.39993, MacroPrecision: 0.47805, MacroRecall: 0.31152, MacroFOne: 0.37062,
pruning: False, include_original_features: with_org, averageAUROC: 0.5829073, HammingLoss: 0.3973, SubsetAccuracy: 0.063063, RankingLoss: 0.37845, MacroPrecision: 0.48979, MacroRecall: 0.52251, MacroFOne: 0.50343,
pruning: True, include_original_features: no_org, averageAUROC: 0.5726331, HammingLoss: 0.3964, SubsetAccuracy: 0.072072, RankingLoss: 0.39832, MacroPrecision: 0.4726, MacroRecall: 0.32747, MacroFOne: 0.37744,
pruning: False, include_original_features: no_org, averageAUROC: 0.5597953, HammingLoss: 0.43514, SubsetAccuracy: 0.036036, RankingLoss: 0.41529, MacroPrecision: 0.44745, MacroRecall: 0.51734, MacroFOne: 0.47779,

Fold 2/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [05:49<00:00,  4.60feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.6334904, HammingLoss: 0.35045, SubsetAccuracy: 0.10811, RankingLoss: 0.36512, MacroPrecision: 0.53271, MacroRecall: 0.31502, MacroFOne: 0.39031,
pruning: False, include_original_features: with_org, averageAUROC: 0.5826287, HammingLoss: 0.41712, SubsetAccuracy: 0.045045, RankingLoss: 0.34462, MacroPrecision: 0.45405, MacroRecall: 0.49093, MacroFOne: 0.46918,
pruning: True, include_original_features: no_org, averageAUROC: 0.6258891, HammingLoss: 0.33333, SubsetAccuracy: 0.13514, RankingLoss: 0.33843, MacroPrecision: 0.61298, MacroRecall: 0.24194, MacroFOne: 0.33273,
pruning: False, include_original_features: no_org, averageAUROC: 0.5810184, HammingLoss: 0.3982, SubsetAccuracy: 0.063063, RankingLoss: 0.34329, MacroPrecision: 0.47587, MacroRecall: 0.49426, MacroFOne: 0.48263,

Fold 3/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [05:49<00:00,  4.60feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5893598, HammingLoss: 0.36396, SubsetAccuracy: 0.099099, RankingLoss: 0.38293, MacroPrecision: 0.51922, MacroRecall: 0.40195, MacroFOne: 0.45059,
pruning: False, include_original_features: with_org, averageAUROC: 0.6042058, HammingLoss: 0.4, SubsetAccuracy: 0.027027, RankingLoss: 0.37342, MacroPrecision: 0.47416, MacroRecall: 0.53287, MacroFOne: 0.49915,
pruning: True, include_original_features: no_org, averageAUROC: 0.5918369, HammingLoss: 0.36757, SubsetAccuracy: 0.099099, RankingLoss: 0.36609, MacroPrecision: 0.52248, MacroRecall: 0.34071, MacroFOne: 0.41062,
pruning: False, include_original_features: no_org, averageAUROC: 0.5757168, HammingLoss: 0.42523, SubsetAccuracy: 0.027027, RankingLoss: 0.38679, MacroPrecision: 0.44582, MacroRecall: 0.49879, MacroFOne: 0.4698,

Fold 4/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [05:49<00:00,  4.60feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5615409, HammingLoss: 0.38919, SubsetAccuracy: 0.072072, RankingLoss: 0.36429, MacroPrecision: 0.42132, MacroRecall: 0.25446, MacroFOne: 0.30981,
pruning: False, include_original_features: with_org, averageAUROC: 0.5624621, HammingLoss: 0.42973, SubsetAccuracy: 0.054054, RankingLoss: 0.33836, MacroPrecision: 0.42316, MacroRecall: 0.4869, MacroFOne: 0.45129,
pruning: True, include_original_features: no_org, averageAUROC: 0.5674229, HammingLoss: 0.37117, SubsetAccuracy: 0.09009, RankingLoss: 0.37788, MacroPrecision: 0.45268, MacroRecall: 0.20982, MacroFOne: 0.27616,
pruning: False, include_original_features: no_org, averageAUROC: 0.5485618, HammingLoss: 0.43784, SubsetAccuracy: 0.018018, RankingLoss: 0.37458, MacroPrecision: 0.41655, MacroRecall: 0.47904, MacroFOne: 0.44409,

Fold 5/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [05:49<00:00,  4.59feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.6146181, HammingLoss: 0.31261, SubsetAccuracy: 0.099099, RankingLoss: 0.38179, MacroPrecision: 0.48595, MacroRecall: 0.31997, MacroFOne: 0.38428,
pruning: False, include_original_features: with_org, averageAUROC: 0.609697, HammingLoss: 0.39009, SubsetAccuracy: 0.072072, RankingLoss: 0.33698, MacroPrecision: 0.40676, MacroRecall: 0.544, MacroFOne: 0.46458,
pruning: True, include_original_features: no_org, averageAUROC: 0.5638729, HammingLoss: 0.3009, SubsetAccuracy: 0.12613, RankingLoss: 0.3851, MacroPrecision: 0.49097, MacroRecall: 0.18169, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.5987416, HammingLoss: 0.4018, SubsetAccuracy: 0.045045, RankingLoss: 0.35483, MacroPrecision: 0.39733, MacroRecall: 0.54532, MacroFOne: 0.45744,

Fold 6/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [05:49<00:00,  4.60feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5987959, HammingLoss: 0.36486, SubsetAccuracy: 0.09009, RankingLoss: 0.39125, MacroPrecision: 0.57448, MacroRecall: 0.27454, MacroFOne: 0.35884,
pruning: False, include_original_features: with_org, averageAUROC: 0.5397577, HammingLoss: 0.43964, SubsetAccuracy: 0.054054, RankingLoss: 0.37968, MacroPrecision: 0.45169, MacroRecall: 0.43753, MacroFOne: 0.4431,
pruning: True, include_original_features: no_org, averageAUROC: 0.553922, HammingLoss: 0.38198, SubsetAccuracy: 0.072072, RankingLoss: 0.41315, MacroPrecision: 0.56048, MacroRecall: 0.25184, MacroFOne: 0.34474,
pruning: False, include_original_features: no_org, averageAUROC: 0.5696021, HammingLoss: 0.42613, SubsetAccuracy: 0.063063, RankingLoss: 0.37587, MacroPrecision: 0.47071, MacroRecall: 0.50935, MacroFOne: 0.48885,

Fold 7/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [05:49<00:00,  4.60feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.578592, HammingLoss: 0.33514, SubsetAccuracy: 0.17117, RankingLoss: 0.32606, MacroPrecision: 0.44273, MacroRecall: 0.31826, MacroFOne: 0.36852,
pruning: False, include_original_features: with_org, averageAUROC: 0.5995865, HammingLoss: 0.4045, SubsetAccuracy: 0.045045, RankingLoss: 0.29438, MacroPrecision: 0.39222, MacroRecall: 0.54918, MacroFOne: 0.45449,
pruning: True, include_original_features: no_org, averageAUROC: 0.5581585, HammingLoss: 0.33514, SubsetAccuracy: 0.18919, RankingLoss: 0.32735, MacroPrecision: 0.3813, MacroRecall: 0.18608, MacroFOne: 0.24604,
pruning: False, include_original_features: no_org, averageAUROC: 0.5825442, HammingLoss: 0.42523, SubsetAccuracy: 0.063063, RankingLoss: 0.28635, MacroPrecision: 0.36219, MacroRecall: 0.50079, MacroFOne: 0.41761,

Fold 8/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [05:50<00:00,  4.59feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5939859, HammingLoss: 0.36636, SubsetAccuracy: 0.13636, RankingLoss: 0.33706, MacroPrecision: 0.48076, MacroRecall: 0.35634, MacroFOne: 0.40663,
pruning: False, include_original_features: with_org, averageAUROC: 0.6192735, HammingLoss: 0.40909, SubsetAccuracy: 0.072727, RankingLoss: 0.31682, MacroPrecision: 0.43759, MacroRecall: 0.51813, MacroFOne: 0.47242,
pruning: True, include_original_features: no_org, averageAUROC: 0.5918475, HammingLoss: 0.34273, SubsetAccuracy: 0.13636, RankingLoss: 0.36695, MacroPrecision: 0.54333, MacroRecall: 0.30007, MacroFOne: 0.38336,
pruning: False, include_original_features: no_org, averageAUROC: 0.594594, HammingLoss: 0.40818, SubsetAccuracy: 0.045455, RankingLoss: 0.31172, MacroPrecision: 0.44622, MacroRecall: 0.53203, MacroFOne: 0.48332,

Fold 9/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [05:49<00:00,  4.60feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.6551193, HammingLoss: 0.34636, SubsetAccuracy: 0.11818, RankingLoss: 0.37049, MacroPrecision: 0.64036, MacroRecall: 0.38747, MacroFOne: 0.4746,
pruning: False, include_original_features: with_org, averageAUROC: 0.6250485, HammingLoss: 0.38909, SubsetAccuracy: 0.054545, RankingLoss: 0.334, MacroPrecision: 0.5389, MacroRecall: 0.55929, MacroFOne: 0.54479,
pruning: True, include_original_features: no_org, averageAUROC: 0.6232486, HammingLoss: 0.34455, SubsetAccuracy: 0.11818, RankingLoss: 0.37862, MacroPrecision: 0.64172, MacroRecall: 0.38232, MacroFOne: 0.46557,
pruning: False, include_original_features: no_org, averageAUROC: 0.6133846, HammingLoss: 0.37818, SubsetAccuracy: 0.054545, RankingLoss: 0.34798, MacroPrecision: 0.55347, MacroRecall: 0.49552, MacroFOne: 0.52093,

Fold 10/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [05:49<00:00,  4.60feat/s]

XofN groups with 2 features: 1
XofN groups with 5 features: 321
pruning: True, include_original_features: with_org, averageAUROC: 0.5436732, HammingLoss: 0.35545, SubsetAccuracy: 0.10909, RankingLoss: 0.35989, MacroPrecision: 0.43474, MacroRecall: 0.25566, MacroFOne: 0.31906,
pruning: False, include_original_features: with_org, averageAUROC: 0.5677488, HammingLoss: 0.41636, SubsetAccuracy: 0.036364, RankingLoss: 0.36542, MacroPrecision: 0.39825, MacroRecall: 0.44569, MacroFOne: 0.41912,
pruning: True, include_original_features: no_org, averageAUROC: 0.5577655, HammingLoss: 0.35, SubsetAccuracy: 0.11818, RankingLoss: 0.36607, MacroPrecision: 0.47182, MacroRecall: 0.29078, MacroFOne: 0.35916,
pruning: False, include_original_features: no_org, averageAUROC: 0.5801076, HammingLoss: 0.40364, SubsetAccuracy: 0.036364, RankingLoss: 0.34689, MacroPrecision: 0.42142, MacroRecall: 0.48242, MacroFOne: 0.44754,
   pruning include_original_features      dataset  averageAUROC  HammingLoss  \
0    False                    no_org  CPI_ten_mid      0.580407     0.413957
1    False                  with_org  CPI_ten_mid      0.589332     0.409292
2     True                    no_org  CPI_ten_mid      0.580660     0.352377
3     True                  with_org  CPI_ten_mid      0.593023     0.357897

   SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  MacroFOne  nodes  \
0        0.045168     0.354359        0.443703     0.505486   0.469000  772.4
1        0.052400     0.346213        0.446657     0.508703   0.472155  793.4
2        0.115651     0.371796        0.515036     0.271272   0.319582   71.0
3        0.108435     0.367881        0.501032     0.319519   0.383326   88.0

   leaves  groups  avg_group_features  gen_XofN_time  training_time
0   386.7   322.0            4.990683     349.730067       1.086974
1   397.2   322.0            4.990683     349.730067       3.065245
2    36.0   322.0            4.990683     349.730067       1.086974
3    44.5   322.0            4.990683     349.730067       3.065245

--- Running with label:'['se_C0009676', 'se_C0041657', 'se_C0002994', 'se_C0042571', 'se_C0004604', 'se_C0041834', 'se_C0085631', 'se_C0040822', 'se_C0042373', 'se_C0021053']' training_algorithm:'Jaccard' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_jaccard/logs/fingerprint_ten_mid_Jaccard_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:15<00:00,  7.13feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.6081885, HammingLoss: 0.36515, SubsetAccuracy: 0.075758, RankingLoss: 0.33856, MacroPrecision: 0.48635, MacroRecall: 0.30363, MacroFOne: 0.3714,
pruning: False, include_original_features: with_org, averageAUROC: 0.568662, HammingLoss: 0.42197, SubsetAccuracy: 0.030303, RankingLoss: 0.34669, MacroPrecision: 0.42479, MacroRecall: 0.46575, MacroFOne: 0.44125,
pruning: True, include_original_features: no_org, averageAUROC: 0.5647586, HammingLoss: 0.36136, SubsetAccuracy: 0.098485, RankingLoss: 0.34807, MacroPrecision: 0.47845, MacroRecall: 0.20862, MacroFOne: 0.28855,
pruning: False, include_original_features: no_org, averageAUROC: 0.6294118, HammingLoss: 0.38258, SubsetAccuracy: 0.060606, RankingLoss: 0.3327, MacroPrecision: 0.47266, MacroRecall: 0.55865, MacroFOne: 0.5105,

Fold 2/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:15<00:00,  7.14feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5666822, HammingLoss: 0.37481, SubsetAccuracy: 0.061069, RankingLoss: 0.3457, MacroPrecision: 0.43779, MacroRecall: 0.2312, MacroFOne: 0.30124,
pruning: False, include_original_features: with_org, averageAUROC: 0.5710011, HammingLoss: 0.42595, SubsetAccuracy: 0.015267, RankingLoss: 0.31929, MacroPrecision: 0.42063, MacroRecall: 0.50934, MacroFOne: 0.45779,
pruning: True, include_original_features: no_org, averageAUROC: 0.5966577, HammingLoss: 0.34504, SubsetAccuracy: 0.076336, RankingLoss: 0.34095, MacroPrecision: 0.51063, MacroRecall: 0.24458, MacroFOne: 0.32847,
pruning: False, include_original_features: no_org, averageAUROC: 0.5897938, HammingLoss: 0.39084, SubsetAccuracy: 0.053435, RankingLoss: 0.34216, MacroPrecision: 0.45628, MacroRecall: 0.49296, MacroFOne: 0.47085,

Fold 3/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:15<00:00,  7.15feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5603393, HammingLoss: 0.37863, SubsetAccuracy: 0.12214, RankingLoss: 0.35825, MacroPrecision: 0.43108, MacroRecall: 0.26832, MacroFOne: 0.3292,
pruning: False, include_original_features: with_org, averageAUROC: 0.5492132, HammingLoss: 0.45267, SubsetAccuracy: 0.030534, RankingLoss: 0.37238, MacroPrecision: 0.38593, MacroRecall: 0.51387, MacroFOne: 0.43921,
pruning: True, include_original_features: no_org, averageAUROC: 0.5397297, HammingLoss: 0.3542, SubsetAccuracy: 0.14504, RankingLoss: 0.36376, MacroPrecision: 0.48499, MacroRecall: 0.20771, MacroFOne: 0.2869,
pruning: False, include_original_features: no_org, averageAUROC: 0.5922588, HammingLoss: 0.39084, SubsetAccuracy: 0.045802, RankingLoss: 0.33993, MacroPrecision: 0.44615, MacroRecall: 0.47796, MacroFOne: 0.45883,

Fold 4/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:15<00:00,  7.14feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5668634, HammingLoss: 0.33282, SubsetAccuracy: 0.1374, RankingLoss: 0.36306, MacroPrecision: 0.42071, MacroRecall: 0.2539, MacroFOne: 0.3136,
pruning: False, include_original_features: with_org, averageAUROC: 0.5902305, HammingLoss: 0.39924, SubsetAccuracy: 0.053435, RankingLoss: 0.35077, MacroPrecision: 0.38185, MacroRecall: 0.52806, MacroFOne: 0.44076,
pruning: True, include_original_features: no_org, averageAUROC: 0.5907136, HammingLoss: 0.33435, SubsetAccuracy: 0.1145, RankingLoss: 0.35277, MacroPrecision: 0.4014, MacroRecall: 0.23315, MacroFOne: 0.29362,
pruning: False, include_original_features: no_org, averageAUROC: 0.5835174, HammingLoss: 0.39771, SubsetAccuracy: 0.030534, RankingLoss: 0.34376, MacroPrecision: 0.37444, MacroRecall: 0.47948, MacroFOne: 0.41755,

Fold 5/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:15<00:00,  7.13feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.6096943, HammingLoss: 0.36718, SubsetAccuracy: 0.099237, RankingLoss: 0.31384, MacroPrecision: 0.5255, MacroRecall: 0.25415, MacroFOne: 0.33326,
pruning: False, include_original_features: with_org, averageAUROC: 0.5787116, HammingLoss: 0.42137, SubsetAccuracy: 0.076336, RankingLoss: 0.32419, MacroPrecision: 0.44584, MacroRecall: 0.47404, MacroFOne: 0.45646,
pruning: True, include_original_features: no_org, averageAUROC: 0.6112111, HammingLoss: 0.35191, SubsetAccuracy: 0.10687, RankingLoss: 0.33746, MacroPrecision: 0.55567, MacroRecall: 0.29385, MacroFOne: 0.37894,
pruning: False, include_original_features: no_org, averageAUROC: 0.6077993, HammingLoss: 0.4084, SubsetAccuracy: 0.053435, RankingLoss: 0.33562, MacroPrecision: 0.46519, MacroRecall: 0.56448, MacroFOne: 0.50945,

Fold 6/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:15<00:00,  7.12feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5340533, HammingLoss: 0.34351, SubsetAccuracy: 0.12977, RankingLoss: 0.36802, MacroPrecision: 0.39501, MacroRecall: 0.23463, MacroFOne: 0.28775,
pruning: False, include_original_features: with_org, averageAUROC: 0.5579994, HammingLoss: 0.43282, SubsetAccuracy: 0.022901, RankingLoss: 0.3582, MacroPrecision: 0.35814, MacroRecall: 0.50479, MacroFOne: 0.41771,
pruning: True, include_original_features: no_org, averageAUROC: 0.588306, HammingLoss: 0.34962, SubsetAccuracy: 0.12977, RankingLoss: 0.32691, MacroPrecision: 0.38509, MacroRecall: 0.23236, MacroFOne: 0.28757,
pruning: False, include_original_features: no_org, averageAUROC: 0.5720607, HammingLoss: 0.40534, SubsetAccuracy: 0.022901, RankingLoss: 0.32133, MacroPrecision: 0.3795, MacroRecall: 0.50802, MacroFOne: 0.43254,

Fold 7/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:15<00:00,  7.13feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5666997, HammingLoss: 0.36794, SubsetAccuracy: 0.099237, RankingLoss: 0.33496, MacroPrecision: 0.47404, MacroRecall: 0.21052, MacroFOne: 0.2838,
pruning: False, include_original_features: with_org, averageAUROC: 0.5597548, HammingLoss: 0.40992, SubsetAccuracy: 0.053435, RankingLoss: 0.36134, MacroPrecision: 0.43227, MacroRecall: 0.44535, MacroFOne: 0.43647,
pruning: True, include_original_features: no_org, averageAUROC: 0.6007672, HammingLoss: 0.32901, SubsetAccuracy: 0.12977, RankingLoss: 0.31329, MacroPrecision: 0.57877, MacroRecall: 0.27989, MacroFOne: 0.37186,
pruning: False, include_original_features: no_org, averageAUROC: 0.5717002, HammingLoss: 0.42595, SubsetAccuracy: 0.045802, RankingLoss: 0.32981, MacroPrecision: 0.42556, MacroRecall: 0.50845, MacroFOne: 0.46128,

Fold 8/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:15<00:00,  7.14feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5621502, HammingLoss: 0.38931, SubsetAccuracy: 0.10687, RankingLoss: 0.32664, MacroPrecision: 0.39202, MacroRecall: 0.33162, MacroFOne: 0.35833,
pruning: False, include_original_features: with_org, averageAUROC: 0.6085708, HammingLoss: 0.41221, SubsetAccuracy: 0.061069, RankingLoss: 0.32583, MacroPrecision: 0.40961, MacroRecall: 0.56833, MacroFOne: 0.47499,
pruning: True, include_original_features: no_org, averageAUROC: 0.6033387, HammingLoss: 0.33817, SubsetAccuracy: 0.1374, RankingLoss: 0.32621, MacroPrecision: 0.47554, MacroRecall: 0.34806, MacroFOne: 0.39784,
pruning: False, include_original_features: no_org, averageAUROC: 0.5951183, HammingLoss: 0.42824, SubsetAccuracy: 0.030534, RankingLoss: 0.32829, MacroPrecision: 0.40149, MacroRecall: 0.60026, MacroFOne: 0.48003,

Fold 9/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:15<00:00,  7.12feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5788611, HammingLoss: 0.39466, SubsetAccuracy: 0.091603, RankingLoss: 0.34241, MacroPrecision: 0.42334, MacroRecall: 0.28564, MacroFOne: 0.33701,
pruning: False, include_original_features: with_org, averageAUROC: 0.5853979, HammingLoss: 0.4374, SubsetAccuracy: 0.015267, RankingLoss: 0.33718, MacroPrecision: 0.41509, MacroRecall: 0.54588, MacroFOne: 0.46952,
pruning: True, include_original_features: no_org, averageAUROC: 0.5750837, HammingLoss: 0.38397, SubsetAccuracy: 0.091603, RankingLoss: 0.36058, MacroPrecision: 0.45182, MacroRecall: 0.31201, MacroFOne: 0.3631,
pruning: False, include_original_features: no_org, averageAUROC: 0.5807565, HammingLoss: 0.42443, SubsetAccuracy: 0.022901, RankingLoss: 0.36347, MacroPrecision: 0.42348, MacroRecall: 0.51858, MacroFOne: 0.46391,

Fold 10/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:15<00:00,  7.12feat/s]

XofN groups with 5 features: 108
pruning: True, include_original_features: with_org, averageAUROC: 0.5963773, HammingLoss: 0.36641, SubsetAccuracy: 0.10687, RankingLoss: 0.33095, MacroPrecision: 0.55909, MacroRecall: 0.29172, MacroFOne: 0.37624,
pruning: False, include_original_features: with_org, averageAUROC: 0.6019363, HammingLoss: 0.41527, SubsetAccuracy: 0.038168, RankingLoss: 0.33245, MacroPrecision: 0.47795, MacroRecall: 0.56316, MacroFOne: 0.51632,
pruning: True, include_original_features: no_org, averageAUROC: 0.5756279, HammingLoss: 0.39008, SubsetAccuracy: 0.14504, RankingLoss: 0.35575, MacroPrecision: 0.509, MacroRecall: 0.23362, MacroFOne: 0.31623,
pruning: False, include_original_features: no_org, averageAUROC: 0.609594, HammingLoss: 0.39771, SubsetAccuracy: 0.053435, RankingLoss: 0.32899, MacroPrecision: 0.49634, MacroRecall: 0.51102, MacroFOne: 0.50111,
   pruning include_original_features              dataset  averageAUROC  \
0    False                    no_org  fingerprint_ten_mid      0.593201
1    False                  with_org  fingerprint_ten_mid      0.577148
2     True                    no_org  fingerprint_ten_mid      0.584619
3     True                  with_org  fingerprint_ten_mid      0.574991

   HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
0     0.405204        0.041939     0.336606        0.434109     0.521986
1     0.422882        0.039671     0.342832        0.415210     0.511857
2     0.353771        0.117481     0.342575        0.483136     0.259385
3     0.368042        0.102995     0.342239        0.454493     0.266533

   MacroFOne  nodes  leaves  groups  avg_group_features  gen_XofN_time  \
0   0.470605  989.8   495.4   108.0                 5.0       75.72618
1   0.455048  994.2   497.6   108.0                 5.0       75.72618
2   0.331308   98.4    49.7   108.0                 5.0       75.72618
3   0.329183  109.6    55.3   108.0                 5.0       75.72618

   training_time
0       0.670816
1       1.253825
2       0.670816
3       1.253825

In [5]:
# All results
save_path = "XofN_jaccard/"
final_grouped_res = pd.DataFrame()
for df in cv_results:
    final_grouped_res = pd.concat([final_grouped_res, df])
final_grouped_res.sort_values(by='dataset', ascending=False, inplace=True)
final_grouped_res = final_grouped_res.reset_index(drop=True)
final_grouped_res.to_csv(save_path + "all_results.csv")
final_grouped_res

,pruning,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,RankingLoss,MacroPrecision,MacroRecall,MacroFOne,nodes,leaves,groups,avg_group_features,gen_XofN_time,training_time
0,False,no_org,fingerprint_ten_mid,0.593201,0.405204,0.041939,0.336606,0.434109,0.521986,0.470605,989.8,495.4,108.0,5.000000,75.726180,0.670816
1,False,with_org,fingerprint_ten_mid,0.577148,0.422882,0.039671,0.342832,0.415210,0.511857,0.455048,994.2,497.6,108.0,5.000000,75.726180,1.253825
2,True,no_org,fingerprint_ten_mid,0.584619,0.353771,0.117481,0.342575,0.483136,0.259385,0.331308,98.4,49.7,108.0,5.000000,75.726180,0.670816
3,True,with_org,fingerprint_ten_mid,0.574991,0.368042,0.102995,0.342239,0.454493,0.266533,0.329183,109.6,55.3,108.0,5.000000,75.726180,1.253825
4,False,no_org,CPI_ten_mid,0.580407,0.413957,0.045168,0.354359,0.443703,0.505486,0.469000,772.4,386.7,322.0,4.990683,349.730067,1.086974
5,False,with_org,CPI_ten_mid,0.589332,0.409292,0.052400,0.346213,0.446657,0.508703,0.472155,793.4,397.2,322.0,4.990683,349.730067,3.065245
6,True,no_org,CPI_ten_mid,0.580660,0.352377,0.115651,0.371796,0.515036,0.271272,0.319582,71.0,36.0,322.0,4.990683,349.730067,1.086974
7,True,with_org,CPI_ten_mid,0.593023,0.357897,0.108435,0.367881,0.501032,0.319519,0.383326,88.0,44.5,322.0,4.990683,349.730067,3.065245
8,False,no_org,CPI+fingerprint_ten_mid,0.579709,0.410430,0.046142,0.351905,0.420784,0.487624,0.449191,1029.2,515.1,430.0,4.993023,574.383363,1.181200
9,False,with_org,CPI+fingerprint_ten_mid,0.586958,0.404702,0.048316,0.346406,0.428724,0.504924,0.461434,1025.2,513.1,430.0,4.993023,574.383363,3.951507
10,True,no_org,CPI+fingerprint_ten_mid,0.588364,0.346042,0.126995,0.354453,0.504574,0.263463,0.340175,91.6,46.3,430.0,4.993023,574.383363,1.181200
11,True,with_org,CPI+fingerprint_ten_mid,0.590429,0.347234,0.128448,0.347657,0.500823,0.272100,0.346985,109.0,55.0,430.0,4.993023,574.383363,3.951507

In [6]:
# Table ready (with pruning, rounded, compact)
save_path = "XofN_jaccard/"
rounded_final_grouped_res = pd.read_csv(save_path + "all_results.csv", index_col=0)
res = pd.read_csv(save_path + "all_results.csv", index_col=0)
table_results = get_table_results(res, eval_criteria, get_dataset_paths())
table_results.to_csv(save_path + "table_results.csv")
table_results

,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,RankingLoss,MacroPrecision,MacroRecall,MacroFOne,Nodes; Leaves,#XofN; #Feat/XofN,# Ung. Feats,XofN time (s); PCT tr. time (s)
2,no_org,fingerprint_ten_mid,0.585,0.354,0.117,0.343,0.483,0.259,0.331,98.4; 49.7,108.0; 5.0,0.0,75.7; 0.7
3,with_org,fingerprint_ten_mid,0.575,0.368,0.103,0.342,0.454,0.267,0.329,109.6; 55.3,108.0; 5.0,0.0,75.7; 1.3
6,no_org,CPI_ten_mid,0.581,0.352,0.116,0.372,0.515,0.271,0.320,71.0; 36.0,322.0; 5.0,0.0,349.7; 1.1
7,with_org,CPI_ten_mid,0.593,0.358,0.108,0.368,0.501,0.320,0.383,88.0; 44.5,322.0; 5.0,0.0,349.7; 3.1
10,no_org,CPI+fingerprint_ten_mid,0.588,0.346,0.127,0.354,0.505,0.263,0.340,91.6; 46.3,430.0; 5.0,0.0,574.4; 1.2
11,with_org,CPI+fingerprint_ten_mid,0.590,0.347,0.128,0.348,0.501,0.272,0.347,109.0; 55.0,430.0; 5.0,0.0,574.4; 4.0