In [1]:
%load_ext autoreload
%autoreload 2
import sys, os

sys.path.insert(0, os.path.abspath("C:/Users/Voror/Projects/Personal/sep"))

from SIDER_dataset.libraries.utils import get_clus_path
from sklearn.model_selection import KFold
from SIDER_dataset.libraries.XofN_library import *
from SIDER_dataset.libraries.PCT_library import run_PCT

In [2]:
# Set ADR to predict and scoring
clus_path = get_clus_path()
paths = get_dataset_paths()
print(len(paths), "datasets")
len(paths)

TEST = False
if TEST:
    paths = [paths[0]]

18 datasets

In [3]:
paths = [path for path in paths if "ten_mid" in path["dataset_name"]]
len(paths)

3

In [4]:
k = 10
random_state = 42
performances = []
training_algorithm = "PCT"
eval_criteria = ["averageAUROC", "HammingLoss", "SubsetAccuracy", "RankingLoss", "MacroPrecision", "MacroRecall",
                 "MacroFOne"]

cv_results = []
for idx, path in enumerate(paths, start=1):
    run_config = f"\n--- Running with label:'{path["dataset_path"]}' training_algorithm:'{training_algorithm}' ---"
    print(run_config)
    # Load dataset
    current_df = pd.read_csv(path["dataset_path"])
    if TEST:
        features = get_features(current_df, path["label_set"])
        current_df = current_df[features[:10] + path["label_set"]]
    kf = KFold(n_splits=k, shuffle=True, random_state=random_state)
    for fold, (train_idx, test_idx) in enumerate(kf.split(current_df), start=1):
        print(f"\nFold {fold}/{k} ({path["dataset_name"]} {idx}/{len(paths)})")
        train_dataset = current_df.iloc[train_idx]
        test_dataset = current_df.iloc[test_idx]

        train_dataset.to_csv(f"XofN_none/tmp/train_dataset.csv", index=False)
        test_dataset.to_csv(f"XofN_none/tmp/test_dataset.csv", index=False)
        os.makedirs("XofN_none/tmp", exist_ok=True)
        os.makedirs("XofN_none/tmp", exist_ok=True)

        original_res, pruned_res, training_time = run_PCT(clus_path,
                                                          "XofN_none/tmp/train_dataset.csv",
                                                          path["label_set"],
                                                          eval_criteria,
                                                          test_dataset_path=f"XofN_none/tmp/test_dataset.csv")
        pruned_performance = get_fold_results(pruned_res, eval_criteria, True, fold, True, [[]], 0, training_time,
                                              path["dataset_name"])
        performances.append(pruned_performance)
        performance = get_fold_results(original_res, eval_criteria, False, fold, True, [[]], 0, training_time,
                                       path["dataset_name"])
        performances.append(performance)
    final_perf_df = pd.DataFrame(performances)
    averages = final_perf_df.groupby(["pruning", 'dataset'])[
        eval_criteria + ["nodes", "leaves", 'training_time']].mean().reset_index()
    print(averages)
    cv_results.append(averages)
    performances = []
# laptop - 7m
# desktop - 5m

--- Running with label:'C:\Users\Voror\Projects\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_ten_mid.csv' training_algorithm:'PCT' ---

Fold 1/10 (CPI+fingerprint_ten_mid 1/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5912864, HammingLoss: 0.37482, SubsetAccuracy: 0.10791, RankingLoss: 0.34238, MacroPrecision: 0.46868, MacroRecall: 0.32403, MacroFOne: 0.37642,
pruning: False, include_original_features: with_org, averageAUROC: 0.5956056, HammingLoss: 0.38993, SubsetAccuracy: 0.043165, RankingLoss: 0.34976, MacroPrecision: 0.4635, MacroRecall: 0.51521, MacroFOne: 0.48525,

Fold 2/10 (CPI+fingerprint_ten_mid 1/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.6710237, HammingLoss: 0.31727, SubsetAccuracy: 0.13669, RankingLoss: 0.30883, MacroPrecision: 0.54313, MacroRecall: 0.43216, MacroFOne: 0.47998,
pruning: False, include_original_features: with_org, averageAUROC: 0.6482778, HammingLoss: 0.36835, SubsetAccuracy: 0.079137, RankingLoss: 0.3463, MacroPrecision: 0.47051, MacroRecall: 0.61189, MacroFOne: 0.53032,

Fold 3/10 (CPI+fingerprint_ten_mid 1/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5834672, HammingLoss: 0.37986, SubsetAccuracy: 0.1223, RankingLoss: 0.38683, MacroPrecision: 0.52365, MacroRecall: 0.28375, MacroFOne: 0.36442,
pruning: False, include_original_features: with_org, averageAUROC: 0.5585615, HammingLoss: 0.44173, SubsetAccuracy: 0.043165, RankingLoss: 0.39525, MacroPrecision: 0.43607, MacroRecall: 0.44978, MacroFOne: 0.44105,

Fold 4/10 (CPI+fingerprint_ten_mid 1/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5804283, HammingLoss: 0.34101, SubsetAccuracy: 0.1295, RankingLoss: 0.37618, MacroPrecision: 0.45598, MacroRecall: 0.21818, MacroFOne: 0.29387,
pruning: False, include_original_features: with_org, averageAUROC: 0.581149, HammingLoss: 0.3964, SubsetAccuracy: 0.021583, RankingLoss: 0.35298, MacroPrecision: 0.41215, MacroRecall: 0.48133, MacroFOne: 0.44289,

Fold 5/10 (CPI+fingerprint_ten_mid 1/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.592959, HammingLoss: 0.31583, SubsetAccuracy: 0.10072, RankingLoss: 0.37644, MacroPrecision: 0.56767, MacroRecall: 0.27961, MacroFOne: 0.37133,
pruning: False, include_original_features: with_org, averageAUROC: 0.6419782, HammingLoss: 0.36259, SubsetAccuracy: 0.05036, RankingLoss: 0.35846, MacroPrecision: 0.47242, MacroRecall: 0.58848, MacroFOne: 0.52063,

Fold 6/10 (CPI+fingerprint_ten_mid 1/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5600974, HammingLoss: 0.37482, SubsetAccuracy: 0.14388, RankingLoss: 0.33808, MacroPrecision: 0.48855, MacroRecall: 0.21147, MacroFOne: 0.29351,
pruning: False, include_original_features: with_org, averageAUROC: 0.6000938, HammingLoss: 0.39424, SubsetAccuracy: 0.079137, RankingLoss: 0.34125, MacroPrecision: 0.47205, MacroRecall: 0.48119, MacroFOne: 0.47463,

Fold 7/10 (CPI+fingerprint_ten_mid 1/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.6210842, HammingLoss: 0.29783, SubsetAccuracy: 0.18116, RankingLoss: 0.27891, MacroPrecision: 0.54284, MacroRecall: 0.24963, MacroFOne: 0.33702,
pruning: False, include_original_features: with_org, averageAUROC: 0.5940755, HammingLoss: 0.38116, SubsetAccuracy: 0.07971, RankingLoss: 0.28187, MacroPrecision: 0.39949, MacroRecall: 0.48488, MacroFOne: 0.43655,

Fold 8/10 (CPI+fingerprint_ten_mid 1/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.6071517, HammingLoss: 0.34855, SubsetAccuracy: 0.11594, RankingLoss: 0.3672, MacroPrecision: 0.53386, MacroRecall: 0.27187, MacroFOne: 0.35754,
pruning: False, include_original_features: with_org, averageAUROC: 0.5694632, HammingLoss: 0.41739, SubsetAccuracy: 0.028986, RankingLoss: 0.37259, MacroPrecision: 0.43175, MacroRecall: 0.50235, MacroFOne: 0.46314,

Fold 9/10 (CPI+fingerprint_ten_mid 1/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5576593, HammingLoss: 0.37536, SubsetAccuracy: 0.13043, RankingLoss: 0.33339, MacroPrecision: 0.4206, MacroRecall: 0.22684, MacroFOne: 0.29366,
pruning: False, include_original_features: with_org, averageAUROC: 0.5572162, HammingLoss: 0.41449, SubsetAccuracy: 0.036232, RankingLoss: 0.34129, MacroPrecision: 0.41718, MacroRecall: 0.45779, MacroFOne: 0.43444,

Fold 10/10 (CPI+fingerprint_ten_mid 1/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.6119446, HammingLoss: 0.31884, SubsetAccuracy: 0.14493, RankingLoss: 0.3234, MacroPrecision: 0.4964, MacroRecall: 0.29921, MacroFOne: 0.36884,
pruning: False, include_original_features: with_org, averageAUROC: 0.5864803, HammingLoss: 0.39348, SubsetAccuracy: 0.036232, RankingLoss: 0.3301, MacroPrecision: 0.40968, MacroRecall: 0.49098, MacroFOne: 0.44439,
   pruning                  dataset  averageAUROC  HammingLoss  \
0    False  CPI+fingerprint_ten_mid       0.59329     0.395976
1     True  CPI+fingerprint_ten_mid       0.59771     0.344419

   SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  MacroFOne  \
0        0.049771     0.346985        0.438480     0.506388   0.467329
1        0.131346     0.343164        0.504136     0.279675   0.353659

    nodes  leaves  training_time
0  1034.2   517.6       3.097539
1   102.4    51.7       3.097539

--- Running with label:'C:\Users\Voror\Projects\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI_ten_mid.csv' training_algorithm:'PCT' ---

Fold 1/10 (CPI_ten_mid 2/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5696552, HammingLoss: 0.37658, SubsetAccuracy: 0.081081, RankingLoss: 0.42116, MacroPrecision: 0.5272, MacroRecall: 0.29188, MacroFOne: 0.36714,
pruning: False, include_original_features: with_org, averageAUROC: 0.60099, HammingLoss: 0.40721, SubsetAccuracy: 0.054054, RankingLoss: 0.35001, MacroPrecision: 0.47704, MacroRecall: 0.48988, MacroFOne: 0.48096,

Fold 2/10 (CPI_ten_mid 2/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5758822, HammingLoss: 0.36306, SubsetAccuracy: 0.099099, RankingLoss: 0.3372, MacroPrecision: 0.50939, MacroRecall: 0.24264, MacroFOne: 0.3232,
pruning: False, include_original_features: with_org, averageAUROC: 0.5617107, HammingLoss: 0.41441, SubsetAccuracy: 0.054054, RankingLoss: 0.32648, MacroPrecision: 0.45503, MacroRecall: 0.43858, MacroFOne: 0.4418,

Fold 3/10 (CPI_ten_mid 2/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.573056, HammingLoss: 0.34955, SubsetAccuracy: 0.09009, RankingLoss: 0.35278, MacroPrecision: 0.57004, MacroRecall: 0.31754, MacroFOne: 0.40578,
pruning: False, include_original_features: with_org, averageAUROC: 0.6004861, HammingLoss: 0.39369, SubsetAccuracy: 0.072072, RankingLoss: 0.36032, MacroPrecision: 0.48505, MacroRecall: 0.48582, MacroFOne: 0.48319,

Fold 4/10 (CPI_ten_mid 2/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5637315, HammingLoss: 0.35586, SubsetAccuracy: 0.10811, RankingLoss: 0.40747, MacroPrecision: 0.58524, MacroRecall: 0.1741, MacroFOne: 0.26035,
pruning: False, include_original_features: with_org, averageAUROC: 0.6046064, HammingLoss: 0.3964, SubsetAccuracy: 0.063063, RankingLoss: 0.3469, MacroPrecision: 0.46625, MacroRecall: 0.48638, MacroFOne: 0.47286,

Fold 5/10 (CPI_ten_mid 2/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.6034963, HammingLoss: 0.30811, SubsetAccuracy: 0.10811, RankingLoss: 0.35232, MacroPrecision: 0.50407, MacroRecall: 0.34014, MacroFOne: 0.40492,
pruning: False, include_original_features: with_org, averageAUROC: 0.6124668, HammingLoss: 0.41712, SubsetAccuracy: 0.027027, RankingLoss: 0.31845, MacroPrecision: 0.39107, MacroRecall: 0.60875, MacroFOne: 0.47516,

Fold 6/10 (CPI_ten_mid 2/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5517025, HammingLoss: 0.39369, SubsetAccuracy: 0.072072, RankingLoss: 0.43133, MacroPrecision: 0.53383, MacroRecall: 0.21022, MacroFOne: 0.29669,
pruning: False, include_original_features: with_org, averageAUROC: 0.5244805, HammingLoss: 0.45225, SubsetAccuracy: 0.036036, RankingLoss: 0.42935, MacroPrecision: 0.43011, MacroRecall: 0.37949, MacroFOne: 0.40123,

Fold 7/10 (CPI_ten_mid 2/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.552457, HammingLoss: 0.34324, SubsetAccuracy: 0.13514, RankingLoss: 0.29786, MacroPrecision: 0.42031, MacroRecall: 0.29902, MacroFOne: 0.34663,
pruning: False, include_original_features: with_org, averageAUROC: 0.5288332, HammingLoss: 0.43694, SubsetAccuracy: 0.072072, RankingLoss: 0.31088, MacroPrecision: 0.33271, MacroRecall: 0.40707, MacroFOne: 0.36429,

Fold 8/10 (CPI_ten_mid 2/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5837251, HammingLoss: 0.34727, SubsetAccuracy: 0.12727, RankingLoss: 0.37384, MacroPrecision: 0.54987, MacroRecall: 0.33512, MacroFOne: 0.40855,
pruning: False, include_original_features: with_org, averageAUROC: 0.6044449, HammingLoss: 0.39909, SubsetAccuracy: 0.036364, RankingLoss: 0.33009, MacroPrecision: 0.45511, MacroRecall: 0.53043, MacroFOne: 0.48889,

Fold 9/10 (CPI_ten_mid 2/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5938848, HammingLoss: 0.36545, SubsetAccuracy: 0.11818, RankingLoss: 0.37806, MacroPrecision: 0.63772, MacroRecall: 0.28194, MacroFOne: 0.38481,
pruning: False, include_original_features: with_org, averageAUROC: 0.5904459, HammingLoss: 0.38909, SubsetAccuracy: 0.063636, RankingLoss: 0.33168, MacroPrecision: 0.53714, MacroRecall: 0.50175, MacroFOne: 0.51612,

Fold 10/10 (CPI_ten_mid 2/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5446409, HammingLoss: 0.34455, SubsetAccuracy: 0.12727, RankingLoss: 0.3704, MacroPrecision: 0.4849, MacroRecall: 0.24716, MacroFOne: 0.32408,
pruning: False, include_original_features: with_org, averageAUROC: 0.5478069, HammingLoss: 0.43909, SubsetAccuracy: 0.018182, RankingLoss: 0.39171, MacroPrecision: 0.38333, MacroRecall: 0.46729, MacroFOne: 0.41975,
   pruning      dataset  averageAUROC  HammingLoss  SubsetAccuracy  \
0    False  CPI_ten_mid      0.577627     0.414529        0.049656
1     True  CPI_ten_mid      0.571223     0.354736        0.106642

   RankingLoss  MacroPrecision  MacroRecall  MacroFOne  nodes  leaves  \
0     0.349587        0.441284     0.479544   0.454425  762.6   381.8
1     0.372242        0.532257     0.273976   0.352215   68.8    34.9

   training_time
0       2.766194
1       2.766194

--- Running with label:'C:\Users\Voror\Projects\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/fingerprint_ten_mid.csv' training_algorithm:'PCT' ---

Fold 1/10 (fingerprint_ten_mid 3/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5738573, HammingLoss: 0.34621, SubsetAccuracy: 0.11364, RankingLoss: 0.37377, MacroPrecision: 0.5404, MacroRecall: 0.20703, MacroFOne: 0.29654,
pruning: False, include_original_features: with_org, averageAUROC: 0.5750368, HammingLoss: 0.41061, SubsetAccuracy: 0.05303, RankingLoss: 0.35195, MacroPrecision: 0.43755, MacroRecall: 0.47212, MacroFOne: 0.45192,

Fold 2/10 (fingerprint_ten_mid 3/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5645657, HammingLoss: 0.35496, SubsetAccuracy: 0.068702, RankingLoss: 0.33016, MacroPrecision: 0.49433, MacroRecall: 0.24194, MacroFOne: 0.31924,
pruning: False, include_original_features: with_org, averageAUROC: 0.5512673, HammingLoss: 0.43359, SubsetAccuracy: 0.0076336, RankingLoss: 0.33616, MacroPrecision: 0.40067, MacroRecall: 0.45928, MacroFOne: 0.42507,

Fold 3/10 (fingerprint_ten_mid 3/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5549149, HammingLoss: 0.3542, SubsetAccuracy: 0.12977, RankingLoss: 0.38167, MacroPrecision: 0.49139, MacroRecall: 0.24659, MacroFOne: 0.31956,
pruning: False, include_original_features: with_org, averageAUROC: 0.5500321, HammingLoss: 0.43053, SubsetAccuracy: 0.038168, RankingLoss: 0.37212, MacroPrecision: 0.39406, MacroRecall: 0.45956, MacroFOne: 0.42211,

Fold 4/10 (fingerprint_ten_mid 3/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5772449, HammingLoss: 0.33206, SubsetAccuracy: 0.1145, RankingLoss: 0.3411, MacroPrecision: 0.43185, MacroRecall: 0.32105, MacroFOne: 0.36705,
pruning: False, include_original_features: with_org, averageAUROC: 0.5906508, HammingLoss: 0.40153, SubsetAccuracy: 0.045802, RankingLoss: 0.3497, MacroPrecision: 0.37774, MacroRecall: 0.50954, MacroFOne: 0.43249,

Fold 5/10 (fingerprint_ten_mid 3/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.6177266, HammingLoss: 0.36107, SubsetAccuracy: 0.099237, RankingLoss: 0.31848, MacroPrecision: 0.53767, MacroRecall: 0.26695, MacroFOne: 0.35347,
pruning: False, include_original_features: with_org, averageAUROC: 0.5895242, HammingLoss: 0.41832, SubsetAccuracy: 0.053435, RankingLoss: 0.34392, MacroPrecision: 0.45359, MacroRecall: 0.55695, MacroFOne: 0.49817,

Fold 6/10 (fingerprint_ten_mid 3/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5749282, HammingLoss: 0.32443, SubsetAccuracy: 0.12977, RankingLoss: 0.37316, MacroPrecision: 0.45952, MacroRecall: 0.29542, MacroFOne: 0.35206,
pruning: False, include_original_features: with_org, averageAUROC: 0.5806855, HammingLoss: 0.42214, SubsetAccuracy: 0.053435, RankingLoss: 0.33411, MacroPrecision: 0.37558, MacroRecall: 0.55095, MacroFOne: 0.44484,

Fold 7/10 (fingerprint_ten_mid 3/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5720928, HammingLoss: 0.36183, SubsetAccuracy: 0.12214, RankingLoss: 0.34803, MacroPrecision: 0.50332, MacroRecall: 0.17893, MacroFOne: 0.26105,
pruning: False, include_original_features: with_org, averageAUROC: 0.5673665, HammingLoss: 0.43053, SubsetAccuracy: 0.015267, RankingLoss: 0.35786, MacroPrecision: 0.41841, MacroRecall: 0.49971, MacroFOne: 0.45406,

Fold 8/10 (fingerprint_ten_mid 3/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5873424, HammingLoss: 0.3313, SubsetAccuracy: 0.099237, RankingLoss: 0.35324, MacroPrecision: 0.51754, MacroRecall: 0.32289, MacroFOne: 0.39013,
pruning: False, include_original_features: with_org, averageAUROC: 0.5726524, HammingLoss: 0.42595, SubsetAccuracy: 0.045802, RankingLoss: 0.33605, MacroPrecision: 0.39479, MacroRecall: 0.53814, MacroFOne: 0.4545,

Fold 9/10 (fingerprint_ten_mid 3/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5858326, HammingLoss: 0.3771, SubsetAccuracy: 0.099237, RankingLoss: 0.3365, MacroPrecision: 0.43283, MacroRecall: 0.17493, MacroFOne: 0.24319,
pruning: False, include_original_features: with_org, averageAUROC: 0.5815481, HammingLoss: 0.42443, SubsetAccuracy: 0.038168, RankingLoss: 0.35554, MacroPrecision: 0.4194, MacroRecall: 0.51232, MacroFOne: 0.46022,

Fold 10/10 (fingerprint_ten_mid 3/3)
pruning: True, include_original_features: with_org, averageAUROC: 0.5929201, HammingLoss: 0.35496, SubsetAccuracy: 0.12214, RankingLoss: 0.34, MacroPrecision: 0.63488, MacroRecall: 0.22591, MacroFOne: 0.3304,
pruning: False, include_original_features: with_org, averageAUROC: 0.6037264, HammingLoss: 0.39084, SubsetAccuracy: 0.053435, RankingLoss: 0.34499, MacroPrecision: 0.50836, MacroRecall: 0.48865, MacroFOne: 0.49633,
   pruning              dataset  averageAUROC  HammingLoss  SubsetAccuracy  \
0    False  fingerprint_ten_mid      0.576249     0.418847        0.040418
1     True  fingerprint_ten_mid      0.580143     0.349812        0.109837

   RankingLoss  MacroPrecision  MacroRecall  MacroFOne  nodes  leaves  \
0     0.348240        0.418015     0.504722   0.453971  992.4   496.7
1     0.349611        0.504373     0.248164   0.323269   85.6    43.3

   training_time
0        1.10336
1        1.10336

In [5]:
# All results
save_path = "XofN_none/"
final_grouped_res = pd.DataFrame()
for df in cv_results:
    final_grouped_res = pd.concat([final_grouped_res, df])
final_grouped_res.sort_values(by='dataset', ascending=False, inplace=True)
final_grouped_res = final_grouped_res.reset_index(drop=True)
final_grouped_res.to_csv(save_path + "all_results.csv")
final_grouped_res

,pruning,dataset,averageAUROC,HammingLoss,SubsetAccuracy,RankingLoss,MacroPrecision,MacroRecall,MacroFOne,nodes,leaves,training_time
0,False,fingerprint_ten_mid,0.576249,0.418847,0.040418,0.348240,0.418015,0.504722,0.453971,992.4,496.7,1.103360
1,True,fingerprint_ten_mid,0.580143,0.349812,0.109837,0.349611,0.504373,0.248164,0.323269,85.6,43.3,1.103360
2,False,CPI_ten_mid,0.577627,0.414529,0.049656,0.349587,0.441284,0.479544,0.454425,762.6,381.8,2.766194
3,True,CPI_ten_mid,0.571223,0.354736,0.106642,0.372242,0.532257,0.273976,0.352215,68.8,34.9,2.766194
4,False,CPI+fingerprint_ten_mid,0.593290,0.395976,0.049771,0.346985,0.438480,0.506388,0.467329,1034.2,517.6,3.097539
5,True,CPI+fingerprint_ten_mid,0.597710,0.344419,0.131346,0.343164,0.504136,0.279675,0.353659,102.4,51.7,3.097539

In [6]:
# Table ready (with pruning, rounded, compact)
save_path = "XofN_none/"
rounded_final_grouped_res = pd.read_csv(save_path + "all_results.csv", index_col=0)
rounded_final_grouped_res = rounded_final_grouped_res[rounded_final_grouped_res["pruning"] == True]
for measure in eval_criteria:
    rounded_final_grouped_res[measure] = rounded_final_grouped_res[measure].round(3)

rounded_final_grouped_res["Nodes; Leaves"] = rounded_final_grouped_res["nodes"].round(1).astype(str) + "; " + \
                                             rounded_final_grouped_res["leaves"].round(1).astype(str)

rounded_final_grouped_res["PCT tr. time (s)"] = rounded_final_grouped_res["training_time"].round(
    1).astype(str)

rounded_final_grouped_res = rounded_final_grouped_res.drop(columns=["pruning", "nodes", "leaves", "training_time"])
rounded_final_grouped_res.to_csv(save_path + "table_results.csv")
rounded_final_grouped_res

,dataset,averageAUROC,HammingLoss,SubsetAccuracy,RankingLoss,MacroPrecision,MacroRecall,MacroFOne,Nodes; Leaves,PCT tr. time (s)
1,fingerprint_ten_mid,0.580,0.350,0.110,0.350,0.504,0.248,0.323,85.6; 43.3,1.1
3,CPI_ten_mid,0.571,0.355,0.107,0.372,0.532,0.274,0.352,68.8; 34.9,2.8
5,CPI+fingerprint_ten_mid,0.598,0.344,0.131,0.343,0.504,0.280,0.354,102.4; 51.7,3.1