In [1]:
import sys, os
sys.path.insert(0, os.path.abspath("C:/Users/Voror/Projects/Personal/sep"))

from sklearn.model_selection import KFold
from SIDER_dataset.libraries.XofN_library import *
from SIDER_dataset.libraries.PCT_library import run_PCT
from SIDER_dataset.libraries.utils import *
%load_ext autoreload
%autoreload 2

In [4]:
# Set ADR to predict and scoring
clus_path = get_clus_path()
paths = get_dataset_paths()
print(len(paths), "datasets")
paths

12 datasets

[{'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_cardiac.csv',
  'dataset_name': 'CPI+fingerprint_cardiac',
  'label_set': ['se_C0016382',
   'se_C0018799',
   'se_C0003811',
   'se_C0428977',
   'se_C0027051',
   'se_C0018790'],
  'features': 2147},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_high_freq.csv',
  'dataset_name': 'CPI+fingerprint_high_freq',
  'label_set': ['se_C0027497',
   'se_C0018681',
   'se_C0011603',
   'se_C0015230',
   'se_C0042963',
   'se_C0012833'],
  'features': 2147},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_low_freq.csv',
  'dataset_name': 'CPI+fingerprint_low_freq',
  'label_set': ['se_C0020580',
   'se_C0267792',
   'se_C0018524',
   'se_C0031117',
   'se_C0035078',
   'se_C0011570'],
  'features': 2147},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_mid_freq.csv',
  'dataset_name': 'CPI+fingerprint_mid_freq',
  'label_set': ['se_C0020538',
   'se_C0008031',
   'se_C0003467',
   'se_C0036572',
   'se_C0030252',
   'se_C0027769'],
  'features': 2147},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI_cardiac.csv',
  'dataset_name': 'CPI_cardiac',
  'label_set': ['se_C0016382',
   'se_C0018799',
   'se_C0003811',
   'se_C0428977',
   'se_C0027051',
   'se_C0018790'],
  'features': 1607},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI_high_freq.csv',
  'dataset_name': 'CPI_high_freq',
  'label_set': ['se_C0027497',
   'se_C0018681',
   'se_C0011603',
   'se_C0015230',
   'se_C0042963',
   'se_C0012833'],
  'features': 1607},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI_low_freq.csv',
  'dataset_name': 'CPI_low_freq',
  'label_set': ['se_C0020580',
   'se_C0267792',
   'se_C0018524',
   'se_C0031117',
   'se_C0035078',
   'se_C0011570'],
  'features': 1607},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI_mid_freq.csv',
  'dataset_name': 'CPI_mid_freq',
  'label_set': ['se_C0020538',
   'se_C0008031',
   'se_C0003467',
   'se_C0036572',
   'se_C0030252',
   'se_C0027769'],
  'features': 1607},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/fingerprint_cardiac.csv',
  'dataset_name': 'fingerprint_cardiac',
  'label_set': ['se_C0016382',
   'se_C0018799',
   'se_C0003811',
   'se_C0428977',
   'se_C0027051',
   'se_C0018790'],
  'features': 540},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/fingerprint_high_freq.csv',
  'dataset_name': 'fingerprint_high_freq',
  'label_set': ['se_C0027497',
   'se_C0018681',
   'se_C0011603',
   'se_C0015230',
   'se_C0042963',
   'se_C0012833'],
  'features': 540},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/fingerprint_low_freq.csv',
  'dataset_name': 'fingerprint_low_freq',
  'label_set': ['se_C0020580',
   'se_C0267792',
   'se_C0018524',
   'se_C0031117',
   'se_C0035078',
   'se_C0011570'],
  'features': 540},
 {'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/fingerprint_mid_freq.csv',
  'dataset_name': 'fingerprint_mid_freq',
  'label_set': ['se_C0020538',
   'se_C0008031',
   'se_C0003467',
   'se_C0036572',
   'se_C0030252',
   'se_C0027769'],
  'features': 540}]

In [5]:
k = 10
random_state = 42
performances = []
ranking_criteria = ["MDI"]
include_original_features_options = [True, False]
training_algorithm = "PCT"
eval_criteria = ["averageAUROC", "HammingLoss", "SubsetAccuracy", "RankingLoss", "MacroPrecision", "MacroRecall",
                 "MacroFOne"]
max_size = 5
cv_results = []

for idx, path in enumerate(paths, start=1):
    run_config = f"\n--- Running with label:'{path["dataset_path"]}' training_algorithm:'{training_algorithm}' eval_criterion:'baseline' max_size:'{max_size}' ---"
    print(run_config)
    # Load dataset
    current_df = pd.read_csv(path["dataset_path"])
    # features = get_features(current_df, path["label_set"])
    # current_df = current_df[features[:10] + ["dataset_path"]]
    kf = KFold(n_splits=k, shuffle=True, random_state=random_state)
    for fold, (train_idx, test_idx) in enumerate(kf.split(current_df), start=1):
        print(f"\nFold {fold}/{k} ({path["dataset_name"]} {idx}/{len(paths)})")
        train_dataset = current_df.iloc[train_idx]
        test_dataset = current_df.iloc[test_idx]

        feature_rankings = calculate_mdi_multi_rf(train_dataset, path["label_set"])

        XofN_groupings, gen_XofN_time = generate_XofN_list_baseline(feature_rankings, 5)
        for include_original_features in include_original_features_options:
            current_train_dataset = group_features(
                train_dataset,
                path["label_set"],
                XofN_groupings,
                include_original_features,
                verbose=True
            )

            current_test_dataset = group_features(
                test_dataset,
                path["label_set"],
                XofN_groupings,
                include_original_features,
                verbose=True
            )

            current_train_dataset.to_csv(f"XofN_naive/tmp/train_dataset.csv", index=False)
            current_test_dataset.to_csv(f"XofN_naive/tmp/test_dataset.csv", index=False)

            original_res, pruned_res, training_time = run_PCT(clus_path,
                                                              "XofN_naive/tmp/train_dataset.csv",
                                                              path["label_set"],
                                                              eval_criteria,
                                                              test_dataset_path=f"XofN_naive/tmp/test_dataset.csv")

            pruned_performance = get_fold_results(pruned_res, eval_criteria, True, fold, include_original_features,
                                                  XofN_groupings,
                                                  gen_XofN_time,
                                                  training_time, path["dataset_name"])
            performances.append(pruned_performance)
            performance = get_fold_results(original_res, eval_criteria, False, fold, include_original_features,
                                           XofN_groupings,
                                           gen_XofN_time,
                                           training_time, path["dataset_name"])
            performances.append(performance)
    final_perf_df = pd.DataFrame(performances)
    averages = final_perf_df.groupby(["pruning", 'include_original_features', 'dataset'])[
        eval_criteria + ['nodes', 'leaves', 'groups', 'avg_group_features', 'gen_XofN_time',
                         'training_time']].mean().reset_index()
    print(averages)
    cv_results.append(averages)
    performances = []
# laptop 13m
# desktop 9m

--- Running with label:'C:\Users\Voror\Projects\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_cardiac.csv' training_algorithm:'PCT' eval_criterion:'baseline' max_size:'5' ---

Fold 1/10 (CPI+fingerprint_cardiac 1/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.6229117, HammingLoss: 0.20144, SubsetAccuracy: 0.47482, RankingLoss: 0.19446, MacroPrecision: 0.64374, MacroRecall: 0.22424, MacroFOne: 0.33084,
pruning: False, include_original_features: with_org, averageAUROC: 0.6248091, HammingLoss: 0.28297, SubsetAccuracy: 0.28777, RankingLoss: 0.18717, MacroPrecision: 0.39528, MacroRecall: 0.41606, MacroFOne: 0.40002,
pruning: True, include_original_features: no_org, averageAUROC: 0.5931386, HammingLoss: 0.22182, SubsetAccuracy: 0.45324, RankingLoss: 0.21087, MacroPrecision: 0.54059, MacroRecall: 0.24885, MacroFOne: 0.33774,
pruning: False, include_original_features: no_org, averageAUROC: 0.5987863, HammingLoss: 0.36571, SubsetAccuracy: 0.17986, RankingLoss: 0.19267, MacroPrecision: 0.30649, MacroRecall: 0.47238, MacroFOne: 0.37045,

Fold 2/10 (CPI+fingerprint_cardiac 1/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.5251412, HammingLoss: 0.30576, SubsetAccuracy: 0.34532, RankingLoss: 0.22156, MacroPrecision: 0.34877, MacroRecall: 0.1455, MacroFOne: 0.20229,
pruning: False, include_original_features: with_org, averageAUROC: 0.5807775, HammingLoss: 0.35492, SubsetAccuracy: 0.23741, RankingLoss: 0.2219, MacroPrecision: 0.36217, MacroRecall: 0.41284, MacroFOne: 0.38431,
pruning: True, include_original_features: no_org, averageAUROC: 0.5017032, HammingLoss: 0.29017, SubsetAccuracy: 0.36691, RankingLoss: 0.22992, MacroPrecision: 0.36638, MacroRecall: 0.080437, MacroFOne: 0.13058,
pruning: False, include_original_features: no_org, averageAUROC: 0.534092, HammingLoss: 0.3741, SubsetAccuracy: 0.17986, RankingLoss: 0.24355, MacroPrecision: 0.32534, MacroRecall: 0.34824, MacroFOne: 0.33489,

Fold 3/10 (CPI+fingerprint_cardiac 1/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.5560671, HammingLoss: 0.28657, SubsetAccuracy: 0.35252, RankingLoss: 0.26293, MacroPrecision: 0.47645, MacroRecall: 0.15734, MacroFOne: 0.23444,
pruning: False, include_original_features: with_org, averageAUROC: 0.5831176, HammingLoss: 0.34173, SubsetAccuracy: 0.19424, RankingLoss: 0.23143, MacroPrecision: 0.39236, MacroRecall: 0.39176, MacroFOne: 0.38883,
pruning: True, include_original_features: no_org, averageAUROC: 0.5276521, HammingLoss: 0.28297, SubsetAccuracy: 0.35252, RankingLoss: 0.26631, MacroPrecision: 0.50801, MacroRecall: 0.14117, MacroFOne: 0.21962,
pruning: False, include_original_features: no_org, averageAUROC: 0.5848789, HammingLoss: 0.35612, SubsetAccuracy: 0.20144, RankingLoss: 0.24143, MacroPrecision: 0.38054, MacroRecall: 0.43309, MacroFOne: 0.40398,

Fold 4/10 (CPI+fingerprint_cardiac 1/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.6006043, HammingLoss: 0.29376, SubsetAccuracy: 0.36691, RankingLoss: 0.22082, MacroPrecision: 0.33487, MacroRecall: 0.15113, MacroFOne: 0.20623,
pruning: False, include_original_features: with_org, averageAUROC: 0.5470968, HammingLoss: 0.34892, SubsetAccuracy: 0.23022, RankingLoss: 0.22732, MacroPrecision: 0.32366, MacroRecall: 0.35468, MacroFOne: 0.33705,
pruning: True, include_original_features: no_org, averageAUROC: 0.5827038, HammingLoss: 0.26139, SubsetAccuracy: 0.38849, RankingLoss: 0.21685, MacroPrecision: 0.42639, MacroRecall: 0.11824, MacroFOne: 0.18414,
pruning: False, include_original_features: no_org, averageAUROC: 0.5924076, HammingLoss: 0.32734, SubsetAccuracy: 0.19424, RankingLoss: 0.21485, MacroPrecision: 0.36073, MacroRecall: 0.37254, MacroFOne: 0.36508,

Fold 5/10 (CPI+fingerprint_cardiac 1/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.6137289, HammingLoss: 0.21942, SubsetAccuracy: 0.43165, RankingLoss: 0.2026, MacroPrecision: 0.48088, MacroRecall: 0.22401, MacroFOne: 0.29857,
pruning: False, include_original_features: with_org, averageAUROC: 0.6387523, HammingLoss: 0.30576, SubsetAccuracy: 0.22302, RankingLoss: 0.19107, MacroPrecision: 0.34888, MacroRecall: 0.48566, MacroFOne: 0.40476,
pruning: True, include_original_features: no_org, averageAUROC: 0.6058409, HammingLoss: 0.23501, SubsetAccuracy: 0.40288, RankingLoss: 0.21565, MacroPrecision: 0.28501, MacroRecall: 0.094273, MacroFOne: 0.0,
pruning: False, include_original_features: no_org, averageAUROC: 0.5431168, HammingLoss: 0.31655, SubsetAccuracy: 0.2518, RankingLoss: 0.2051, MacroPrecision: 0.27709, MacroRecall: 0.30187, MacroFOne: 0.28823,

Fold 6/10 (CPI+fingerprint_cardiac 1/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.5706314, HammingLoss: 0.27818, SubsetAccuracy: 0.41727, RankingLoss: 0.18473, MacroPrecision: 0.36779, MacroRecall: 0.13736, MacroFOne: 0.19895,
pruning: False, include_original_features: with_org, averageAUROC: 0.633821, HammingLoss: 0.31535, SubsetAccuracy: 0.27338, RankingLoss: 0.18787, MacroPrecision: 0.39695, MacroRecall: 0.45962, MacroFOne: 0.42283,
pruning: True, include_original_features: no_org, averageAUROC: 0.5808509, HammingLoss: 0.25899, SubsetAccuracy: 0.44604, RankingLoss: 0.1811, MacroPrecision: 0.45884, MacroRecall: 0.11583, MacroFOne: 0.18452,
pruning: False, include_original_features: no_org, averageAUROC: 0.5576406, HammingLoss: 0.33933, SubsetAccuracy: 0.25899, RankingLoss: 0.18072, MacroPrecision: 0.33164, MacroRecall: 0.34099, MacroFOne: 0.33426,

Fold 7/10 (CPI+fingerprint_cardiac 1/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.6257617, HammingLoss: 0.2554, SubsetAccuracy: 0.38849, RankingLoss: 0.2217, MacroPrecision: 0.50247, MacroRecall: 0.25468, MacroFOne: 0.33109,
pruning: False, include_original_features: with_org, averageAUROC: 0.6250275, HammingLoss: 0.29736, SubsetAccuracy: 0.28058, RankingLoss: 0.20661, MacroPrecision: 0.42969, MacroRecall: 0.45689, MacroFOne: 0.44193,
pruning: True, include_original_features: no_org, averageAUROC: 0.5023672, HammingLoss: 0.27698, SubsetAccuracy: 0.38849, RankingLoss: 0.26922, MacroPrecision: 0.32415, MacroRecall: 0.076693, MacroFOne: 0.12205,
pruning: False, include_original_features: no_org, averageAUROC: 0.5210564, HammingLoss: 0.3729, SubsetAccuracy: 0.16547, RankingLoss: 0.24175, MacroPrecision: 0.28416, MacroRecall: 0.31091, MacroFOne: 0.29598,

Fold 8/10 (CPI+fingerprint_cardiac 1/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.5992168, HammingLoss: 0.28297, SubsetAccuracy: 0.30216, RankingLoss: 0.23014, MacroPrecision: 0.48705, MacroRecall: 0.15587, MacroFOne: 0.23336,
pruning: False, include_original_features: with_org, averageAUROC: 0.5526875, HammingLoss: 0.3753, SubsetAccuracy: 0.1223, RankingLoss: 0.23905, MacroPrecision: 0.34733, MacroRecall: 0.38907, MacroFOne: 0.36247,
pruning: True, include_original_features: no_org, averageAUROC: 0.5683399, HammingLoss: 0.28537, SubsetAccuracy: 0.30216, RankingLoss: 0.22188, MacroPrecision: 0.47004, MacroRecall: 0.088138, MacroFOne: 0.14336,
pruning: False, include_original_features: no_org, averageAUROC: 0.5081515, HammingLoss: 0.43405, SubsetAccuracy: 0.086331, RankingLoss: 0.24075, MacroPrecision: 0.2758, MacroRecall: 0.34294, MacroFOne: 0.30077,

Fold 9/10 (CPI+fingerprint_cardiac 1/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.5918362, HammingLoss: 0.27458, SubsetAccuracy: 0.28777, RankingLoss: 0.27026, MacroPrecision: 0.44919, MacroRecall: 0.23321, MacroFOne: 0.30447,
pruning: False, include_original_features: with_org, averageAUROC: 0.6136615, HammingLoss: 0.33933, SubsetAccuracy: 0.19424, RankingLoss: 0.26599, MacroPrecision: 0.38153, MacroRecall: 0.48143, MacroFOne: 0.42228,
pruning: True, include_original_features: no_org, averageAUROC: 0.5915317, HammingLoss: 0.27098, SubsetAccuracy: 0.28777, RankingLoss: 0.27298, MacroPrecision: 0.42979, MacroRecall: 0.1187, MacroFOne: 0.18438,
pruning: False, include_original_features: no_org, averageAUROC: 0.5365895, HammingLoss: 0.39808, SubsetAccuracy: 0.1295, RankingLoss: 0.28133, MacroPrecision: 0.29946, MacroRecall: 0.41254, MacroFOne: 0.3461,

Fold 10/10 (CPI+fingerprint_cardiac 1/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.6046356, HammingLoss: 0.23792, SubsetAccuracy: 0.38406, RankingLoss: 0.21137, MacroPrecision: 0.53704, MacroRecall: 0.12995, MacroFOne: 0.20896,
pruning: False, include_original_features: with_org, averageAUROC: 0.5771271, HammingLoss: 0.32367, SubsetAccuracy: 0.25362, RankingLoss: 0.23245, MacroPrecision: 0.33783, MacroRecall: 0.35142, MacroFOne: 0.34316,
pruning: True, include_original_features: no_org, averageAUROC: 0.5534118, HammingLoss: 0.24758, SubsetAccuracy: 0.36957, RankingLoss: 0.24221, MacroPrecision: 0.45812, MacroRecall: 0.12237, MacroFOne: 0.19089,
pruning: False, include_original_features: no_org, averageAUROC: 0.5763115, HammingLoss: 0.36473, SubsetAccuracy: 0.13768, RankingLoss: 0.2223, MacroPrecision: 0.31481, MacroRecall: 0.43403, MacroFOne: 0.364,
   pruning include_original_features                  dataset  averageAUROC  \
0    False                    no_org  CPI+fingerprint_cardiac      0.555303
1    False                  with_org  CPI+fingerprint_cardiac      0.597688
2     True                    no_org  CPI+fingerprint_cardiac      0.560754
3     True                  with_org  CPI+fingerprint_cardiac      0.591053

   HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
0     0.364891        0.178517     0.226445        0.315606     0.376953
1     0.328531        0.229678     0.219086        0.371568     0.419943
2     0.263126        0.375807     0.232699        0.426732     0.120470
3     0.263600        0.375097     0.222057        0.462825     0.181329

   MacroFOne  nodes  leaves  groups  avg_group_features  gen_XofN_time  \
0   0.340374  850.4   425.7   430.0            4.993023       0.000089
1   0.390764  818.4   409.7   430.0            4.993023       0.000089
2   0.169728   64.8    32.9   430.0            4.993023       0.000089
3   0.254920   83.2    42.1   430.0            4.993023       0.000089

   training_time
0       1.207497
1       4.036337
2       1.207497
3       4.036337

--- Running with label:'C:\Users\Voror\Projects\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_high_freq.csv' training_algorithm:'PCT' eval_criterion:'baseline' max_size:'5' ---

Fold 1/10 (CPI+fingerprint_high_freq 2/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.5423953, HammingLoss: 0.24341, SubsetAccuracy: 0.53957, RankingLoss: 0.13729, MacroPrecision: 0.76734, MacroRecall: 0.9729, MacroFOne: 0.85727,
pruning: False, include_original_features: with_org, averageAUROC: 0.6278456, HammingLoss: 0.26019, SubsetAccuracy: 0.45324, RankingLoss: 0.13433, MacroPrecision: 0.79393, MacroRecall: 0.88109, MacroFOne: 0.83512,
pruning: True, include_original_features: no_org, averageAUROC: 0.5689865, HammingLoss: 0.24341, SubsetAccuracy: 0.53237, RankingLoss: 0.16589, MacroPrecision: 0.76974, MacroRecall: 0.96654, MacroFOne: 0.85644,
pruning: False, include_original_features: no_org, averageAUROC: 0.5576212, HammingLoss: 0.31894, SubsetAccuracy: 0.3741, RankingLoss: 0.15026, MacroPrecision: 0.76751, MacroRecall: 0.82592, MacroFOne: 0.79548,

Fold 2/10 (CPI+fingerprint_high_freq 2/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.6332896, HammingLoss: 0.21703, SubsetAccuracy: 0.4964, RankingLoss: 0.16837, MacroPrecision: 0.80904, MacroRecall: 0.94472, MacroFOne: 0.87105,
pruning: False, include_original_features: with_org, averageAUROC: 0.5819304, HammingLoss: 0.253, SubsetAccuracy: 0.40288, RankingLoss: 0.16329, MacroPrecision: 0.81525, MacroRecall: 0.86896, MacroFOne: 0.84109,
pruning: True, include_original_features: no_org, averageAUROC: 0.5294795, HammingLoss: 0.21703, SubsetAccuracy: 0.4964, RankingLoss: 0.16727, MacroPrecision: 0.79131, MacroRecall: 0.97997, MacroFOne: 0.87504,
pruning: False, include_original_features: no_org, averageAUROC: 0.6282835, HammingLoss: 0.2482, SubsetAccuracy: 0.38129, RankingLoss: 0.14764, MacroPrecision: 0.82015, MacroRecall: 0.86924, MacroFOne: 0.84382,

Fold 3/10 (CPI+fingerprint_high_freq 2/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.5869177, HammingLoss: 0.17986, SubsetAccuracy: 0.56835, RankingLoss: 0.1475, MacroPrecision: 0.84723, MacroRecall: 0.95878, MacroFOne: 0.89883,
pruning: False, include_original_features: with_org, averageAUROC: 0.5627224, HammingLoss: 0.2446, SubsetAccuracy: 0.3741, RankingLoss: 0.13537, MacroPrecision: 0.85967, MacroRecall: 0.84485, MacroFOne: 0.85102,
pruning: True, include_original_features: no_org, averageAUROC: 0.5886106, HammingLoss: 0.15348, SubsetAccuracy: 0.61871, RankingLoss: 0.14976, MacroPrecision: 0.8574, MacroRecall: 0.98017, MacroFOne: 0.91409,
pruning: False, include_original_features: no_org, averageAUROC: 0.5618839, HammingLoss: 0.21942, SubsetAccuracy: 0.44604, RankingLoss: 0.14215, MacroPrecision: 0.86609, MacroRecall: 0.8704, MacroFOne: 0.86788,

Fold 4/10 (CPI+fingerprint_high_freq 2/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.5749187, HammingLoss: 0.26379, SubsetAccuracy: 0.45324, RankingLoss: 0.16229, MacroPrecision: 0.78193, MacroRecall: 0.90691, MacroFOne: 0.83935,
pruning: False, include_original_features: with_org, averageAUROC: 0.5665386, HammingLoss: 0.32134, SubsetAccuracy: 0.32374, RankingLoss: 0.148, MacroPrecision: 0.7831, MacroRecall: 0.80024, MacroFOne: 0.79071,
pruning: True, include_original_features: no_org, averageAUROC: 0.5874383, HammingLoss: 0.26978, SubsetAccuracy: 0.44604, RankingLoss: 0.17068, MacroPrecision: 0.78398, MacroRecall: 0.8931, MacroFOne: 0.83428,
pruning: False, include_original_features: no_org, averageAUROC: 0.5832353, HammingLoss: 0.28777, SubsetAccuracy: 0.34532, RankingLoss: 0.17656, MacroPrecision: 0.78509, MacroRecall: 0.85657, MacroFOne: 0.81883,

Fold 5/10 (CPI+fingerprint_high_freq 2/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.5827568, HammingLoss: 0.27578, SubsetAccuracy: 0.43165, RankingLoss: 0.1504, MacroPrecision: 0.76047, MacroRecall: 0.90971, MacroFOne: 0.82786,
pruning: False, include_original_features: with_org, averageAUROC: 0.598533, HammingLoss: 0.29616, SubsetAccuracy: 0.34532, RankingLoss: 0.14219, MacroPrecision: 0.77023, MacroRecall: 0.84643, MacroFOne: 0.80572,
pruning: True, include_original_features: no_org, averageAUROC: 0.5874073, HammingLoss: 0.25659, SubsetAccuracy: 0.46043, RankingLoss: 0.15801, MacroPrecision: 0.75626, MacroRecall: 0.95692, MacroFOne: 0.84448,
pruning: False, include_original_features: no_org, averageAUROC: 0.5988784, HammingLoss: 0.29616, SubsetAccuracy: 0.30216, RankingLoss: 0.17156, MacroPrecision: 0.76176, MacroRecall: 0.86285, MacroFOne: 0.8088,

Fold 6/10 (CPI+fingerprint_high_freq 2/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.5662885, HammingLoss: 0.21823, SubsetAccuracy: 0.54676, RankingLoss: 0.11673, MacroPrecision: 0.80829, MacroRecall: 0.94786, MacroFOne: 0.87209,
pruning: False, include_original_features: with_org, averageAUROC: 0.62865, HammingLoss: 0.26379, SubsetAccuracy: 0.38129, RankingLoss: 0.13439, MacroPrecision: 0.83237, MacroRecall: 0.83272, MacroFOne: 0.83196,
pruning: True, include_original_features: no_org, averageAUROC: 0.6705313, HammingLoss: 0.19784, SubsetAccuracy: 0.57554, RankingLoss: 0.12066, MacroPrecision: 0.82556, MacroRecall: 0.94992, MacroFOne: 0.88299,
pruning: False, include_original_features: no_org, averageAUROC: 0.6635836, HammingLoss: 0.23141, SubsetAccuracy: 0.43165, RankingLoss: 0.12424, MacroPrecision: 0.83676, MacroRecall: 0.87639, MacroFOne: 0.85599,

Fold 7/10 (CPI+fingerprint_high_freq 2/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.5309572, HammingLoss: 0.26019, SubsetAccuracy: 0.48921, RankingLoss: 0.1711, MacroPrecision: 0.77285, MacroRecall: 0.93031, MacroFOne: 0.84395,
pruning: False, include_original_features: with_org, averageAUROC: 0.6042214, HammingLoss: 0.29257, SubsetAccuracy: 0.34532, RankingLoss: 0.16075, MacroPrecision: 0.78377, MacroRecall: 0.84551, MacroFOne: 0.81316,
pruning: True, include_original_features: no_org, averageAUROC: 0.586552, HammingLoss: 0.23501, SubsetAccuracy: 0.5036, RankingLoss: 0.16011, MacroPrecision: 0.7885, MacroRecall: 0.94289, MacroFOne: 0.85853,
pruning: False, include_original_features: no_org, averageAUROC: 0.5827131, HammingLoss: 0.27698, SubsetAccuracy: 0.36691, RankingLoss: 0.13705, MacroPrecision: 0.79232, MacroRecall: 0.85874, MacroFOne: 0.82408,

Fold 8/10 (CPI+fingerprint_high_freq 2/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.6079923, HammingLoss: 0.21377, SubsetAccuracy: 0.47826, RankingLoss: 0.16443, MacroPrecision: 0.80777, MacroRecall: 0.95322, MacroFOne: 0.87401,
pruning: False, include_original_features: with_org, averageAUROC: 0.5697372, HammingLoss: 0.25242, SubsetAccuracy: 0.41304, RankingLoss: 0.17164, MacroPrecision: 0.81473, MacroRecall: 0.87571, MacroFOne: 0.8437,
pruning: True, include_original_features: no_org, averageAUROC: 0.6353297, HammingLoss: 0.21981, SubsetAccuracy: 0.47826, RankingLoss: 0.16176, MacroPrecision: 0.80245, MacroRecall: 0.95328, MacroFOne: 0.87097,
pruning: False, include_original_features: no_org, averageAUROC: 0.534607, HammingLoss: 0.27536, SubsetAccuracy: 0.38406, RankingLoss: 0.19634, MacroPrecision: 0.79624, MacroRecall: 0.86978, MacroFOne: 0.83104,

Fold 9/10 (CPI+fingerprint_high_freq 2/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.558244, HammingLoss: 0.22826, SubsetAccuracy: 0.48551, RankingLoss: 0.15666, MacroPrecision: 0.79176, MacroRecall: 0.96171, MacroFOne: 0.86748,
pruning: False, include_original_features: with_org, averageAUROC: 0.6538836, HammingLoss: 0.25, SubsetAccuracy: 0.32609, RankingLoss: 0.15407, MacroPrecision: 0.82753, MacroRecall: 0.8546, MacroFOne: 0.84075,
pruning: True, include_original_features: no_org, averageAUROC: 0.5049336, HammingLoss: 0.23188, SubsetAccuracy: 0.48551, RankingLoss: 0.1713, MacroPrecision: 0.79339, MacroRecall: 0.95055, MacroFOne: 0.8642,
pruning: False, include_original_features: no_org, averageAUROC: 0.5643358, HammingLoss: 0.26208, SubsetAccuracy: 0.42029, RankingLoss: 0.14044, MacroPrecision: 0.80069, MacroRecall: 0.88375, MacroFOne: 0.83952,

Fold 10/10 (CPI+fingerprint_high_freq 2/12)
pruning: True, include_original_features: with_org, averageAUROC: 0.6067192, HammingLoss: 0.25121, SubsetAccuracy: 0.42029, RankingLoss: 0.17162, MacroPrecision: 0.76309, MacroRecall: 0.96793, MacroFOne: 0.8525,
pruning: False, include_original_features: with_org, averageAUROC: 0.5674863, HammingLoss: 0.28986, SubsetAccuracy: 0.32609, RankingLoss: 0.19805, MacroPrecision: 0.77332, MacroRecall: 0.8694, MacroFOne: 0.81794,
pruning: True, include_original_features: no_org, averageAUROC: 0.5814221, HammingLoss: 0.25604, SubsetAccuracy: 0.42754, RankingLoss: 0.18021, MacroPrecision: 0.75921, MacroRecall: 0.96818, MacroFOne: 0.8502,
pruning: False, include_original_features: no_org, averageAUROC: 0.5738274, HammingLoss: 0.28382, SubsetAccuracy: 0.37681, RankingLoss: 0.18144, MacroPrecision: 0.78108, MacroRecall: 0.8646, MacroFOne: 0.82009,
   pruning include_original_features                    dataset  averageAUROC  \
0    False                    no_org  CPI+fingerprint_high_freq      0.584897
1    False                  with_org  CPI+fingerprint_high_freq      0.596155
2     True                    no_org  CPI+fingerprint_high_freq      0.584069
3     True                  with_org  CPI+fingerprint_high_freq      0.579048

   HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
0     0.270014        0.382863     0.156768        0.800769     0.863824

In [6]:
# All results
save_path = "XofN_naive/"
final_grouped_res = pd.DataFrame()
for df in cv_results:
    final_grouped_res = pd.concat([final_grouped_res, df])
final_grouped_res.sort_values(by='dataset', ascending=False, inplace=True)
final_grouped_res = final_grouped_res.reset_index(drop=True)
final_grouped_res.to_csv(save_path + "all_results.csv")
final_grouped_res

,pruning,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,RankingLoss,MacroPrecision,MacroRecall,MacroFOne,nodes,leaves,groups,avg_group_features,gen_XofN_time,training_time
0,True,with_org,fingerprint_mid_freq,0.565329,0.390004,0.233632,0.274590,0.462715,0.348512,0.394423,175.4,88.2,108.0,5.000000,0.000026,1.307341
1,True,no_org,fingerprint_mid_freq,0.574810,0.389586,0.213198,0.275866,0.462816,0.347901,0.393424,169.0,85.0,108.0,5.000000,0.000026,0.686397
2,False,with_org,fingerprint_mid_freq,0.567078,0.427932,0.125169,0.264522,0.431031,0.502130,0.462080,870.4,435.7,108.0,5.000000,0.000026,1.307341
3,False,no_org,fingerprint_mid_freq,0.569979,0.425347,0.124434,0.260294,0.435645,0.507133,0.466996,882.0,441.5,108.0,5.000000,0.000026,0.686397
4,True,with_org,fingerprint_low_freq,0.510883,0.253590,0.361443,0.296178,0.113877,0.033433,0.043021,15.4,8.2,108.0,5.000000,0.000023,1.302823
5,True,no_org,fingerprint_low_freq,0.502013,0.243724,0.374333,0.301604,0.036667,0.007256,0.000000,4.8,2.9,108.0,5.000000,0.000023,0.686866
6,False,with_org,fingerprint_low_freq,0.595268,0.345858,0.182223,0.248633,0.336207,0.429188,0.372996,828.6,414.8,108.0,5.000000,0.000023,1.302823
7,False,no_org,fingerprint_low_freq,0.581223,0.347992,0.189115,0.260934,0.331956,0.415886,0.364483,848.6,424.8,108.0,5.000000,0.000023,0.686866
8,True,no_org,fingerprint_high_freq,0.553838,0.227580,0.512925,0.165469,0.791260,0.962870,0.867806,36.8,18.9,108.0,5.000000,0.000023,0.656762
9,False,no_org,fingerprint_high_freq,0.581023,0.290390,0.340429,0.162869,0.802653,0.831117,0.815813,607.0,304.0,108.0,5.000000,0.000023,0.656762
10,False,with_org,fingerprint_high_freq,0.563362,0.280424,0.358634,0.164823,0.800288,0.850798,0.824166,597.8,299.4,108.0,5.000000,0.000023,1.299051
11,True,with_org,fingerprint_high_freq,0.554044,0.229616,0.506864,0.166674,0.792680,0.955496,0.865899,51.8,26.4,108.0,5.000000,0.000023,1.299051
12,True,with_org,fingerprint_cardiac,0.556750,0.260859,0.370454,0.227279,0.373531,0.096830,0.114907,37.0,19.0,108.0,5.000000,0.000024,1.333663
13,True,no_org,fingerprint_cardiac,0.517048,0.259722,0.376515,0.229942,0.118194,0.028188,0.020222,11.8,6.4,108.0,5.000000,0.000024,0.675898
14,False,with_org,fingerprint_cardiac,0.571055,0.364395,0.175000,0.210017,0.325545,0.412621,0.359942,826.6,413.8,108.0,5.000000,0.000024,1.333663
15,False,no_org,fingerprint_cardiac,0.566241,0.360354,0.171970,0.224479,0.325588,0.404016,0.357617,842.2,421.6,108.0,5.000000,0.000024,0.675898
16,True,with_org,CPI_mid_freq,0.605574,0.368027,0.242352,0.273713,0.537066,0.373624,0.434681,128.4,64.7,322.0,4.990683,0.000065,2.557444
17,True,no_org,CPI_mid_freq,0.596483,0.374915,0.242376,0.276103,0.526656,0.375754,0.432313,114.2,57.6,322.0,4.990683,0.000065,0.857617
18,False,with_org,CPI_mid_freq,0.584590,0.412895,0.138259,0.260934,0.471616,0.517151,0.490739,729.2,365.1,322.0,4.990683,0.000065,2.557444
19,False,no_org,CPI_mid_freq,0.577281,0.416070,0.131967,0.283482,0.470692,0.535820,0.497601,711.0,356.0,322.0,4.990683,0.000065,0.857617
20,False,with_org,CPI_low_freq,0.605706,0.333950,0.189616,0.269558,0.379695,0.424926,0.396938,719.0,360.0,322.0,4.990683,0.000072,2.686300
21,True,with_org,CPI_low_freq,0.619399,0.254931,0.333622,0.275961,0.529041,0.191569,0.262445,48.8,24.9,322.0,4.990683,0.000072,2.686300
22,True,no_org,CPI_low_freq,0.594193,0.266679,0.327389,0.287128,0.472129,0.144863,0.180905,42.8,21.9,322.0,4.990683,0.000072,0.855554
23,False,no_org,CPI_low_freq,0.586059,0.345575,0.169080,0.284885,0.359673,0.407523,0.377725,715.2,358.1,322.0,4.990683,0.000072,0.855554
24,True,no_org,CPI_high_freq,0.516074,0.211940,0.546180,0.163004,0.793589,0.989558,0.879715,9.4,5.2,322.0,4.990683,0.000066,0.805346
25,False,with_org,CPI_high_freq,0.561481,0.271695,0.394305,0.161625,0.797793,0.875901,0.834227,468.6,234.8,322.0,4.990683,0.000066,2.634138
26,False,no_org,CPI_high_freq,0.565666,0.265549,0.394354,0.170889,0.800291,0.882578,0.838438,446.8,223.9,322.0,4.990683,0.000066,0.805346
27,True,with_org,CPI_high_freq,0.559204,0.215085,0.538104,0.164482,0.794691,0.981123,0.877167,21.8,11.4,322.0,4.990683,0.000066,2.634138
28,True,with_org,CPI_cardiac,0.576063,0.283631,0.338393,0.236336,0.427496,0.179635,0.228250,69.8,35.4,322.0,4.990683,0.000068,2.578386
29,True,no_org,CPI_cardiac,0.559586,0.282440,0.343750,0.236121,0.375238,0.143036,0.158862,46.4,23.7,322.0,4.990683,0.000068,0.840652
30,False,with_org,CPI_cardiac,0.583324,0.349257,0.185713,0.238787,0.364002,0.425791,0.388649,700.6,350.8,322.0,4.990683,0.000068,2.578386
31,False,no_org,CPI_cardiac,0.549509,0.368154,0.189286,0.247146,0.332041,0.384117,0.351383,695.6,348.3,322.0,4.990683,0.000068,0.840652
32,False,no_org,CPI+fingerprint_mid_freq,0.583361,0.413112,0.136799,0.273369,0.444420,0.514493,0.474649,896.4,448.7,430.0,4.993023,0.000086,1.151600
33,False,with_org,CPI+fingerprint_mid_freq,0.595536,0.398040,0.151136,0.258590,0.462059,0.524823,0.489152,880.6,440.8,430.0,4.993023,0.000086,3.590083
34,True,no_org,CPI+fingerprint_mid_freq,0.596646,0.361886,0.245510,0.270758,0.512886,0.353200,0.415430,155.4,78.2,430.0,4.993023,0.000086,1.151600
35,True,with_org,CPI+fingerprint_mid_freq,0.600565,0.359512,0.255552,0.263458,0.519851,0.351998,0.416724,163.8,82.4,430.0,4.993023,0.000086,3.590083
36,True,with_org,CPI+fingerprint_low_freq,0.595369,0.247235,0.350861,0.275420,0.472340,0.184152,0.255347,72.0,36.5,430.0,4.993023,0.000085,3.923984
37,True,no_org,CPI+fingerprint_low_freq,0.541604,0.247118,0.363104,0.296488,0.457977,0.099595,0.119544,40.0,20.5,430.0,4.993023,0.000085,1.206685
38,False,with_org,CPI+fingerprint_low_freq,0.589425,0.321712,0.192340,0.260186,0.348040,0.383294,0.359582,843.8,422.4,430.0,4.993023,0.000085,3.923984
39,False,no_org,CPI+fingerprint_low_freq,0.574064,0.338855,0.190183,0.261062,0.323553,0.378094,0.344422,870.6,435.8,430.0,4.993023,0.000085,1.206685
40,True,with_org,CPI+fingerprint_high_freq,0.579048,0.235153,0.490924,0.154639,0.790977,0.945405,0.860439,70.8,35.9,430.0,4.993023,0.000087,3.601170
41,True,no_org,CPI+fingerprint_high_freq,0.584069,0.228087,0.502440,0.160565,0.792780,0.954152,0.865122,56.2,28.6,430.0,4.993023,0.000087,1.156208
42,False,with_org,CPI+fingerprint_high_freq,0.596155,0.272393,0.369111,0.154208,0.805390,0.851951,0.827117,608.8,304.9,430.0,4.993023,0.000087,3.601170
43,False,no_org,CPI+fingerprint_high_freq,0.584897,0.270014,0.382863,0.156768,0.800769,0.863824,0.830553,627.8,314.4,430.0,4.993023,0.000087,1.156208
44,True,no_org,CPI+fingerprint_cardiac,0.560754,0.263126,0.375807,0.232699,0.426732,0.120470,0.169728,64.8,32.9,430.0,4.993023,0.000089,1.207497
45,False,with_org,CPI+fingerprint_cardiac,0.597688,0.328531,0.229678,0.219086,0.371568,0.419943,0.390764,818.4,409.7,430.0,4.993023,0.000089,4.036337
46,True,with_org,CPI+fingerprint_cardiac,0.591053,0.263600,0.375097,0.222057,0.462825,0.181329,0.254920,83.2,42.1,430.0,4.993023,0.000089,4.036337
47,False,no_org,CPI+fingerprint_cardiac,0.555303,0.364891,0.178517,0.226445,0.315606,0.376953,0.340374,850.4,425.7,430.0,4.993023,0.000089,1.207497

In [7]:
# Table ready (with pruning, rounded, compact)
save_path = "XofN_naive/"
rounded_final_grouped_res = pd.read_csv(save_path + "all_results.csv", index_col=0)
res = pd.read_csv(save_path + "all_results.csv", index_col=0)
table_results = get_table_results(res, eval_criteria, get_dataset_paths())
table_results.to_csv(save_path + "table_results.csv")
table_results

,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,RankingLoss,MacroPrecision,MacroRecall,MacroFOne,Nodes; Leaves,#XofN; #Feat/XofN,# Ung. Feats,XofN time (s); PCT tr. time (s)
1,no_org,fingerprint_mid_freq,0.575,0.390,0.213,0.276,0.463,0.348,0.393,169.0; 85.0,108.0; 5.0,0.0,0.0; 0.7
0,with_org,fingerprint_mid_freq,0.565,0.390,0.234,0.275,0.463,0.349,0.394,175.4; 88.2,108.0; 5.0,0.0,0.0; 1.3
5,no_org,fingerprint_low_freq,0.502,0.244,0.374,0.302,0.037,0.007,0.000,4.8; 2.9,108.0; 5.0,0.0,0.0; 0.7
4,with_org,fingerprint_low_freq,0.511,0.254,0.361,0.296,0.114,0.033,0.043,15.4; 8.2,108.0; 5.0,0.0,0.0; 1.3
8,no_org,fingerprint_high_freq,0.554,0.228,0.513,0.165,0.791,0.963,0.868,36.8; 18.9,108.0; 5.0,0.0,0.0; 0.7
11,with_org,fingerprint_high_freq,0.554,0.230,0.507,0.167,0.793,0.955,0.866,51.8; 26.4,108.0; 5.0,0.0,0.0; 1.3
13,no_org,fingerprint_cardiac,0.517,0.260,0.377,0.230,0.118,0.028,0.020,11.8; 6.4,108.0; 5.0,0.0,0.0; 0.7
12,with_org,fingerprint_cardiac,0.557,0.261,0.370,0.227,0.374,0.097,0.115,37.0; 19.0,108.0; 5.0,0.0,0.0; 1.3
17,no_org,CPI_mid_freq,0.596,0.375,0.242,0.276,0.527,0.376,0.432,114.2; 57.6,322.0; 5.0,0.0,0.0; 0.9
16,with_org,CPI_mid_freq,0.606,0.368,0.242,0.274,0.537,0.374,0.435,128.4; 64.7,322.0; 5.0,0.0,0.0; 2.6
22,no_org,CPI_low_freq,0.594,0.267,0.327,0.287,0.472,0.145,0.181,42.8; 21.9,322.0; 5.0,0.0,0.0; 0.9
21,with_org,CPI_low_freq,0.619,0.255,0.334,0.276,0.529,0.192,0.262,48.8; 24.9,322.0; 5.0,0.0,0.0; 2.7
24,no_org,CPI_high_freq,0.516,0.212,0.546,0.163,0.794,0.990,0.880,9.4; 5.2,322.0; 5.0,0.0,0.0; 0.8
27,with_org,CPI_high_freq,0.559,0.215,0.538,0.164,0.795,0.981,0.877,21.8; 11.4,322.0; 5.0,0.0,0.0; 2.6
29,no_org,CPI_cardiac,0.560,0.282,0.344,0.236,0.375,0.143,0.159,46.4; 23.7,322.0; 5.0,0.0,0.0; 0.8
28,with_org,CPI_cardiac,0.576,0.284,0.338,0.236,0.427,0.180,0.228,69.8; 35.4,322.0; 5.0,0.0,0.0; 2.6
34,no_org,CPI+fingerprint_mid_freq,0.597,0.362,0.246,0.271,0.513,0.353,0.415,155.4; 78.2,430.0; 5.0,0.0,0.0; 1.2
35,with_org,CPI+fingerprint_mid_freq,0.601,0.360,0.256,0.263,0.520,0.352,0.417,163.8; 82.4,430.0; 5.0,0.0,0.0; 3.6
37,no_org,CPI+fingerprint_low_freq,0.542,0.247,0.363,0.296,0.458,0.100,0.120,40.0; 20.5,430.0; 5.0,0.0,0.0; 1.2
36,with_org,CPI+fingerprint_low_freq,0.595,0.247,0.351,0.275,0.472,0.184,0.255,72.0; 36.5,430.0; 5.0,0.0,0.0; 3.9
41,no_org,CPI+fingerprint_high_freq,0.584,0.228,0.502,0.161,0.793,0.954,0.865,56.2; 28.6,430.0; 5.0,0.0,0.0; 1.2
40,with_org,CPI+fingerprint_high_freq,0.579,0.235,0.491,0.155,0.791,0.945,0.860,70.8; 35.9,430.0; 5.0,0.0,0.0; 3.6
44,no_org,CPI+fingerprint_cardiac,0.561,0.263,0.376,0.233,0.427,0.120,0.170,64.8; 32.9,430.0; 5.0,0.0,0.0; 1.2
46,with_org,CPI+fingerprint_cardiac,0.591,0.264,0.375,0.222,0.463,0.181,0.255,83.2; 42.1,430.0; 5.0,0.0,0.0; 4.0