In [1]:
import sys, os
sys.path.insert(0, os.path.abspath("C:/Users/Voror/Projects/Personal/sep"))

from sklearn.model_selection import KFold
from SIDER_dataset.libraries.XofN_library import *
from SIDER_dataset.libraries.PCT_library import run_PCT
from SIDER_dataset.libraries.feature_evaluation_methods import feature_variance_reduction_scores
from SIDER_dataset.libraries.utils import get_clus_path
%load_ext autoreload
%autoreload 2

In [2]:
# Set ADR to predict and scoring
clus_path = get_clus_path()
paths = get_dataset_paths()
print(len(paths), "datasets")
paths

18 datasets

[{'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_cardiac.csv',
  'dataset_name': 'CPI+fingerprint_cardiac',
  'label_set': ['se_C0016382',
   'se_C0018799',
   'se_C0003811',
   'se_C0428977',
   'se_C0027051',
   'se_C0018790'],
  'features': 2147,
  'original_features': ['cpi_9606.ENSP00000000442',
   'cpi_9606.ENSP00000001008',
   'cpi_9606.ENSP00000003084',
   'cpi_9606.ENSP00000003100',
   'cpi_9606.ENSP00000005178',
   'cpi_9606.ENSP00000011292',
   'cpi_9606.ENSP00000011653',
   'cpi_9606.ENSP00000012443',
   'cpi_9606.ENSP00000013034',
   'cpi_9606.ENSP00000014930',
   'cpi_9606.ENSP00000019103',
   'cpi_9606.ENSP00000023897',
   'cpi_9606.ENSP00000039007',
   'cpi_9606.ENSP00000044462',
   'cpi_9606.ENSP00000054668',
   'cpi_9606.ENSP00000078429',
   'cpi_9606.ENSP00000155840',
   'cpi_9606.ENSP00000164139',
   'cpi_9606.ENSP00000171757',
   'cpi_9606.ENSP00000176183',
   'cpi_9606.ENSP00000176195',
   'cpi_9606.ENSP00000176763',
   'cpi_9606.ENSP00000178638',
   'cpi_9606.ENSP00000181383',
   'cpi_9606.ENSP00000196551',
   'cpi_9606.ENSP00000199280',
   'cpi_9606.ENSP00000200676',
   'cpi_9606.ENSP00000206249',
   'cpi_9606.ENSP00000211122',
   'cpi_9606.ENSP00000211287',
   'cpi_9606.ENSP00000212015',
   'cpi_9606.ENSP00000215659',
   'cpi_9606.ENSP00000215832',
   'cpi_9606.ENSP00000215904',
   'cpi_9606.ENSP00000215956',
   'cpi_9606.ENSP00000216024',
   'cpi_9606.ENSP00000216037',
   'cpi_9606.ENSP00000216117',
   'cpi_9606.ENSP00000216185',
   'cpi_9606.ENSP00000216341',
   'cpi_9606.ENSP00000216392',
   'cpi_9606.ENSP00000216410',
   'cpi_9606.ENSP00000216455',
   'cpi_9606.ENSP00000216465',
   'cpi_9606.ENSP00000216540',
   'cpi_9606.ENSP00000216629',
   'cpi_9606.ENSP00000216714',
   'cpi_9606.ENSP00000216797',
   'cpi_9606.ENSP00000216862',
   'cpi_9606.ENSP00000216911',
   'cpi_9606.ENSP00000216962',
   'cpi_9606.ENSP00000217133',
   'cpi_9606.ENSP00000217244',
   'cpi_9606.ENSP00000217270',
   'cpi_9606.ENSP00000217305',
   'cpi_9606.ENSP00000217386',
   'cpi_9606.ENSP00000217426',
   'cpi_9606.ENSP00000217961',
   'cpi_9606.ENSP00000218099',
   'cpi_9606.ENSP00000218388',
   'cpi_9606.ENSP00000218548',
   'cpi_9606.ENSP00000218721',
   'cpi_9606.ENSP00000218758',
   'cpi_9606.ENSP00000219070',
   'cpi_9606.ENSP00000219240',
   'cpi_9606.ENSP00000219252',
   'cpi_9606.ENSP00000219700',
   'cpi_9606.ENSP00000219794',
   'cpi_9606.ENSP00000219833',
   'cpi_9606.ENSP00000219919',
   'cpi_9606.ENSP00000220003',
   'cpi_9606.ENSP00000220616',
   'cpi_9606.ENSP00000220764',
   'cpi_9606.ENSP00000220809',
   'cpi_9606.ENSP00000221130',
   'cpi_9606.ENSP00000221138',
   'cpi_9606.ENSP00000221421',
   'cpi_9606.ENSP00000221515',
   'cpi_9606.ENSP00000221930',
   'cpi_9606.ENSP00000221972',
   'cpi_9606.ENSP00000222002',
   'cpi_9606.ENSP00000222256',
   'cpi_9606.ENSP00000222330',
   'cpi_9606.ENSP00000222381',
   'cpi_9606.ENSP00000222390',
   'cpi_9606.ENSP00000222481',
   'cpi_9606.ENSP00000222482',
   'cpi_9606.ENSP00000222553',
   'cpi_9606.ENSP00000222982',
   'cpi_9606.ENSP00000223095',
   'cpi_9606.ENSP00000223366',
   'cpi_9606.ENSP00000223642',
   'cpi_9606.ENSP00000224784',
   'cpi_9606.ENSP00000225275',
   'cpi_9606.ENSP00000225371',
   'cpi_9606.ENSP00000225426',
   'cpi_9606.ENSP00000225430',
   'cpi_9606.ENSP00000225474',
   'cpi_9606.ENSP00000225577',
   'cpi_9606.ENSP00000225740',
   'cpi_9606.ENSP00000225831',
   'cpi_9606.ENSP00000225927',
   'cpi_9606.ENSP00000225964',
   'cpi_9606.ENSP00000225992',
   'cpi_9606.ENSP00000226299',
   'cpi_9606.ENSP00000226317',
   'cpi_9606.ENSP00000226413',
   'cpi_9606.ENSP00000226444',
   'cpi_9606.ENSP00000226574',
   'cpi_9606.ENSP00000226578',
   'cpi_9606.ENSP00000226730',
   'cpi_9606.ENSP00000226840',
   'cpi_9606.ENSP00000227378',
   'cpi_9606.ENSP00000227507',
   'cpi_9606.ENSP00000227758',
   'cpi_9606.ENSP00000228476',
   'cpi_9606.ENSP00000228740',
   'cpi_9606.ENSP00000228872',
   'cpi_9606.ENSP00000229135',
   'cpi_9606.ENSP00000229239',
   'cpi_9606.ENSP00000229264',
   'cpi_9606.ENSP00000229270',
   'cpi_9606.ENSP00000229277',
   'cpi_9606.ENSP00000229319',
   'cpi_9606.ENSP00000229447',
   'cpi_9606.ENSP00000229794',
   'cpi_9606.ENSP00000230050',
   'cpi_9606.ENSP00000230671',
   'cpi_9606.ENSP00000231188',
   'cpi_9606.ENSP00000231228',
   'cpi_9606.ENSP00000231449',
   'cpi_9606.ENSP00000231454',
   'cpi_9606.ENSP00000231509',
   'cpi_9606.ENSP00000231751',
   'cpi_9606.ENSP00000231790',
   'cpi_9606.ENSP00000232219',
   'cpi_9606.ENSP00000232607',
   'cpi_9606.ENSP00000232892',
   'cpi_9606.ENSP00000233146',
   'cpi_9606.ENSP00000233242',
   'cpi_9606.ENSP00000233944',
   'cpi_9606.ENSP00000234071',
   'cpi_9606.ENSP00000234111',
   'cpi_9606.ENSP00000234310',
   'cpi_9606.ENSP00000234371',
   'cpi_9606.ENSP00000234389',
   'cpi_9606.ENSP00000234590',
   'cpi_9606.ENSP00000234961',
   'cpi_9606.ENSP00000235382',
   'cpi_9606.ENSP00000236671',
   'cpi_9606.ENSP00000236850',
   'cpi_9606.ENSP00000237014',
   'cpi_9606.ENSP00000237527',
   'cpi_9606.ENSP00000237612',
   'cpi_9606.ENSP00000237858',
   'cpi_9606.ENSP00000238018',
   'cpi_9606.ENSP00000238379',
   'cpi_9606.ENSP00000239223',
   'cpi_9606.ENSP00000239849',
   'cpi_9606.ENSP00000239938',
   'cpi_9606.ENSP00000240139',
   'cpi_9606.ENSP00000240615',
   'cpi_9606.ENSP00000240619',
   'cpi_9606.ENSP00000240652',
   'cpi_9606.ENSP00000240687',
   'cpi_9606.ENSP00000240691',
   'cpi_9606.ENSP00000240874',
   'cpi_9606.ENSP00000241052',
   'cpi_9606.ENSP00000241256',
   'cpi_9606.ENSP00000241261',
   'cpi_9606.ENSP00000241453',
   'cpi_9606.ENSP00000241600',
   'cpi_9606.ENSP00000242057',
   'cpi_9606.ENSP00000242152',
   'cpi_9606.ENSP00000242375',
   'cpi_9606.ENSP00000242839',
   'cpi_9606.ENSP00000243167',
   'cpi_9606.ENSP00000243911',
   'cpi_9606.ENSP00000244051',
   'cpi_9606.ENSP00000244137',
   'cpi_9606.ENSP00000244217',
   'cpi_9606.ENSP00000244289',
   'cpi_9606.ENSP00000244741',
   'cpi_9606.ENSP00000245206',
   'cpi_9606.ENSP00000245457',
   'cpi_9606.ENSP00000245539',
   'cpi_9606.ENSP00000245907',
   'cpi_9606.ENSP00000245983',
   'cpi_9606.ENSP00000246115',
   'cpi_9606.ENSP00000246337',
   'cpi_9606.ENSP00000246549',
   'cpi_9606.ENSP00000246553',
   'cpi_9606.ENSP00000246657',
   'cpi_9606.ENSP00000247879',
   'cpi_9606.ENSP00000247881',
   'cpi_9606.ENSP00000247883',
   'cpi_9606.ENSP00000248041',
   'cpi_9606.ENSP00000248076',
   'cpi_9606.ENSP00000248437',
   'cpi_9606.ENSP00000248553',
   'cpi_9606.ENSP00000248572',
   'cpi_9606.ENSP00000248923',
   'cpi_9606.ENSP00000248935',
   'cpi_9606.ENSP00000249016',
   'cpi_9606.ENSP00000249041',
   'cpi_9606.ENSP00000249284',
   'cpi_9606.ENSP00000249750',
   'cpi_9606.ENSP00000250378',
   'cpi_9606.ENSP00000250615',
   'cpi_9606.ENSP00000250971',
   'cpi_9606.ENSP00000251453',
   'cpi_9606.ENSP00000251535',
   'cpi_9606.ENSP00000251566',
   'cpi_9606.ENSP00000251595',
   'cpi_9606.ENSP00000251810',
   'cpi_9606.ENSP00000251849',
   'cpi_9606.ENSP00000252029',
   'cpi_9606.ENSP00000252321',
   'cpi_9606.ENSP00000252486',
   'cpi_9606.ENSP00000252519',
   'cpi_9606.ENSP00000252723',
   'cpi_9606.ENSP00000252804',
   'cpi_9606.ENSP00000252809',
   'cpi_9606.ENSP00000252945',
   'cpi_9606.ENSP00000253004',
   'cpi_9606.ENSP00000253099',
   'cpi_9606.ENSP00000253122',
   'cpi_9606.ENSP00000253303',
   'cpi_9606.ENSP00000253727',
   'cpi_9606.ENSP00000253792',
   'cpi_9606.ENSP00000253799',
   'cpi_9606.ENSP00000254066',
   'cpi_9606.ENSP00000254079',
   'cpi_9606.ENSP00000254227',
   'cpi_9606.ENSP00000254235',
   'cpi_9606.ENSP00000254488',
   'cpi_9606.ENSP00000254810',
   'cpi_9606.ENSP00000254976',
   'cpi_9606.ENSP00000255008',
   'cpi_9606.ENSP00000255030',
   'cpi_9606.ENSP00000255084',
   'cpi_9606.ENSP00000255262',
   'cpi_9606.ENSP00000255380',
   'cpi_9606.ENSP00000255409',
   'cpi_9606.ENSP00000255465',
   'cpi_9606.ENSP00000256010',
   'cpi_9606.ENSP00000256078',
   'cpi_9606.ENSP00000256104',
   'cpi_9606.ENSP00000256119',
   'cpi_9606.ENSP00000256383',
   'cpi_9606.ENSP00000256442',
   'cpi_9606.ENSP00000256578',
   'cpi_9606.ENSP00000256722',
   'cpi_9606.ENSP00000256857',
   'cpi_9606.ENSP00000256906',
   'cpi_9606.ENSP00000256958',
   'cpi_9606.ENSP00000256999',
   'cpi_9606.ENSP00000257068',
   'cpi_9606.ENSP00000257254',
   'cpi_9606.ENSP00000257290',
   'cpi_9606.ENSP00000257497',
   'cpi_9606.ENSP00000257770',
   'cpi_9606.ENSP00000258042',
   'cpi_9606.ENSP00000258317',
   'cpi_9606.ENSP00000258400',
   'cpi_9606.ENSP00000258662',
   'cpi_9606.ENSP00000258743',
   'cpi_9606.ENSP00000258749',
   'cpi_9606.ENSP00000259089',
   'cpi_9606.ENSP00000259271',
   'cpi_9606.ENSP00000259396',
   'cpi_9606.ENSP00000259457',
   'cpi_9606.ENSP00000259469',
   'cpi_9606.ENSP00000259486',
   'cpi_9606.ENSP00000259607',
   'cpi_9606.ENSP00000259631',
   'cpi_9606.ENSP00000259667',
   'cpi_9606.ENSP00000259818',
   'cpi_9606.ENSP00000260010',
   'cpi_9606.ENSP00000260102',
   'cpi_9606.ENSP00000260191',
   'cpi_9606.ENSP00000260227',
   'cpi_9606.ENSP00000260302',
   'cpi_9606.ENSP00000260356',
   'cpi_9606.ENSP00000260402',
   'cpi_9606.ENSP00000260433',
   'cpi_9606.ENSP00000260443',
   'cpi_9606.ENSP00000260600',
   'cpi_9606.ENSP00000260630',
   'cpi_9606.ENSP00000260649',
   'cpi_9606.ENSP00000260682',
   'cpi_9606.ENSP00000260970',
   'cpi_9606.ENSP00000261196',
   'cpi_9606.ENSP00000261205',
   'cpi_9606.ENSP00000261267',
   'cpi_9606.ENSP00000261386',
   'cpi_9606.ENSP00000261405',
   'cpi_9606.ENSP00000261416',
   'cpi_9606.ENSP00000261465',
   'cpi_9606.ENSP00000261479',
   'cpi_9606.ENSP00000261693',
   'cpi_9606.ENSP00000261707',
   'cpi_9606.ENSP00000261733',
   'cpi_9606.ENSP00000261755',
   'cpi_9606.ENSP00000261769',
   'cpi_9606.ENSP00000261799',
   'cpi_9606.ENSP00000261835',
   'cpi_9606.ENSP00000261937',
   'cpi_9606.ENSP00000262017',
   'cpi_9606.ENSP00000262027',
   'cpi_9606.ENSP00000262160',
   'cpi_9606.ENSP00000262178',
   'cpi_9606.ENSP00000262186',
   'cpi_9606.ENSP00000262187',
   'cpi_9606.ENSP00000262193',
   'cpi_9606.ENSP00000262290',
   'cpi_9606.ENSP00000262352',
   'cpi_9606.ENSP00000262367',
   'cpi_9606.ENSP00000262407',
   'cpi_9606.ENSP00000262441',
   'cpi_9606.ENSP00000262461',
   'cpi_9606.ENSP00000262545',
   'cpi_9606.ENSP00000262584',
   'cpi_9606.ENSP00000262623',
   'cpi_9606.ENSP00000262735',
   'cpi_9606.ENSP00000262848',
   'cpi_9606.ENSP00000262888',
   'cpi_9606.ENSP00000262948',
   'cpi_9606.ENSP00000262958',
   'cpi_9606.ENSP00000262999',
   'cpi_9606.ENSP00000263025',
   'cpi_9606.ENSP00000263088',
   'cpi_9606.ENSP00000263126',
   'cpi_9606.ENSP00000263212',
   'cpi_9606.ENSP00000263269',
   'cpi_9606.ENSP00000263321',
   'cpi_9606.ENSP00000263339',
   'cpi_9606.ENSP00000263341',
   'cpi_9606.ENSP00000263377',
   'cpi_9606.ENSP00000263431',
   'cpi_9606.ENSP00000263464',
   'cpi_9606.ENSP00000263686',
   'cpi_9606.ENSP00000263817',
   'cpi_9606.ENSP00000263857',
   'cpi_9606.ENSP00000263923',
   'cpi_9606.ENSP00000263967',
   'cpi_9606.ENSP00000263980',
   'cpi_9606.ENSP00000264071',
   'cpi_9606.ENSP00000264162',
   'cpi_9606.ENSP00000264218',
   'cpi_9606.ENSP00000264318',
   'cpi_9606.ENSP00000264357',
   'cpi_9606.ENSP00000264381',
   'cpi_9606.ENSP00000264382',
   'cpi_9606.ENSP00000264399',
   'cpi_9606.ENSP00000264426',
   'cpi_9606.ENSP00000264498',
   'cpi_9606.ENSP00000264613',
   'cpi_9606.ENSP00000264637',
   'cpi_9606.ENSP00000264657',
   'cpi_9606.ENSP00000264668',
   'cpi_9606.ENSP00000264705',
   'cpi_9606.ENSP00000264708',
   'cpi_9606.ENSP00000264818',
   'cpi_9606.ENSP00000264832',
   'cpi_9606.ENSP00000264867',
   'cpi_9606.ENSP00000264896',
   'cpi_9606.ENSP00000264932',
   'cpi_9606.ENSP00000264995',
   'cpi_9606.ENSP00000265023',
   'cpi_9606.ENSP00000265100',
   'cpi_9606.ENSP00000265164',
   'cpi_9606.ENSP00000265171',
   'cpi_9606.ENSP00000265174',
   'cpi_9606.ENSP00000265294',
   'cpi_9606.ENSP00000265403',
   'cpi_9606.ENSP00000265421',
   'cpi_9606.ENSP00000265563',
   'cpi_9606.ENSP00000265572',
   'cpi_9606.ENSP00000265643',
   'cpi_9606.ENSP00000265717',
   'cpi_9606.ENSP00000265723',
   'cpi_9606.ENSP00000265724',
   'cpi_9606.ENSP00000266376',
   'cpi_9606.ENSP00000266682',
   'cpi_9606.ENSP00000266970',
   'cpi_9606.ENSP00000267017',
   'cpi_9606.ENSP00000267101',
   'cpi_9606.ENSP00000267119',
   'cpi_9606.ENSP00000267163',
   'cpi_9606.ENSP00000267377',
   'cpi_9606.ENSP00000267549',
   'cpi_9606.ENSP00000267843',
   'cpi_9606.ENSP00000268035',
   'cpi_9606.ENSP00000268053',
   'cpi_9606.ENSP00000268124',
   'cpi_9606.ENSP00000268171',
   'cpi_9606.ENSP00000268251',
   'cpi_9606.ENSP00000268661',
   'cpi_9606.ENSP00000268695',
   'cpi_9606.ENSP00000269159',
   'cpi_9606.ENSP00000269305',
   'cpi_9606.ENSP00000269571',
   'cpi_9606.ENSP00000270142',
   'cpi_9606.ENSP00000270202',
   'cpi_9606.ENSP00000270349',
   'cpi_9606.ENSP00000270474',
   'cpi_9606.ENSP00000270570',
   'cpi_9606.ENSP00000270586',
   'cpi_9606.ENSP00000270625',
   'cpi_9606.ENSP00000270631',
   'cpi_9606.ENSP00000270776',
   'cpi_9606.ENSP00000271308',
   'cpi_9606.ENSP00000271331',
   'cpi_9606.ENSP00000271620',
   'cpi_9606.ENSP00000272065',
   'cpi_9606.ENSP00000272167',
   'cpi_9606.ENSP00000272190',
   'cpi_9606.ENSP00000272227',
   'cpi_9606.ENSP00000272298',
   'cpi_9606.ENSP00000272317',
   'cpi_9606.ENSP00000272644',
   'cpi_9606.ENSP00000272847',
   'cpi_9606.ENSP00000272928',
   'cpi_9606.ENSP00000273077',
   'cpi_9606.ENSP00000273398',
   'cpi_9606.ENSP00000273430',
   'cpi_9606.ENSP00000273550',
   'cpi_9606.ENSP00000274026',
   'cpi_9606.ENSP00000274335',
   'cpi_9606.ENSP00000274353',
   'cpi_9606.ENSP00000274545',
   'cpi_9606.ENSP00000274547',
   'cpi_9606.ENSP00000274606',
   'cpi_9606.ENSP00000274793',
   'cpi_9606.ENSP00000275216',
   'cpi_9606.ENSP00000275300',
   'cpi_9606.ENSP00000275493',
   'cpi_9606.ENSP00000275525',
   'cpi_9606.ENSP00000276198',
   'cpi_9606.ENSP00000276414',
   'cpi_9606.ENSP00000276431',
   'cpi_9606.ENSP00000276449',
   'cpi_9606.ENSP00000276571',
   'cpi_9606.ENSP00000276590',
   'cpi_9606.ENSP00000276651',
   'cpi_9606.ENSP00000277010',
   'cpi_9606.ENSP00000277120',
   'cpi_9606.ENSP00000277508',
   'cpi_9606.ENSP00000277541',
   'cpi_9606.ENSP00000277942',
   'cpi_9606.ENSP00000278175',
   'cpi_9606.ENSP00000278616',
   'cpi_9606.ENSP00000279178',
   'cpi_9606.ENSP00000279230',
   'cpi_9606.ENSP00000279387',
   'cpi_9606.ENSP00000279593',
   'cpi_9606.ENSP00000280155',
   'cpi_9606.ENSP00000280357',
   'cpi_9606.ENSP00000280701',
   'cpi_9606.ENSP00000280704',
   'cpi_9606.ENSP00000280706',
   'cpi_9606.ENSP00000281806',
   'cpi_9606.ENSP00000282018',
   'cpi_9606.ENSP00000282077',
   'cpi_9606.ENSP00000282091',
   'cpi_9606.ENSP00000282397',
   'cpi_9606.ENSP00000282561',
   'cpi_9606.ENSP00000282753',
   'cpi_9606.ENSP00000282841',
   'cpi_9606.ENSP00000282957',
   'cpi_9606.ENSP00000283254',
   'cpi_9606.ENSP00000283558',
   'cpi_9606.ENSP00000283635',
   'cpi_9606.ENSP00000283646',
   'cpi_9606.ENSP00000283916',
   'cpi_9606.ENSP00000284981',
   'cpi_9606.ENSP00000285238',
   'cpi_9606.ENSP00000285379',
   'cpi_9606.ENSP00000285381',
   'cpi_9606.ENSP00000285900',
   'cpi_9606.ENSP00000285930',
   'cpi_9606.ENSP00000285979',
   'cpi_9606.ENSP00000286091',
   'cpi_9606.ENSP00000286301',
   'cpi_9606.ENSP00000286355',
   'cpi_9606.ENSP00000286479',
   'cpi_9606.ENSP00000286548',
   'cpi_9606.ENSP00000286621',
   'cpi_9606.ENSP00000286648',
   'cpi_9606.ENSP00000286719',
   'cpi_9606.ENSP00000286758',
   'cpi_9606.ENSP00000287641',
   'cpi_9606.ENSP00000287713',
   'cpi_9606.ENSP00000287766',
   'cpi_9606.ENSP00000287820',
   'cpi_9606.ENSP00000287878',
   'cpi_9606.ENSP00000287907',
   'cpi_9606.ENSP00000287936',
   'cpi_9606.ENSP00000288022',
   'cpi_9606.ENSP00000288135',
   'cpi_9606.ENSP00000288139',
   'cpi_9606.ENSP00000288602',
   'cpi_9606.ENSP00000289753',
   'cpi_9606.ENSP00000290349',
   'cpi_9606.ENSP00000290378',
   'cpi_9606.ENSP00000290541',
   'cpi_9606.ENSP00000290866',
   'cpi_9606.ENSP00000291294',
   'cpi_9606.ENSP00000291295',
   'cpi_9606.ENSP00000291565',
   'cpi_9606.ENSP00000291700',
   'cpi_9606.ENSP00000292095',
   'cpi_9606.ENSP00000292147',
   'cpi_9606.ENSP00000292174',
   'cpi_9606.ENSP00000292301',
   'cpi_9606.ENSP00000292303',
   'cpi_9606.ENSP00000292427',
   'cpi_9606.ENSP00000292513',
   'cpi_9606.ENSP00000292896',
   'cpi_9606.ENSP00000293190',
   'cpi_9606.ENSP00000293230',
   'cpi_9606.ENSP00000293272',
   'cpi_9606.ENSP00000293275',
   'cpi_9606.ENSP00000293288',
   'cpi_9606.ENSP00000293330',
   'cpi_9606.ENSP00000293404',
   'cpi_9606.ENSP00000293636',
   'cpi_9606.ENSP00000293745',
   'cpi_9606.ENSP00000293778',
   'cpi_9606.ENSP00000293813',
   'cpi_9606.ENSP00000293842',
   'cpi_9606.ENSP00000293897',
   'cpi_9606.ENSP00000294016',
   'cpi_9606.ENSP00000294728',
   'cpi_9606.ENSP00000294954',
   'cpi_9606.ENSP00000295137',
   'cpi_9606.ENSP00000295256',
   'cpi_9606.ENSP00000295400',
   'cpi_9606.ENSP00000295448',
   'cpi_9606.ENSP00000295452',
   'cpi_9606.ENSP00000295453',
   'cpi_9606.ENSP00000295454',
   'cpi_9606.ENSP00000295491',
   'cpi_9606.ENSP00000295589',
   'cpi_9606.ENSP00000295598',
   'cpi_9606.ENSP00000295619',
   'cpi_9606.ENSP00000295683',
   'cpi_9606.ENSP00000295731',
   'cpi_9606.ENSP00000295834',
   'cpi_9606.ENSP00000295897',
   'cpi_9606.ENSP00000295930',
   'cpi_9606.ENSP00000296026',
   'cpi_9606.ENSP00000296027',
   'cpi_9606.ENSP00000296028',
   'cpi_9606.ENSP00000296046',
   'cpi_9606.ENSP00000296122',
   'cpi_9606.ENSP00000296140',
   'cpi_9606.ENSP00000296271',
   'cpi_9606.ENSP00000296277',
   'cpi_9606.ENSP00000296350',
   'cpi_9606.ENSP00000296370',
   'cpi_9606.ENSP00000296411',
   'cpi_9606.ENSP00000296412',
   'cpi_9606.ENSP00000296511',
   'cpi_9606.ENSP00000296522',
   'cpi_9606.ENSP00000296545',
   'cpi_9606.ENSP00000296641',
   'cpi_9606.ENSP00000296674',
   'cpi_9606.ENSP00000296677',
   'cpi_9606.ENSP00000296754',
   'cpi_9606.ENSP00000296871',
   'cpi_9606.ENSP00000297258',
   'cpi_9606.ENSP00000297261',
   'cpi_9606.ENSP00000297268',
   'cpi_9606.ENSP00000297313',
   'cpi_9606.ENSP00000297316',
   'cpi_9606.ENSP00000297323',
   'cpi_9606.ENSP00000297350',
   'cpi_9606.ENSP00000297469',
   'cpi_9606.ENSP00000297494',
   'cpi_9606.ENSP00000297770',
   'cpi_9606.ENSP00000297785',
   'cpi_9606.ENSP00000297792',
   'cpi_9606.ENSP00000297991',
   'cpi_9606.ENSP00000298139',
   'cpi_9606.ENSP00000298171',
   'cpi_9606.ENSP00000298283',
   'cpi_9606.ENSP00000298352',
   'cpi_9606.ENSP00000298386',
   'cpi_9606.ENSP00000298440',
   'cpi_9606.ENSP00000298472',
   'cpi_9606.ENSP00000299178',
   'cpi_9606.ENSP00000299267',
   'cpi_9606.ENSP00000299727',
   'cpi_9606.ENSP00000299766',
   'cpi_9606.ENSP00000299847',
   'cpi_9606.ENSP00000299855',
   'cpi_9606.ENSP00000300060',
   'cpi_9606.ENSP00000300061',
   'cpi_9606.ENSP00000300093',
   'cpi_9606.ENSP00000300108',
   'cpi_9606.ENSP00000300151',
   'cpi_9606.ENSP00000300289',
   'cpi_9606.ENSP00000300738',
   'cpi_9606.ENSP00000300900',
   'cpi_9606.ENSP00000301071',
   'cpi_9606.ENSP00000301072',
   'cpi_9606.ENSP00000301141',
   'cpi_9606.ENSP00000301146',
   'cpi_9606.ENSP00000301178',
   'cpi_9606.ENSP00000301420',
   'cpi_9606.ENSP00000301633',
   'cpi_9606.ENSP00000301634',
   'cpi_9606.ENSP00000301645',
   'cpi_9606.ENSP00000301891',
   'cpi_9606.ENSP00000301908',
   'cpi_9606.ENSP00000301974',
   'cpi_9606.ENSP00000302079',
   'cpi_9606.ENSP00000302111',
   'cpi_9606.ENSP00000302150',
   'cpi_9606.ENSP00000302393',
   'cpi_9606.ENSP00000302441',
   'cpi_9606.ENSP00000302486',
   'cpi_9606.ENSP00000302564',
   'cpi_9606.ENSP00000302620',
   'cpi_9606.ENSP00000302665',
   'cpi_9606.ENSP00000302707',
   'cpi_9606.ENSP00000302728',
   'cpi_9606.ENSP00000302811',
   'cpi_9606.ENSP00000302846',
   'cpi_9606.ENSP00000302886',
   'cpi_9606.ENSP00000302961',

In [3]:
paths = [path for path in paths if "ten_mid" in path["dataset_name"]]
len(paths)

3

In [4]:
k = 10
random_state = 42
performances = []
ranking_criteria = "MDI"  # or "VAR"
include_original_features_options = [True, False]
training_algorithm = "Variance Reduction"
eval_criteria = ["averageAUROC", "HammingLoss", "SubsetAccuracy", "RankingLoss", "MacroPrecision", "MacroRecall",
                 "MacroFOne"]
max_size = 5
cv_results = []

for idx, path in enumerate(paths, start=1):
    run_config = f"\n--- Running with label:'{path["label_set"]}' training_algorithm:'{training_algorithm}' eval_criterion:'{eval_criteria}' max_size:'{max_size}' ---"
    print(run_config)
    run_config_name = "_".join(
        [
            path["dataset_name"],
            training_algorithm,
            "_".join(eval_criteria),
            str(max_size),
        ]
    )
    logging_path = f"XofN_filter/logs/{run_config_name}_logs.txt"
    print(f"Logs can be found in {logging_path}.")
    logger = get_logger(logging_path)
    logger.info(run_config_name)

    # Load dataset
    current_df = pd.read_csv(path["dataset_path"])
    features = get_features(current_df, path["label_set"])
    # current_df = current_df[features[:10] + path["label_set"]]
    kf = KFold(n_splits=k, shuffle=True, random_state=random_state)
    for fold, (train_idx, test_idx) in enumerate(kf.split(current_df), start=1):
        print(f"\nFold {fold}/{k} ({path["dataset_name"]} {idx}/{len(paths)})")
        train_dataset = current_df.iloc[train_idx]
        test_dataset = current_df.iloc[test_idx]

        if ranking_criteria == "VAR":
            feature_rankings = feature_variance_reduction_scores(train_dataset[features],
                                                                 train_dataset[path["label_set"]])
        elif ranking_criteria == "MDI":
            feature_rankings = calculate_mdi_multi_rf(train_dataset, path["label_set"])
        else:
            raise NotImplementedError

        XofN_groupings, avg_features, gen_XofN_time = generate_XofN_list_multi_custom(
            train_dataset,
            feature_rankings,
            max_size,
            path["label_set"],
            logger
        )
        if len(XofN_groupings) == 0:
            print("no XofN groupings were created")
        else:
            for include_original_features in include_original_features_options:
                current_train_dataset = group_features(
                    train_dataset,
                    path["label_set"],
                    XofN_groupings,
                    include_original_features,
                    verbose=True
                )

                current_test_dataset = group_features(
                    test_dataset,
                    path["label_set"],
                    XofN_groupings,
                    include_original_features,
                    verbose=True
                )

                current_train_dataset.to_csv(f"XofN_filter/tmp/train_dataset.csv", index=False)
                current_test_dataset.to_csv(f"XofN_filter/tmp/test_dataset.csv", index=False)

                training_start = time.perf_counter()
                original_res, pruned_res, training_time = run_PCT(clus_path,
                                                                  "XofN_filter/tmp/train_dataset.csv",
                                                                  path["label_set"],
                                                                  eval_criteria,
                                                                  test_dataset_path=f"XofN_filter/tmp/test_dataset.csv")
                pruned_performance = get_fold_results(pruned_res, eval_criteria, True, fold, include_original_features,
                                                      XofN_groupings,
                                                      gen_XofN_time,
                                                      training_time, path["dataset_name"])
                performances.append(pruned_performance)
                performance = get_fold_results(original_res, eval_criteria, False, fold, include_original_features,
                                               XofN_groupings,
                                               gen_XofN_time,
                                               training_time, path["dataset_name"])
                performances.append(performance)

    if len(performances) == 0:
        print("no XofN groupings were created in any fold")
    else:
        final_perf_df = pd.DataFrame(performances)
        averages = final_perf_df.groupby(["pruning", 'include_original_features', 'dataset'])[
            eval_criteria + ['nodes', 'leaves', 'groups',
                             'avg_group_features', 'gen_XofN_time', 'training_time']].mean().reset_index()
        print(averages)
        cv_results.append(averages)
        performances = []
# paths[0] - features[:10] desktop 0.29m
# laptop ??m
# desktop 14h

--- Running with label:'['se_C0009676', 'se_C0041657', 'se_C0002994', 'se_C0042571', 'se_C0004604', 'se_C0041834', 'se_C0085631', 'se_C0040822', 'se_C0042373', 'se_C0021053']' training_algorithm:'Variance Reduction' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_filter/logs/CPI+fingerprint_ten_mid_Variance Reduction_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [12:26<00:00,  2.88feat/s]

XofN groups with 2 features: 30
XofN groups with 3 features: 7
XofN groups with 4 features: 9
XofN groups with 5 features: 402
pruning: True, include_original_features: with_org, averageAUROC: 0.5436044, HammingLoss: 0.38273, SubsetAccuracy: 0.10791, RankingLoss: 0.38177, MacroPrecision: 0.45909, MacroRecall: 0.27702, MacroFOne: 0.33737,
pruning: False, include_original_features: with_org, averageAUROC: 0.5453187, HammingLoss: 0.44317, SubsetAccuracy: 0.05036, RankingLoss: 0.35356, MacroPrecision: 0.40498, MacroRecall: 0.47027, MacroFOne: 0.4328,
pruning: True, include_original_features: no_org, averageAUROC: 0.5454955, HammingLoss: 0.36978, SubsetAccuracy: 0.1223, RankingLoss: 0.38399, MacroPrecision: 0.48176, MacroRecall: 0.28304, MacroFOne: 0.35102,
pruning: False, include_original_features: no_org, averageAUROC: 0.5458158, HammingLoss: 0.44388, SubsetAccuracy: 0.0071942, RankingLoss: 0.35265, MacroPrecision: 0.39906, MacroRecall: 0.45944, MacroFOne: 0.42606,

Fold 2/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [12:30<00:00,  2.86feat/s]

XofN groups with 2 features: 13
XofN groups with 3 features: 9
XofN groups with 4 features: 8
XofN groups with 5 features: 405
pruning: True, include_original_features: with_org, averageAUROC: 0.6426293, HammingLoss: 0.31942, SubsetAccuracy: 0.15108, RankingLoss: 0.34349, MacroPrecision: 0.5504, MacroRecall: 0.38107, MacroFOne: 0.44923,
pruning: False, include_original_features: with_org, averageAUROC: 0.6006948, HammingLoss: 0.38849, SubsetAccuracy: 0.071942, RankingLoss: 0.33417, MacroPrecision: 0.44246, MacroRecall: 0.5154, MacroFOne: 0.47571,
pruning: True, include_original_features: no_org, averageAUROC: 0.5792706, HammingLoss: 0.30791, SubsetAccuracy: 0.15108, RankingLoss: 0.36345, MacroPrecision: 0.63648, MacroRecall: 0.24135, MacroFOne: 0.34919,
pruning: False, include_original_features: no_org, averageAUROC: 0.6115845, HammingLoss: 0.37698, SubsetAccuracy: 0.071942, RankingLoss: 0.32971, MacroPrecision: 0.45803, MacroRecall: 0.53908, MacroFOne: 0.49407,

Fold 3/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [12:28<00:00,  2.87feat/s]

XofN groups with 2 features: 11
XofN groups with 3 features: 18
XofN groups with 4 features: 12
XofN groups with 5 features: 399
pruning: True, include_original_features: with_org, averageAUROC: 0.6044948, HammingLoss: 0.37626, SubsetAccuracy: 0.10072, RankingLoss: 0.34, MacroPrecision: 0.5196, MacroRecall: 0.34875, MacroFOne: 0.41423,
pruning: False, include_original_features: with_org, averageAUROC: 0.5765812, HammingLoss: 0.42662, SubsetAccuracy: 0.05036, RankingLoss: 0.39028, MacroPrecision: 0.45484, MacroRecall: 0.4754, MacroFOne: 0.46009,
pruning: True, include_original_features: no_org, averageAUROC: 0.5889898, HammingLoss: 0.38417, SubsetAccuracy: 0.10072, RankingLoss: 0.34125, MacroPrecision: 0.50264, MacroRecall: 0.32733, MacroFOne: 0.39385,
pruning: False, include_original_features: no_org, averageAUROC: 0.5800128, HammingLoss: 0.41727, SubsetAccuracy: 0.064748, RankingLoss: 0.37173, MacroPrecision: 0.46743, MacroRecall: 0.4926, MacroFOne: 0.47638,

Fold 4/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [11:54<00:00,  3.00feat/s]

XofN groups with 2 features: 9
XofN groups with 3 features: 13
XofN groups with 4 features: 17
XofN groups with 5 features: 399
pruning: True, include_original_features: with_org, averageAUROC: 0.5840837, HammingLoss: 0.33597, SubsetAccuracy: 0.14388, RankingLoss: 0.3791, MacroPrecision: 0.47506, MacroRecall: 0.19864, MacroFOne: 0.27666,
pruning: False, include_original_features: with_org, averageAUROC: 0.5202761, HammingLoss: 0.45683, SubsetAccuracy: 0.021583, RankingLoss: 0.3944, MacroPrecision: 0.33541, MacroRecall: 0.39368, MacroFOne: 0.36005,
pruning: True, include_original_features: no_org, averageAUROC: 0.5907299, HammingLoss: 0.33741, SubsetAccuracy: 0.1295, RankingLoss: 0.38505, MacroPrecision: 0.45585, MacroRecall: 0.19407, MacroFOne: 0.26728,
pruning: False, include_original_features: no_org, averageAUROC: 0.5530253, HammingLoss: 0.43309, SubsetAccuracy: 0.043165, RankingLoss: 0.37746, MacroPrecision: 0.37273, MacroRecall: 0.47116, MacroFOne: 0.415,

Fold 5/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [11:08<00:00,  3.21feat/s]

XofN groups with 2 features: 13
XofN groups with 3 features: 11
XofN groups with 4 features: 8
XofN groups with 5 features: 406
pruning: True, include_original_features: with_org, averageAUROC: 0.609076, HammingLoss: 0.32518, SubsetAccuracy: 0.093525, RankingLoss: 0.36231, MacroPrecision: 0.52745, MacroRecall: 0.31077, MacroFOne: 0.38852,
pruning: False, include_original_features: with_org, averageAUROC: 0.5963621, HammingLoss: 0.38345, SubsetAccuracy: 0.079137, RankingLoss: 0.34911, MacroPrecision: 0.4404, MacroRecall: 0.51051, MacroFOne: 0.46998,
pruning: True, include_original_features: no_org, averageAUROC: 0.6038451, HammingLoss: 0.31295, SubsetAccuracy: 0.10072, RankingLoss: 0.33518, MacroPrecision: 0.56229, MacroRecall: 0.26464, MacroFOne: 0.35366,
pruning: False, include_original_features: no_org, averageAUROC: 0.5973802, HammingLoss: 0.38417, SubsetAccuracy: 0.071942, RankingLoss: 0.37487, MacroPrecision: 0.44566, MacroRecall: 0.54101, MacroFOne: 0.48444,

Fold 6/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [11:10<00:00,  3.20feat/s]

XofN groups with 2 features: 11
XofN groups with 3 features: 6
XofN groups with 4 features: 11
XofN groups with 5 features: 406
pruning: True, include_original_features: with_org, averageAUROC: 0.5771551, HammingLoss: 0.35252, SubsetAccuracy: 0.17266, RankingLoss: 0.35317, MacroPrecision: 0.55923, MacroRecall: 0.26444, MacroFOne: 0.35485,
pruning: False, include_original_features: with_org, averageAUROC: 0.6085737, HammingLoss: 0.37554, SubsetAccuracy: 0.086331, RankingLoss: 0.33481, MacroPrecision: 0.4969, MacroRecall: 0.4881, MacroFOne: 0.49065,
pruning: True, include_original_features: no_org, averageAUROC: 0.5893329, HammingLoss: 0.33813, SubsetAccuracy: 0.17986, RankingLoss: 0.34291, MacroPrecision: 0.60402, MacroRecall: 0.26435, MacroFOne: 0.36655,
pruning: False, include_original_features: no_org, averageAUROC: 0.592143, HammingLoss: 0.39137, SubsetAccuracy: 0.057554, RankingLoss: 0.32072, MacroPrecision: 0.47637, MacroRecall: 0.49825, MacroFOne: 0.48633,

Fold 7/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [11:08<00:00,  3.21feat/s]

XofN groups with 2 features: 11
XofN groups with 3 features: 18
XofN groups with 4 features: 5
XofN groups with 5 features: 405
pruning: True, include_original_features: with_org, averageAUROC: 0.6289912, HammingLoss: 0.30145, SubsetAccuracy: 0.16667, RankingLoss: 0.29623, MacroPrecision: 0.52049, MacroRecall: 0.28254, MacroFOne: 0.36399,
pruning: False, include_original_features: with_org, averageAUROC: 0.571092, HammingLoss: 0.4029, SubsetAccuracy: 0.065217, RankingLoss: 0.30664, MacroPrecision: 0.37556, MacroRecall: 0.47313, MacroFOne: 0.41659,
pruning: True, include_original_features: no_org, averageAUROC: 0.6143939, HammingLoss: 0.30652, SubsetAccuracy: 0.18116, RankingLoss: 0.30723, MacroPrecision: 0.50569, MacroRecall: 0.28406, MacroFOne: 0.36022,
pruning: False, include_original_features: no_org, averageAUROC: 0.6028038, HammingLoss: 0.38696, SubsetAccuracy: 0.043478, RankingLoss: 0.26896, MacroPrecision: 0.39682, MacroRecall: 0.49251, MacroFOne: 0.43699,

Fold 8/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [11:09<00:00,  3.20feat/s]

XofN groups with 2 features: 18
XofN groups with 3 features: 6
XofN groups with 4 features: 13
XofN groups with 5 features: 402
pruning: True, include_original_features: with_org, averageAUROC: 0.582657, HammingLoss: 0.37681, SubsetAccuracy: 0.1087, RankingLoss: 0.35246, MacroPrecision: 0.45062, MacroRecall: 0.21074, MacroFOne: 0.28535,
pruning: False, include_original_features: with_org, averageAUROC: 0.5689466, HammingLoss: 0.40072, SubsetAccuracy: 0.021739, RankingLoss: 0.3801, MacroPrecision: 0.44124, MacroRecall: 0.43613, MacroFOne: 0.43761,
pruning: True, include_original_features: no_org, averageAUROC: 0.5892153, HammingLoss: 0.37101, SubsetAccuracy: 0.07971, RankingLoss: 0.35795, MacroPrecision: 0.47437, MacroRecall: 0.24963, MacroFOne: 0.32378,
pruning: False, include_original_features: no_org, averageAUROC: 0.5470236, HammingLoss: 0.43696, SubsetAccuracy: 0.050725, RankingLoss: 0.38953, MacroPrecision: 0.41105, MacroRecall: 0.48242, MacroFOne: 0.44185,

Fold 9/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [11:10<00:00,  3.20feat/s]

XofN groups with 2 features: 19
XofN groups with 3 features: 9
XofN groups with 4 features: 11
XofN groups with 5 features: 400
pruning: True, include_original_features: with_org, averageAUROC: 0.6044158, HammingLoss: 0.35725, SubsetAccuracy: 0.1087, RankingLoss: 0.31708, MacroPrecision: 0.48424, MacroRecall: 0.29488, MacroFOne: 0.3642,
pruning: False, include_original_features: with_org, averageAUROC: 0.5757474, HammingLoss: 0.4029, SubsetAccuracy: 0.043478, RankingLoss: 0.33778, MacroPrecision: 0.43171, MacroRecall: 0.45675, MacroFOne: 0.43936,
pruning: True, include_original_features: no_org, averageAUROC: 0.606725, HammingLoss: 0.34058, SubsetAccuracy: 0.1087, RankingLoss: 0.30898, MacroPrecision: 0.52457, MacroRecall: 0.30152, MacroFOne: 0.38095,
pruning: False, include_original_features: no_org, averageAUROC: 0.5743485, HammingLoss: 0.40217, SubsetAccuracy: 0.028986, RankingLoss: 0.33197, MacroPrecision: 0.43125, MacroRecall: 0.45958, MacroFOne: 0.44279,

Fold 10/10 (CPI+fingerprint_ten_mid 1/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 2147/2147 [11:08<00:00,  3.21feat/s]

XofN groups with 2 features: 9
XofN groups with 3 features: 14
XofN groups with 4 features: 5
XofN groups with 5 features: 406
pruning: True, include_original_features: with_org, averageAUROC: 0.6423705, HammingLoss: 0.30217, SubsetAccuracy: 0.16667, RankingLoss: 0.33008, MacroPrecision: 0.55446, MacroRecall: 0.28671, MacroFOne: 0.36959,
pruning: False, include_original_features: with_org, averageAUROC: 0.6260885, HammingLoss: 0.36304, SubsetAccuracy: 0.028986, RankingLoss: 0.33126, MacroPrecision: 0.45213, MacroRecall: 0.55946, MacroFOne: 0.49819,
pruning: True, include_original_features: no_org, averageAUROC: 0.6237801, HammingLoss: 0.31522, SubsetAccuracy: 0.15942, RankingLoss: 0.33771, MacroPrecision: 0.50463, MacroRecall: 0.26307, MacroFOne: 0.34025,
pruning: False, include_original_features: no_org, averageAUROC: 0.569274, HammingLoss: 0.41449, SubsetAccuracy: 0.036232, RankingLoss: 0.35862, MacroPrecision: 0.39082, MacroRecall: 0.50081, MacroFOne: 0.43618,
   pruning include_original_features                  dataset  averageAUROC  \
0    False                    no_org  CPI+fingerprint_ten_mid      0.577341
1    False                  with_org  CPI+fingerprint_ten_mid      0.578968
2     True                    no_org  CPI+fingerprint_ten_mid      0.593178
3     True                  with_org  CPI+fingerprint_ten_mid      0.601948

   HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
0     0.408734        0.047597     0.347622        0.424922     0.493686
1     0.404366        0.051913     0.351211        0.427563     0.477883
2     0.338368        0.131317     0.346370        0.525230     0.267306
3     0.342976        0.132052     0.345569        0.510064     0.285556

   MacroFOne   nodes  leaves  groups  avg_group_features  gen_XofN_time  \
0   0.454009  1022.8   511.9   438.4             4.82852     697.756258
1   0.448103  1019.6   510.3   438.4             4.82852     697.756258
2   0.348675    82.2    41.6   438.4             4.82852     697.756258
3   0.360399    96.2    48.6   438.4             4.82852     697.756258

   training_time
0       1.222673
1       3.740729
2       1.222673
3       3.740729

--- Running with label:'['se_C0009676', 'se_C0041657', 'se_C0002994', 'se_C0042571', 'se_C0004604', 'se_C0041834', 'se_C0085631', 'se_C0040822', 'se_C0042373', 'se_C0021053']' training_algorithm:'Variance Reduction' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_filter/logs/CPI_ten_mid_Variance Reduction_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [07:06<00:00,  3.77feat/s]

XofN groups with 2 features: 9
XofN groups with 3 features: 14
XofN groups with 4 features: 10
XofN groups with 5 features: 296
pruning: True, include_original_features: with_org, averageAUROC: 0.5496722, HammingLoss: 0.39459, SubsetAccuracy: 0.063063, RankingLoss: 0.39888, MacroPrecision: 0.47728, MacroRecall: 0.28521, MacroFOne: 0.34984,
pruning: False, include_original_features: with_org, averageAUROC: 0.523609, HammingLoss: 0.46847, SubsetAccuracy: 0.045045, RankingLoss: 0.43081, MacroPrecision: 0.40784, MacroRecall: 0.45465, MacroFOne: 0.42801,
pruning: True, include_original_features: no_org, averageAUROC: 0.550204, HammingLoss: 0.39099, SubsetAccuracy: 0.081081, RankingLoss: 0.39843, MacroPrecision: 0.50048, MacroRecall: 0.26176, MacroFOne: 0.33786,
pruning: False, include_original_features: no_org, averageAUROC: 0.5422755, HammingLoss: 0.42973, SubsetAccuracy: 0.045045, RankingLoss: 0.41489, MacroPrecision: 0.44999, MacroRecall: 0.45566, MacroFOne: 0.451,

Fold 2/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [07:06<00:00,  3.77feat/s]

XofN groups with 2 features: 9
XofN groups with 3 features: 12
XofN groups with 4 features: 9
XofN groups with 5 features: 296
pruning: True, include_original_features: with_org, averageAUROC: 0.6094481, HammingLoss: 0.34865, SubsetAccuracy: 0.14414, RankingLoss: 0.32097, MacroPrecision: 0.55268, MacroRecall: 0.25354, MacroFOne: 0.344,
pruning: False, include_original_features: with_org, averageAUROC: 0.5723209, HammingLoss: 0.40721, SubsetAccuracy: 0.072072, RankingLoss: 0.33874, MacroPrecision: 0.44802, MacroRecall: 0.43872, MacroFOne: 0.44113,
pruning: True, include_original_features: no_org, averageAUROC: 0.6174777, HammingLoss: 0.34324, SubsetAccuracy: 0.14414, RankingLoss: 0.32878, MacroPrecision: 0.60231, MacroRecall: 0.21097, MacroFOne: 0.3024,
pruning: False, include_original_features: no_org, averageAUROC: 0.5952367, HammingLoss: 0.38829, SubsetAccuracy: 0.099099, RankingLoss: 0.36371, MacroPrecision: 0.48332, MacroRecall: 0.45013, MacroFOne: 0.46387,

Fold 3/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [07:07<00:00,  3.76feat/s]

XofN groups with 2 features: 8
XofN groups with 3 features: 17
XofN groups with 4 features: 8
XofN groups with 5 features: 297
pruning: True, include_original_features: with_org, averageAUROC: 0.6344985, HammingLoss: 0.32432, SubsetAccuracy: 0.099099, RankingLoss: 0.37694, MacroPrecision: 0.6067, MacroRecall: 0.42604, MacroFOne: 0.4984,
pruning: False, include_original_features: with_org, averageAUROC: 0.5965111, HammingLoss: 0.40721, SubsetAccuracy: 0.045045, RankingLoss: 0.39662, MacroPrecision: 0.47412, MacroRecall: 0.53247, MacroFOne: 0.50005,
pruning: True, include_original_features: no_org, averageAUROC: 0.5936824, HammingLoss: 0.37207, SubsetAccuracy: 0.09009, RankingLoss: 0.40191, MacroPrecision: 0.51035, MacroRecall: 0.35464, MacroFOne: 0.41596,
pruning: False, include_original_features: no_org, averageAUROC: 0.5789763, HammingLoss: 0.42523, SubsetAccuracy: 0.036036, RankingLoss: 0.41785, MacroPrecision: 0.45533, MacroRecall: 0.53463, MacroFOne: 0.48985,

Fold 4/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [07:13<00:00,  3.71feat/s]

XofN groups with 2 features: 8
XofN groups with 3 features: 17
XofN groups with 4 features: 6
XofN groups with 5 features: 297
pruning: True, include_original_features: with_org, averageAUROC: 0.5701368, HammingLoss: 0.37568, SubsetAccuracy: 0.099099, RankingLoss: 0.37775, MacroPrecision: 0.47964, MacroRecall: 0.24302, MacroFOne: 0.32108,
pruning: False, include_original_features: with_org, averageAUROC: 0.6003242, HammingLoss: 0.4036, SubsetAccuracy: 0.045045, RankingLoss: 0.37641, MacroPrecision: 0.45778, MacroRecall: 0.49404, MacroFOne: 0.47394,
pruning: True, include_original_features: no_org, averageAUROC: 0.5902558, HammingLoss: 0.35225, SubsetAccuracy: 0.10811, RankingLoss: 0.37619, MacroPrecision: 0.54022, MacroRecall: 0.25206, MacroFOne: 0.33923,
pruning: False, include_original_features: no_org, averageAUROC: 0.6202876, HammingLoss: 0.3982, SubsetAccuracy: 0.063063, RankingLoss: 0.33816, MacroPrecision: 0.46297, MacroRecall: 0.54187, MacroFOne: 0.49705,

Fold 5/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [07:09<00:00,  3.74feat/s]

XofN groups with 2 features: 17
XofN groups with 3 features: 10
XofN groups with 4 features: 13
XofN groups with 5 features: 293
pruning: True, include_original_features: with_org, averageAUROC: 0.6124556, HammingLoss: 0.31081, SubsetAccuracy: 0.11712, RankingLoss: 0.32289, MacroPrecision: 0.4923, MacroRecall: 0.35253, MacroFOne: 0.40896,
pruning: False, include_original_features: with_org, averageAUROC: 0.571403, HammingLoss: 0.42523, SubsetAccuracy: 0.018018, RankingLoss: 0.3287, MacroPrecision: 0.37069, MacroRecall: 0.53747, MacroFOne: 0.43754,
pruning: True, include_original_features: no_org, averageAUROC: 0.5948016, HammingLoss: 0.30811, SubsetAccuracy: 0.11712, RankingLoss: 0.34337, MacroPrecision: 0.49618, MacroRecall: 0.30197, MacroFOne: 0.37128,
pruning: False, include_original_features: no_org, averageAUROC: 0.5455536, HammingLoss: 0.41982, SubsetAccuracy: 0.054054, RankingLoss: 0.32873, MacroPrecision: 0.37265, MacroRecall: 0.50301, MacroFOne: 0.4269,

Fold 6/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [07:07<00:00,  3.76feat/s]

XofN groups with 2 features: 14
XofN groups with 3 features: 12
XofN groups with 4 features: 5
XofN groups with 5 features: 299
pruning: True, include_original_features: with_org, averageAUROC: 0.5714052, HammingLoss: 0.38468, SubsetAccuracy: 0.072072, RankingLoss: 0.40482, MacroPrecision: 0.54912, MacroRecall: 0.24263, MacroFOne: 0.33106,
pruning: False, include_original_features: with_org, averageAUROC: 0.5767114, HammingLoss: 0.41712, SubsetAccuracy: 0.009009, RankingLoss: 0.36795, MacroPrecision: 0.48533, MacroRecall: 0.46619, MacroFOne: 0.47461,
pruning: True, include_original_features: no_org, averageAUROC: 0.59203, HammingLoss: 0.36577, SubsetAccuracy: 0.081081, RankingLoss: 0.39029, MacroPrecision: 0.62176, MacroRecall: 0.22131, MacroFOne: 0.32575,
pruning: False, include_original_features: no_org, averageAUROC: 0.5870204, HammingLoss: 0.41892, SubsetAccuracy: 0.045045, RankingLoss: 0.3844, MacroPrecision: 0.47888, MacroRecall: 0.49893, MacroFOne: 0.48704,

Fold 7/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [07:05<00:00,  3.78feat/s]

XofN groups with 2 features: 15
XofN groups with 3 features: 15
XofN groups with 4 features: 14
XofN groups with 5 features: 291
pruning: True, include_original_features: with_org, averageAUROC: 0.6085133, HammingLoss: 0.33874, SubsetAccuracy: 0.17117, RankingLoss: 0.31614, MacroPrecision: 0.44299, MacroRecall: 0.36355, MacroFOne: 0.39611,
pruning: False, include_original_features: with_org, averageAUROC: 0.6074184, HammingLoss: 0.4027, SubsetAccuracy: 0.081081, RankingLoss: 0.30346, MacroPrecision: 0.39291, MacroRecall: 0.55009, MacroFOne: 0.45637,
pruning: True, include_original_features: no_org, averageAUROC: 0.5943733, HammingLoss: 0.33694, SubsetAccuracy: 0.17117, RankingLoss: 0.31248, MacroPrecision: 0.4322, MacroRecall: 0.31204, MacroFOne: 0.35929,
pruning: False, include_original_features: no_org, averageAUROC: 0.5701317, HammingLoss: 0.43063, SubsetAccuracy: 0.027027, RankingLoss: 0.31091, MacroPrecision: 0.35266, MacroRecall: 0.48034, MacroFOne: 0.40497,

Fold 8/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [07:07<00:00,  3.76feat/s]

XofN groups with 2 features: 14
XofN groups with 3 features: 17
XofN groups with 4 features: 13
XofN groups with 5 features: 290
pruning: True, include_original_features: with_org, averageAUROC: 0.6106288, HammingLoss: 0.32909, SubsetAccuracy: 0.14545, RankingLoss: 0.35935, MacroPrecision: 0.57312, MacroRecall: 0.34448, MacroFOne: 0.42764,
pruning: False, include_original_features: with_org, averageAUROC: 0.5847655, HammingLoss: 0.42909, SubsetAccuracy: 0.0, RankingLoss: 0.34446, MacroPrecision: 0.42055, MacroRecall: 0.49391, MacroFOne: 0.45302,
pruning: True, include_original_features: no_org, averageAUROC: 0.6063414, HammingLoss: 0.33909, SubsetAccuracy: 0.14545, RankingLoss: 0.36053, MacroPrecision: 0.55009, MacroRecall: 0.32845, MacroFOne: 0.40977,
pruning: False, include_original_features: no_org, averageAUROC: 0.566619, HammingLoss: 0.42545, SubsetAccuracy: 0.018182, RankingLoss: 0.37682, MacroPrecision: 0.41997, MacroRecall: 0.4783, MacroFOne: 0.44602,

Fold 9/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [07:06<00:00,  3.77feat/s]

XofN groups with 2 features: 6
XofN groups with 3 features: 14
XofN groups with 4 features: 5
XofN groups with 5 features: 300
pruning: True, include_original_features: with_org, averageAUROC: 0.6025842, HammingLoss: 0.36, SubsetAccuracy: 0.10909, RankingLoss: 0.36033, MacroPrecision: 0.64785, MacroRecall: 0.35772, MacroFOne: 0.44126,
pruning: False, include_original_features: with_org, averageAUROC: 0.6022277, HammingLoss: 0.41273, SubsetAccuracy: 0.045455, RankingLoss: 0.32427, MacroPrecision: 0.50705, MacroRecall: 0.56274, MacroFOne: 0.53048,
pruning: True, include_original_features: no_org, averageAUROC: 0.584979, HammingLoss: 0.37727, SubsetAccuracy: 0.10909, RankingLoss: 0.3682, MacroPrecision: 0.60965, MacroRecall: 0.36178, MacroFOne: 0.43255,
pruning: False, include_original_features: no_org, averageAUROC: 0.5547555, HammingLoss: 0.44909, SubsetAccuracy: 0.054545, RankingLoss: 0.37029, MacroPrecision: 0.46793, MacroRecall: 0.50131, MacroFOne: 0.4818,

Fold 10/10 (CPI_ten_mid 2/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 1607/1607 [07:28<00:00,  3.58feat/s]

XofN groups with 2 features: 11
XofN groups with 3 features: 7
XofN groups with 4 features: 14
XofN groups with 5 features: 294
pruning: True, include_original_features: with_org, averageAUROC: 0.5678387, HammingLoss: 0.34727, SubsetAccuracy: 0.13636, RankingLoss: 0.37124, MacroPrecision: 0.47436, MacroRecall: 0.26537, MacroFOne: 0.33898,
pruning: False, include_original_features: with_org, averageAUROC: 0.6053329, HammingLoss: 0.37818, SubsetAccuracy: 0.054545, RankingLoss: 0.32372, MacroPrecision: 0.44344, MacroRecall: 0.45558, MacroFOne: 0.44693,
pruning: True, include_original_features: no_org, averageAUROC: 0.5698595, HammingLoss: 0.35182, SubsetAccuracy: 0.13636, RankingLoss: 0.37801, MacroPrecision: 0.45804, MacroRecall: 0.25111, MacroFOne: 0.31926,
pruning: False, include_original_features: no_org, averageAUROC: 0.5488443, HammingLoss: 0.40636, SubsetAccuracy: 0.036364, RankingLoss: 0.36503, MacroPrecision: 0.4085, MacroRecall: 0.42225, MacroFOne: 0.41272,
   pruning include_original_features      dataset  averageAUROC  HammingLoss  \
0    False                    no_org  CPI_ten_mid      0.570970     0.419172
1    False                  with_org  CPI_ten_mid      0.584062     0.415154
2     True                    no_org  CPI_ten_mid      0.589400     0.353755
3     True                  with_org  CPI_ten_mid      0.593718     0.351383

   SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  MacroFOne  nodes  \
0        0.047846     0.367079        0.435220     0.486643   0.456122  773.6
1        0.041531     0.353514        0.440773     0.498586   0.464208  801.8
2        0.118369     0.365819        0.532128     0.285609   0.361335   61.0
3        0.115666     0.360931        0.529604     0.313409   0.385733   78.4

   leaves  groups  avg_group_features  gen_XofN_time  training_time
0   387.3   329.6            4.787968     429.850277       0.896050
1   401.4   329.6            4.787968     429.850277       2.680915
2    31.0   329.6            4.787968     429.850277       0.896050
3    39.7   329.6            4.787968     429.850277       2.680915

--- Running with label:'['se_C0009676', 'se_C0041657', 'se_C0002994', 'se_C0042571', 'se_C0004604', 'se_C0041834', 'se_C0085631', 'se_C0040822', 'se_C0042373', 'se_C0021053']' training_algorithm:'Variance Reduction' eval_criterion:'['averageAUROC', 'HammingLoss', 'SubsetAccuracy', 'RankingLoss', 'MacroPrecision', 'MacroRecall', 'MacroFOne']' max_size:'5' ---
Logs can be found in XofN_filter/logs/fingerprint_ten_mid_Variance Reduction_averageAUROC_HammingLoss_SubsetAccuracy_RankingLoss_MacroPrecision_MacroRecall_MacroFOne_5_logs.txt.

Fold 1/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:35<00:00,  5.66feat/s]

XofN groups with 2 features: 2
XofN groups with 3 features: 3
XofN groups with 4 features: 3
XofN groups with 5 features: 103
pruning: True, include_original_features: with_org, averageAUROC: 0.5582446, HammingLoss: 0.36212, SubsetAccuracy: 0.083333, RankingLoss: 0.33762, MacroPrecision: 0.48213, MacroRecall: 0.27172, MacroFOne: 0.34295,
pruning: False, include_original_features: with_org, averageAUROC: 0.5876292, HammingLoss: 0.40152, SubsetAccuracy: 0.030303, RankingLoss: 0.34434, MacroPrecision: 0.44742, MacroRecall: 0.51918, MacroFOne: 0.47902,
pruning: True, include_original_features: no_org, averageAUROC: 0.551572, HammingLoss: 0.36894, SubsetAccuracy: 0.10606, RankingLoss: 0.34748, MacroPrecision: 0.44726, MacroRecall: 0.17563, MacroFOne: 0.24681,
pruning: False, include_original_features: no_org, averageAUROC: 0.5504562, HammingLoss: 0.43788, SubsetAccuracy: 0.037879, RankingLoss: 0.36948, MacroPrecision: 0.40452, MacroRecall: 0.47601, MacroFOne: 0.43648,

Fold 2/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:35<00:00,  5.63feat/s]

XofN groups with 2 features: 1
XofN groups with 3 features: 3
XofN groups with 4 features: 3
XofN groups with 5 features: 103
pruning: True, include_original_features: with_org, averageAUROC: 0.5897694, HammingLoss: 0.34351, SubsetAccuracy: 0.091603, RankingLoss: 0.33829, MacroPrecision: 0.52761, MacroRecall: 0.24943, MacroFOne: 0.33297,
pruning: False, include_original_features: with_org, averageAUROC: 0.5580798, HammingLoss: 0.41069, SubsetAccuracy: 0.053435, RankingLoss: 0.353, MacroPrecision: 0.42635, MacroRecall: 0.45233, MacroFOne: 0.43492,
pruning: True, include_original_features: no_org, averageAUROC: 0.559346, HammingLoss: 0.36489, SubsetAccuracy: 0.076336, RankingLoss: 0.33698, MacroPrecision: 0.45262, MacroRecall: 0.213, MacroFOne: 0.28236,
pruning: False, include_original_features: no_org, averageAUROC: 0.5322064, HammingLoss: 0.44504, SubsetAccuracy: 0.045802, RankingLoss: 0.36336, MacroPrecision: 0.38879, MacroRecall: 0.44305, MacroFOne: 0.4121,

Fold 3/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:36<00:00,  5.62feat/s]

XofN groups with 2 features: 2
XofN groups with 3 features: 2
XofN groups with 4 features: 3
XofN groups with 5 features: 103
pruning: True, include_original_features: with_org, averageAUROC: 0.5488631, HammingLoss: 0.37557, SubsetAccuracy: 0.12214, RankingLoss: 0.35152, MacroPrecision: 0.42646, MacroRecall: 0.21104, MacroFOne: 0.27531,
pruning: False, include_original_features: with_org, averageAUROC: 0.5585127, HammingLoss: 0.44198, SubsetAccuracy: 0.022901, RankingLoss: 0.34365, MacroPrecision: 0.39222, MacroRecall: 0.50321, MacroFOne: 0.4401,
pruning: True, include_original_features: no_org, averageAUROC: 0.5424769, HammingLoss: 0.3771, SubsetAccuracy: 0.12977, RankingLoss: 0.35697, MacroPrecision: 0.42923, MacroRecall: 0.2429, MacroFOne: 0.30461,
pruning: False, include_original_features: no_org, averageAUROC: 0.5630586, HammingLoss: 0.42901, SubsetAccuracy: 0.030534, RankingLoss: 0.36352, MacroPrecision: 0.40237, MacroRecall: 0.50548, MacroFOne: 0.44729,

Fold 4/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:36<00:00,  5.61feat/s]

XofN groups with 2 features: 3
XofN groups with 3 features: 4
XofN groups with 4 features: 4
XofN groups with 5 features: 101
pruning: True, include_original_features: with_org, averageAUROC: 0.5663915, HammingLoss: 0.33893, SubsetAccuracy: 0.12977, RankingLoss: 0.366, MacroPrecision: 0.39838, MacroRecall: 0.28929, MacroFOne: 0.3328,
pruning: False, include_original_features: with_org, averageAUROC: 0.5297938, HammingLoss: 0.44122, SubsetAccuracy: 0.038168, RankingLoss: 0.36419, MacroPrecision: 0.33262, MacroRecall: 0.47214, MacroFOne: 0.38739,
pruning: True, include_original_features: no_org, averageAUROC: 0.5568748, HammingLoss: 0.3145, SubsetAccuracy: 0.14504, RankingLoss: 0.38368, MacroPrecision: 0.44343, MacroRecall: 0.19861, MacroFOne: 0.27049,
pruning: False, include_original_features: no_org, averageAUROC: 0.5659433, HammingLoss: 0.41527, SubsetAccuracy: 0.030534, RankingLoss: 0.38209, MacroPrecision: 0.36921, MacroRecall: 0.53954, MacroFOne: 0.43711,

Fold 5/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:36<00:00,  5.61feat/s]

XofN groups with 2 features: 1
XofN groups with 3 features: 4
XofN groups with 4 features: 5
XofN groups with 5 features: 101
pruning: True, include_original_features: with_org, averageAUROC: 0.6317831, HammingLoss: 0.35115, SubsetAccuracy: 0.091603, RankingLoss: 0.32666, MacroPrecision: 0.56832, MacroRecall: 0.2979, MacroFOne: 0.38631,
pruning: False, include_original_features: with_org, averageAUROC: 0.6042633, HammingLoss: 0.40076, SubsetAccuracy: 0.068702, RankingLoss: 0.34644, MacroPrecision: 0.46845, MacroRecall: 0.47637, MacroFOne: 0.47097,
pruning: True, include_original_features: no_org, averageAUROC: 0.5710305, HammingLoss: 0.36565, SubsetAccuracy: 0.1145, RankingLoss: 0.36129, MacroPrecision: 0.52643, MacroRecall: 0.2308, MacroFOne: 0.31612,
pruning: False, include_original_features: no_org, averageAUROC: 0.6107579, HammingLoss: 0.39771, SubsetAccuracy: 0.099237, RankingLoss: 0.358, MacroPrecision: 0.4732, MacroRecall: 0.50429, MacroFOne: 0.48705,

Fold 6/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:36<00:00,  5.61feat/s]

XofN groups with 2 features: 2
XofN groups with 3 features: 3
XofN groups with 4 features: 4
XofN groups with 5 features: 102
pruning: True, include_original_features: with_org, averageAUROC: 0.5638783, HammingLoss: 0.36794, SubsetAccuracy: 0.12214, RankingLoss: 0.33478, MacroPrecision: 0.37708, MacroRecall: 0.2582, MacroFOne: 0.30271,
pruning: False, include_original_features: with_org, averageAUROC: 0.582498, HammingLoss: 0.42519, SubsetAccuracy: 0.038168, RankingLoss: 0.32386, MacroPrecision: 0.37473, MacroRecall: 0.56363, MacroFOne: 0.44876,
pruning: True, include_original_features: no_org, averageAUROC: 0.5598041, HammingLoss: 0.36641, SubsetAccuracy: 0.1374, RankingLoss: 0.33457, MacroPrecision: 0.35627, MacroRecall: 0.23085, MacroFOne: 0.27729,
pruning: False, include_original_features: no_org, averageAUROC: 0.5413714, HammingLoss: 0.43511, SubsetAccuracy: 0.038168, RankingLoss: 0.32915, MacroPrecision: 0.3466, MacroRecall: 0.46883, MacroFOne: 0.39714,

Fold 7/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:35<00:00,  5.63feat/s]

XofN groups with 2 features: 2
XofN groups with 3 features: 1
XofN groups with 4 features: 3
XofN groups with 5 features: 104
pruning: True, include_original_features: with_org, averageAUROC: 0.5723029, HammingLoss: 0.35725, SubsetAccuracy: 0.12214, RankingLoss: 0.3514, MacroPrecision: 0.52679, MacroRecall: 0.19999, MacroFOne: 0.28697,
pruning: False, include_original_features: with_org, averageAUROC: 0.5599565, HammingLoss: 0.42366, SubsetAccuracy: 0.053435, RankingLoss: 0.35386, MacroPrecision: 0.41616, MacroRecall: 0.45124, MacroFOne: 0.43145,
pruning: True, include_original_features: no_org, averageAUROC: 0.5592081, HammingLoss: 0.37405, SubsetAccuracy: 0.12977, RankingLoss: 0.3576, MacroPrecision: 0.4803, MacroRecall: 0.24151, MacroFOne: 0.31326,
pruning: False, include_original_features: no_org, averageAUROC: 0.5628314, HammingLoss: 0.42595, SubsetAccuracy: 0.030534, RankingLoss: 0.35897, MacroPrecision: 0.41439, MacroRecall: 0.45084, MacroFOne: 0.42934,

Fold 8/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:36<00:00,  5.60feat/s]

XofN groups with 2 features: 3
XofN groups with 3 features: 4
XofN groups with 4 features: 4
XofN groups with 5 features: 101
pruning: True, include_original_features: with_org, averageAUROC: 0.5804445, HammingLoss: 0.33893, SubsetAccuracy: 0.1374, RankingLoss: 0.32782, MacroPrecision: 0.46641, MacroRecall: 0.28607, MacroFOne: 0.35207,
pruning: False, include_original_features: with_org, averageAUROC: 0.5745698, HammingLoss: 0.42672, SubsetAccuracy: 0.045802, RankingLoss: 0.34089, MacroPrecision: 0.38391, MacroRecall: 0.50355, MacroFOne: 0.43433,
pruning: True, include_original_features: no_org, averageAUROC: 0.5920313, HammingLoss: 0.35267, SubsetAccuracy: 0.14504, RankingLoss: 0.33647, MacroPrecision: 0.4596, MacroRecall: 0.38231, MacroFOne: 0.41516,
pruning: False, include_original_features: no_org, averageAUROC: 0.5922055, HammingLoss: 0.43206, SubsetAccuracy: 0.061069, RankingLoss: 0.31854, MacroPrecision: 0.39098, MacroRecall: 0.55487, MacroFOne: 0.45719,

Fold 9/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:35<00:00,  5.64feat/s]

XofN groups with 2 features: 2
XofN groups with 3 features: 3
XofN groups with 4 features: 1
XofN groups with 5 features: 104
pruning: True, include_original_features: with_org, averageAUROC: 0.5666192, HammingLoss: 0.37786, SubsetAccuracy: 0.1145, RankingLoss: 0.33035, MacroPrecision: 0.43078, MacroRecall: 0.24859, MacroFOne: 0.30874,
pruning: False, include_original_features: with_org, averageAUROC: 0.5877531, HammingLoss: 0.41603, SubsetAccuracy: 0.038168, RankingLoss: 0.35275, MacroPrecision: 0.43493, MacroRecall: 0.51552, MacroFOne: 0.46769,
pruning: True, include_original_features: no_org, averageAUROC: 0.5448063, HammingLoss: 0.3916, SubsetAccuracy: 0.10687, RankingLoss: 0.35997, MacroPrecision: 0.4182, MacroRecall: 0.23596, MacroFOne: 0.29944,
pruning: False, include_original_features: no_org, averageAUROC: 0.5496489, HammingLoss: 0.44809, SubsetAccuracy: 0.038168, RankingLoss: 0.385, MacroPrecision: 0.39125, MacroRecall: 0.45681, MacroFOne: 0.41952,

Fold 10/10 (fingerprint_ten_mid 3/3)

generate_XofN_list -> Generating groupings based on variance reduction:variance reduction.

🔄 Processing features: 100%|██████████| 540/540 [01:36<00:00,  5.62feat/s]

XofN groups with 3 features: 7
XofN groups with 4 features: 3
XofN groups with 5 features: 101
pruning: True, include_original_features: with_org, averageAUROC: 0.5576617, HammingLoss: 0.38244, SubsetAccuracy: 0.12977, RankingLoss: 0.3433, MacroPrecision: 0.53388, MacroRecall: 0.19998, MacroFOne: 0.28738,
pruning: False, include_original_features: with_org, averageAUROC: 0.5890007, HammingLoss: 0.40534, SubsetAccuracy: 0.068702, RankingLoss: 0.33757, MacroPrecision: 0.48637, MacroRecall: 0.47317, MacroFOne: 0.4785,
pruning: True, include_original_features: no_org, averageAUROC: 0.5507356, HammingLoss: 0.38855, SubsetAccuracy: 0.14504, RankingLoss: 0.35128, MacroPrecision: 0.52155, MacroRecall: 0.18102, MacroFOne: 0.26547,
pruning: False, include_original_features: no_org, averageAUROC: 0.5664737, HammingLoss: 0.43817, SubsetAccuracy: 0.068702, RankingLoss: 0.33784, MacroPrecision: 0.44796, MacroRecall: 0.48986, MacroFOne: 0.46717,
   pruning include_original_features              dataset  averageAUROC  \
0    False                    no_org  fingerprint_ten_mid      0.563495
1    False                  with_org  fingerprint_ten_mid      0.573206
2     True                    no_org  fingerprint_ten_mid      0.558789
3     True                  with_org  fingerprint_ten_mid      0.573596

   HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
0     0.430429        0.048063     0.356595        0.402927     0.488958
1     0.419311        0.045778     0.346055        0.416316     0.493034
2     0.366436        0.123583     0.352629        0.453489     0.233259
3     0.359570        0.114440     0.340774        0.473784     0.251221

   MacroFOne  nodes  leaves  groups  avg_group_features  gen_XofN_time  \
0   0.439039  980.2   490.6   110.8            4.860297      96.060877
1   0.447313  981.8   491.4   110.8            4.860297      96.060877
2   0.299101   89.4    45.2   110.8            4.860297      96.060877
3   0.320821   95.6    48.3   110.8            4.860297      96.060877

   training_time
0       0.700176
1       1.349122
2       0.700176
3       1.349122

In [5]:
# All results
save_path = "XofN_filter/"
final_grouped_res = pd.DataFrame()
for df in cv_results:
    final_grouped_res = pd.concat([final_grouped_res, df])
final_grouped_res.sort_values(by='dataset', ascending=False, inplace=True)
final_grouped_res = final_grouped_res.reset_index(drop=True)
final_grouped_res.to_csv(save_path + "all_results.csv")
final_grouped_res

,pruning,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,RankingLoss,MacroPrecision,MacroRecall,MacroFOne,nodes,leaves,groups,avg_group_features,gen_XofN_time,training_time
0,False,no_org,fingerprint_ten_mid,0.563495,0.430429,0.048063,0.356595,0.402927,0.488958,0.439039,980.2,490.6,110.8,4.860297,96.060877,0.700176
1,False,with_org,fingerprint_ten_mid,0.573206,0.419311,0.045778,0.346055,0.416316,0.493034,0.447313,981.8,491.4,110.8,4.860297,96.060877,1.349122
2,True,no_org,fingerprint_ten_mid,0.558789,0.366436,0.123583,0.352629,0.453489,0.233259,0.299101,89.4,45.2,110.8,4.860297,96.060877,0.700176
3,True,with_org,fingerprint_ten_mid,0.573596,0.359570,0.114440,0.340774,0.473784,0.251221,0.320821,95.6,48.3,110.8,4.860297,96.060877,1.349122
4,False,no_org,CPI_ten_mid,0.570970,0.419172,0.047846,0.367079,0.435220,0.486643,0.456122,773.6,387.3,329.6,4.787968,429.850277,0.896050
5,False,with_org,CPI_ten_mid,0.584062,0.415154,0.041531,0.353514,0.440773,0.498586,0.464208,801.8,401.4,329.6,4.787968,429.850277,2.680915
6,True,no_org,CPI_ten_mid,0.589400,0.353755,0.118369,0.365819,0.532128,0.285609,0.361335,61.0,31.0,329.6,4.787968,429.850277,0.896050
7,True,with_org,CPI_ten_mid,0.593718,0.351383,0.115666,0.360931,0.529604,0.313409,0.385733,78.4,39.7,329.6,4.787968,429.850277,2.680915
8,False,no_org,CPI+fingerprint_ten_mid,0.577341,0.408734,0.047597,0.347622,0.424922,0.493686,0.454009,1022.8,511.9,438.4,4.828520,697.756258,1.222673
9,False,with_org,CPI+fingerprint_ten_mid,0.578968,0.404366,0.051913,0.351211,0.427563,0.477883,0.448103,1019.6,510.3,438.4,4.828520,697.756258,3.740729
10,True,no_org,CPI+fingerprint_ten_mid,0.593178,0.338368,0.131317,0.346370,0.525230,0.267306,0.348675,82.2,41.6,438.4,4.828520,697.756258,1.222673
11,True,with_org,CPI+fingerprint_ten_mid,0.601948,0.342976,0.132052,0.345569,0.510064,0.285556,0.360399,96.2,48.6,438.4,4.828520,697.756258,3.740729

In [6]:
# Table ready (with pruning, rounded, compact)
save_path = "XofN_filter/"
rounded_final_grouped_res = pd.read_csv(save_path + "all_results.csv", index_col=0)
res = pd.read_csv(save_path + "all_results.csv", index_col=0)
table_results = get_table_results(res, eval_criteria, get_dataset_paths())
table_results.to_csv(save_path + "table_results.csv")
table_results

,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,RankingLoss,MacroPrecision,MacroRecall,MacroFOne,Nodes; Leaves,#XofN; #Feat/XofN,# Ung. Feats,XofN time (s); PCT tr. time (s)
2,no_org,fingerprint_ten_mid,0.559,0.366,0.124,0.353,0.453,0.233,0.299,89.4; 45.2,110.8; 4.9,1.479105,96.1; 0.7
3,with_org,fingerprint_ten_mid,0.574,0.360,0.114,0.341,0.474,0.251,0.321,95.6; 48.3,110.8; 4.9,1.479105,96.1; 1.3
6,no_org,CPI_ten_mid,0.589,0.354,0.118,0.366,0.532,0.286,0.361,61.0; 31.0,329.6; 4.8,28.885798,429.9; 0.9
7,with_org,CPI_ten_mid,0.594,0.351,0.116,0.361,0.530,0.313,0.386,78.4; 39.7,329.6; 4.8,28.885798,429.9; 2.7
10,no_org,CPI+fingerprint_ten_mid,0.593,0.338,0.131,0.346,0.525,0.267,0.349,82.2; 41.6,438.4; 4.8,30.176840,697.8; 1.2
11,with_org,CPI+fingerprint_ten_mid,0.602,0.343,0.132,0.346,0.510,0.286,0.360,96.2; 48.6,438.4; 4.8,30.176840,697.8; 3.7