In [1]:
import sys, os

sys.path.insert(0, os.path.abspath("C:/Users/Voror/Projects/Personal/sep"))

from sklearn.model_selection import KFold
from SIDER_dataset.libraries.XofN_library import *
from SIDER_dataset.libraries.PCT_library import run_PCT, save_to_arff
from SIDER_dataset.libraries.utils import *
import json
from collections import Counter
import re

%load_ext autoreload
%autoreload 2

In [2]:
# Set ADR to predict and scoring
clus_path = get_clus_path()
paths = get_dataset_paths()
print(len(paths), "datasets")
paths

18 datasets

[{'dataset_path': 'C:\\Users\\Voror\\Projects\\Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/CPI+fingerprint_cardiac.csv',
  'dataset_name': 'CPI+fingerprint_cardiac',
  'label_set': ['se_C0016382',
   'se_C0018799',
   'se_C0003811',
   'se_C0428977',
   'se_C0027051',
   'se_C0018790'],
  'features': 2147,
  'original_features': ['cpi_9606.ENSP00000000442',
   'cpi_9606.ENSP00000001008',
   'cpi_9606.ENSP00000003084',
   'cpi_9606.ENSP00000003100',
   'cpi_9606.ENSP00000005178',
   'cpi_9606.ENSP00000011292',
   'cpi_9606.ENSP00000011653',
   'cpi_9606.ENSP00000012443',
   'cpi_9606.ENSP00000013034',
   'cpi_9606.ENSP00000014930',
   'cpi_9606.ENSP00000019103',
   'cpi_9606.ENSP00000023897',
   'cpi_9606.ENSP00000039007',
   'cpi_9606.ENSP00000044462',
   'cpi_9606.ENSP00000054668',
   'cpi_9606.ENSP00000078429',
   'cpi_9606.ENSP00000155840',
   'cpi_9606.ENSP00000164139',
   'cpi_9606.ENSP00000171757',
   'cpi_9606.ENSP00000176183',
   'cpi_9606.ENSP00000176195',
   'cpi_9606.ENSP00000176763',
   'cpi_9606.ENSP00000178638',
   'cpi_9606.ENSP00000181383',
   'cpi_9606.ENSP00000196551',
   'cpi_9606.ENSP00000199280',
   'cpi_9606.ENSP00000200676',
   'cpi_9606.ENSP00000206249',
   'cpi_9606.ENSP00000211122',
   'cpi_9606.ENSP00000211287',
   'cpi_9606.ENSP00000212015',
   'cpi_9606.ENSP00000215659',
   'cpi_9606.ENSP00000215832',
   'cpi_9606.ENSP00000215904',
   'cpi_9606.ENSP00000215956',
   'cpi_9606.ENSP00000216024',
   'cpi_9606.ENSP00000216037',
   'cpi_9606.ENSP00000216117',
   'cpi_9606.ENSP00000216185',
   'cpi_9606.ENSP00000216341',
   'cpi_9606.ENSP00000216392',
   'cpi_9606.ENSP00000216410',
   'cpi_9606.ENSP00000216455',
   'cpi_9606.ENSP00000216465',
   'cpi_9606.ENSP00000216540',
   'cpi_9606.ENSP00000216629',
   'cpi_9606.ENSP00000216714',
   'cpi_9606.ENSP00000216797',
   'cpi_9606.ENSP00000216862',
   'cpi_9606.ENSP00000216911',
   'cpi_9606.ENSP00000216962',
   'cpi_9606.ENSP00000217133',
   'cpi_9606.ENSP00000217244',
   'cpi_9606.ENSP00000217270',
   'cpi_9606.ENSP00000217305',
   'cpi_9606.ENSP00000217386',
   'cpi_9606.ENSP00000217426',
   'cpi_9606.ENSP00000217961',
   'cpi_9606.ENSP00000218099',
   'cpi_9606.ENSP00000218388',
   'cpi_9606.ENSP00000218548',
   'cpi_9606.ENSP00000218721',
   'cpi_9606.ENSP00000218758',
   'cpi_9606.ENSP00000219070',
   'cpi_9606.ENSP00000219240',
   'cpi_9606.ENSP00000219252',
   'cpi_9606.ENSP00000219700',
   'cpi_9606.ENSP00000219794',
   'cpi_9606.ENSP00000219833',
   'cpi_9606.ENSP00000219919',
   'cpi_9606.ENSP00000220003',
   'cpi_9606.ENSP00000220616',
   'cpi_9606.ENSP00000220764',
   'cpi_9606.ENSP00000220809',
   'cpi_9606.ENSP00000221130',
   'cpi_9606.ENSP00000221138',
   'cpi_9606.ENSP00000221421',
   'cpi_9606.ENSP00000221515',
   'cpi_9606.ENSP00000221930',
   'cpi_9606.ENSP00000221972',
   'cpi_9606.ENSP00000222002',
   'cpi_9606.ENSP00000222256',
   'cpi_9606.ENSP00000222330',
   'cpi_9606.ENSP00000222381',
   'cpi_9606.ENSP00000222390',
   'cpi_9606.ENSP00000222481',
   'cpi_9606.ENSP00000222482',
   'cpi_9606.ENSP00000222553',
   'cpi_9606.ENSP00000222982',
   'cpi_9606.ENSP00000223095',
   'cpi_9606.ENSP00000223366',
   'cpi_9606.ENSP00000223642',
   'cpi_9606.ENSP00000224784',
   'cpi_9606.ENSP00000225275',
   'cpi_9606.ENSP00000225371',
   'cpi_9606.ENSP00000225426',
   'cpi_9606.ENSP00000225430',
   'cpi_9606.ENSP00000225474',
   'cpi_9606.ENSP00000225577',
   'cpi_9606.ENSP00000225740',
   'cpi_9606.ENSP00000225831',
   'cpi_9606.ENSP00000225927',
   'cpi_9606.ENSP00000225964',
   'cpi_9606.ENSP00000225992',
   'cpi_9606.ENSP00000226299',
   'cpi_9606.ENSP00000226317',
   'cpi_9606.ENSP00000226413',
   'cpi_9606.ENSP00000226444',
   'cpi_9606.ENSP00000226574',
   'cpi_9606.ENSP00000226578',
   'cpi_9606.ENSP00000226730',
   'cpi_9606.ENSP00000226840',
   'cpi_9606.ENSP00000227378',
   'cpi_9606.ENSP00000227507',
   'cpi_9606.ENSP00000227758',
   'cpi_9606.ENSP00000228476',
   'cpi_9606.ENSP00000228740',
   'cpi_9606.ENSP00000228872',
   'cpi_9606.ENSP00000229135',
   'cpi_9606.ENSP00000229239',
   'cpi_9606.ENSP00000229264',
   'cpi_9606.ENSP00000229270',
   'cpi_9606.ENSP00000229277',
   'cpi_9606.ENSP00000229319',
   'cpi_9606.ENSP00000229447',
   'cpi_9606.ENSP00000229794',
   'cpi_9606.ENSP00000230050',
   'cpi_9606.ENSP00000230671',
   'cpi_9606.ENSP00000231188',
   'cpi_9606.ENSP00000231228',
   'cpi_9606.ENSP00000231449',
   'cpi_9606.ENSP00000231454',
   'cpi_9606.ENSP00000231509',
   'cpi_9606.ENSP00000231751',
   'cpi_9606.ENSP00000231790',
   'cpi_9606.ENSP00000232219',
   'cpi_9606.ENSP00000232607',
   'cpi_9606.ENSP00000232892',
   'cpi_9606.ENSP00000233146',
   'cpi_9606.ENSP00000233242',
   'cpi_9606.ENSP00000233944',
   'cpi_9606.ENSP00000234071',
   'cpi_9606.ENSP00000234111',
   'cpi_9606.ENSP00000234310',
   'cpi_9606.ENSP00000234371',
   'cpi_9606.ENSP00000234389',
   'cpi_9606.ENSP00000234590',
   'cpi_9606.ENSP00000234961',
   'cpi_9606.ENSP00000235382',
   'cpi_9606.ENSP00000236671',
   'cpi_9606.ENSP00000236850',
   'cpi_9606.ENSP00000237014',
   'cpi_9606.ENSP00000237527',
   'cpi_9606.ENSP00000237612',
   'cpi_9606.ENSP00000237858',
   'cpi_9606.ENSP00000238018',
   'cpi_9606.ENSP00000238379',
   'cpi_9606.ENSP00000239223',
   'cpi_9606.ENSP00000239849',
   'cpi_9606.ENSP00000239938',
   'cpi_9606.ENSP00000240139',
   'cpi_9606.ENSP00000240615',
   'cpi_9606.ENSP00000240619',
   'cpi_9606.ENSP00000240652',
   'cpi_9606.ENSP00000240687',
   'cpi_9606.ENSP00000240691',
   'cpi_9606.ENSP00000240874',
   'cpi_9606.ENSP00000241052',
   'cpi_9606.ENSP00000241256',
   'cpi_9606.ENSP00000241261',
   'cpi_9606.ENSP00000241453',
   'cpi_9606.ENSP00000241600',
   'cpi_9606.ENSP00000242057',
   'cpi_9606.ENSP00000242152',
   'cpi_9606.ENSP00000242375',
   'cpi_9606.ENSP00000242839',
   'cpi_9606.ENSP00000243167',
   'cpi_9606.ENSP00000243911',
   'cpi_9606.ENSP00000244051',
   'cpi_9606.ENSP00000244137',
   'cpi_9606.ENSP00000244217',
   'cpi_9606.ENSP00000244289',
   'cpi_9606.ENSP00000244741',
   'cpi_9606.ENSP00000245206',
   'cpi_9606.ENSP00000245457',
   'cpi_9606.ENSP00000245539',
   'cpi_9606.ENSP00000245907',
   'cpi_9606.ENSP00000245983',
   'cpi_9606.ENSP00000246115',
   'cpi_9606.ENSP00000246337',
   'cpi_9606.ENSP00000246549',
   'cpi_9606.ENSP00000246553',
   'cpi_9606.ENSP00000246657',
   'cpi_9606.ENSP00000247879',
   'cpi_9606.ENSP00000247881',
   'cpi_9606.ENSP00000247883',
   'cpi_9606.ENSP00000248041',
   'cpi_9606.ENSP00000248076',
   'cpi_9606.ENSP00000248437',
   'cpi_9606.ENSP00000248553',
   'cpi_9606.ENSP00000248572',
   'cpi_9606.ENSP00000248923',
   'cpi_9606.ENSP00000248935',
   'cpi_9606.ENSP00000249016',
   'cpi_9606.ENSP00000249041',
   'cpi_9606.ENSP00000249284',
   'cpi_9606.ENSP00000249750',
   'cpi_9606.ENSP00000250378',
   'cpi_9606.ENSP00000250615',
   'cpi_9606.ENSP00000250971',
   'cpi_9606.ENSP00000251453',
   'cpi_9606.ENSP00000251535',
   'cpi_9606.ENSP00000251566',
   'cpi_9606.ENSP00000251595',
   'cpi_9606.ENSP00000251810',
   'cpi_9606.ENSP00000251849',
   'cpi_9606.ENSP00000252029',
   'cpi_9606.ENSP00000252321',
   'cpi_9606.ENSP00000252486',
   'cpi_9606.ENSP00000252519',
   'cpi_9606.ENSP00000252723',
   'cpi_9606.ENSP00000252804',
   'cpi_9606.ENSP00000252809',
   'cpi_9606.ENSP00000252945',
   'cpi_9606.ENSP00000253004',
   'cpi_9606.ENSP00000253099',
   'cpi_9606.ENSP00000253122',
   'cpi_9606.ENSP00000253303',
   'cpi_9606.ENSP00000253727',
   'cpi_9606.ENSP00000253792',
   'cpi_9606.ENSP00000253799',
   'cpi_9606.ENSP00000254066',
   'cpi_9606.ENSP00000254079',
   'cpi_9606.ENSP00000254227',
   'cpi_9606.ENSP00000254235',
   'cpi_9606.ENSP00000254488',
   'cpi_9606.ENSP00000254810',
   'cpi_9606.ENSP00000254976',
   'cpi_9606.ENSP00000255008',
   'cpi_9606.ENSP00000255030',
   'cpi_9606.ENSP00000255084',
   'cpi_9606.ENSP00000255262',
   'cpi_9606.ENSP00000255380',
   'cpi_9606.ENSP00000255409',
   'cpi_9606.ENSP00000255465',
   'cpi_9606.ENSP00000256010',
   'cpi_9606.ENSP00000256078',
   'cpi_9606.ENSP00000256104',
   'cpi_9606.ENSP00000256119',
   'cpi_9606.ENSP00000256383',
   'cpi_9606.ENSP00000256442',
   'cpi_9606.ENSP00000256578',
   'cpi_9606.ENSP00000256722',
   'cpi_9606.ENSP00000256857',
   'cpi_9606.ENSP00000256906',
   'cpi_9606.ENSP00000256958',
   'cpi_9606.ENSP00000256999',
   'cpi_9606.ENSP00000257068',
   'cpi_9606.ENSP00000257254',
   'cpi_9606.ENSP00000257290',
   'cpi_9606.ENSP00000257497',
   'cpi_9606.ENSP00000257770',
   'cpi_9606.ENSP00000258042',
   'cpi_9606.ENSP00000258317',
   'cpi_9606.ENSP00000258400',
   'cpi_9606.ENSP00000258662',
   'cpi_9606.ENSP00000258743',
   'cpi_9606.ENSP00000258749',
   'cpi_9606.ENSP00000259089',
   'cpi_9606.ENSP00000259271',
   'cpi_9606.ENSP00000259396',
   'cpi_9606.ENSP00000259457',
   'cpi_9606.ENSP00000259469',
   'cpi_9606.ENSP00000259486',
   'cpi_9606.ENSP00000259607',
   'cpi_9606.ENSP00000259631',
   'cpi_9606.ENSP00000259667',
   'cpi_9606.ENSP00000259818',
   'cpi_9606.ENSP00000260010',
   'cpi_9606.ENSP00000260102',
   'cpi_9606.ENSP00000260191',
   'cpi_9606.ENSP00000260227',
   'cpi_9606.ENSP00000260302',
   'cpi_9606.ENSP00000260356',
   'cpi_9606.ENSP00000260402',
   'cpi_9606.ENSP00000260433',
   'cpi_9606.ENSP00000260443',
   'cpi_9606.ENSP00000260600',
   'cpi_9606.ENSP00000260630',
   'cpi_9606.ENSP00000260649',
   'cpi_9606.ENSP00000260682',
   'cpi_9606.ENSP00000260970',
   'cpi_9606.ENSP00000261196',
   'cpi_9606.ENSP00000261205',
   'cpi_9606.ENSP00000261267',
   'cpi_9606.ENSP00000261386',
   'cpi_9606.ENSP00000261405',
   'cpi_9606.ENSP00000261416',
   'cpi_9606.ENSP00000261465',
   'cpi_9606.ENSP00000261479',
   'cpi_9606.ENSP00000261693',
   'cpi_9606.ENSP00000261707',
   'cpi_9606.ENSP00000261733',
   'cpi_9606.ENSP00000261755',
   'cpi_9606.ENSP00000261769',
   'cpi_9606.ENSP00000261799',
   'cpi_9606.ENSP00000261835',
   'cpi_9606.ENSP00000261937',
   'cpi_9606.ENSP00000262017',
   'cpi_9606.ENSP00000262027',
   'cpi_9606.ENSP00000262160',
   'cpi_9606.ENSP00000262178',
   'cpi_9606.ENSP00000262186',
   'cpi_9606.ENSP00000262187',
   'cpi_9606.ENSP00000262193',
   'cpi_9606.ENSP00000262290',
   'cpi_9606.ENSP00000262352',
   'cpi_9606.ENSP00000262367',
   'cpi_9606.ENSP00000262407',
   'cpi_9606.ENSP00000262441',
   'cpi_9606.ENSP00000262461',
   'cpi_9606.ENSP00000262545',
   'cpi_9606.ENSP00000262584',
   'cpi_9606.ENSP00000262623',
   'cpi_9606.ENSP00000262735',
   'cpi_9606.ENSP00000262848',
   'cpi_9606.ENSP00000262888',
   'cpi_9606.ENSP00000262948',
   'cpi_9606.ENSP00000262958',
   'cpi_9606.ENSP00000262999',
   'cpi_9606.ENSP00000263025',
   'cpi_9606.ENSP00000263088',
   'cpi_9606.ENSP00000263126',
   'cpi_9606.ENSP00000263212',
   'cpi_9606.ENSP00000263269',
   'cpi_9606.ENSP00000263321',
   'cpi_9606.ENSP00000263339',
   'cpi_9606.ENSP00000263341',
   'cpi_9606.ENSP00000263377',
   'cpi_9606.ENSP00000263431',
   'cpi_9606.ENSP00000263464',
   'cpi_9606.ENSP00000263686',
   'cpi_9606.ENSP00000263817',
   'cpi_9606.ENSP00000263857',
   'cpi_9606.ENSP00000263923',
   'cpi_9606.ENSP00000263967',
   'cpi_9606.ENSP00000263980',
   'cpi_9606.ENSP00000264071',
   'cpi_9606.ENSP00000264162',
   'cpi_9606.ENSP00000264218',
   'cpi_9606.ENSP00000264318',
   'cpi_9606.ENSP00000264357',
   'cpi_9606.ENSP00000264381',
   'cpi_9606.ENSP00000264382',
   'cpi_9606.ENSP00000264399',
   'cpi_9606.ENSP00000264426',
   'cpi_9606.ENSP00000264498',
   'cpi_9606.ENSP00000264613',
   'cpi_9606.ENSP00000264637',
   'cpi_9606.ENSP00000264657',
   'cpi_9606.ENSP00000264668',
   'cpi_9606.ENSP00000264705',
   'cpi_9606.ENSP00000264708',
   'cpi_9606.ENSP00000264818',
   'cpi_9606.ENSP00000264832',
   'cpi_9606.ENSP00000264867',
   'cpi_9606.ENSP00000264896',
   'cpi_9606.ENSP00000264932',
   'cpi_9606.ENSP00000264995',
   'cpi_9606.ENSP00000265023',
   'cpi_9606.ENSP00000265100',
   'cpi_9606.ENSP00000265164',
   'cpi_9606.ENSP00000265171',
   'cpi_9606.ENSP00000265174',
   'cpi_9606.ENSP00000265294',
   'cpi_9606.ENSP00000265403',
   'cpi_9606.ENSP00000265421',
   'cpi_9606.ENSP00000265563',
   'cpi_9606.ENSP00000265572',
   'cpi_9606.ENSP00000265643',
   'cpi_9606.ENSP00000265717',
   'cpi_9606.ENSP00000265723',
   'cpi_9606.ENSP00000265724',
   'cpi_9606.ENSP00000266376',
   'cpi_9606.ENSP00000266682',
   'cpi_9606.ENSP00000266970',
   'cpi_9606.ENSP00000267017',
   'cpi_9606.ENSP00000267101',
   'cpi_9606.ENSP00000267119',
   'cpi_9606.ENSP00000267163',
   'cpi_9606.ENSP00000267377',
   'cpi_9606.ENSP00000267549',
   'cpi_9606.ENSP00000267843',
   'cpi_9606.ENSP00000268035',
   'cpi_9606.ENSP00000268053',
   'cpi_9606.ENSP00000268124',
   'cpi_9606.ENSP00000268171',
   'cpi_9606.ENSP00000268251',
   'cpi_9606.ENSP00000268661',
   'cpi_9606.ENSP00000268695',
   'cpi_9606.ENSP00000269159',
   'cpi_9606.ENSP00000269305',
   'cpi_9606.ENSP00000269571',
   'cpi_9606.ENSP00000270142',
   'cpi_9606.ENSP00000270202',
   'cpi_9606.ENSP00000270349',
   'cpi_9606.ENSP00000270474',
   'cpi_9606.ENSP00000270570',
   'cpi_9606.ENSP00000270586',
   'cpi_9606.ENSP00000270625',
   'cpi_9606.ENSP00000270631',
   'cpi_9606.ENSP00000270776',
   'cpi_9606.ENSP00000271308',
   'cpi_9606.ENSP00000271331',
   'cpi_9606.ENSP00000271620',
   'cpi_9606.ENSP00000272065',
   'cpi_9606.ENSP00000272167',
   'cpi_9606.ENSP00000272190',
   'cpi_9606.ENSP00000272227',
   'cpi_9606.ENSP00000272298',
   'cpi_9606.ENSP00000272317',
   'cpi_9606.ENSP00000272644',
   'cpi_9606.ENSP00000272847',
   'cpi_9606.ENSP00000272928',
   'cpi_9606.ENSP00000273077',
   'cpi_9606.ENSP00000273398',
   'cpi_9606.ENSP00000273430',
   'cpi_9606.ENSP00000273550',
   'cpi_9606.ENSP00000274026',
   'cpi_9606.ENSP00000274335',
   'cpi_9606.ENSP00000274353',
   'cpi_9606.ENSP00000274545',
   'cpi_9606.ENSP00000274547',
   'cpi_9606.ENSP00000274606',
   'cpi_9606.ENSP00000274793',
   'cpi_9606.ENSP00000275216',
   'cpi_9606.ENSP00000275300',
   'cpi_9606.ENSP00000275493',
   'cpi_9606.ENSP00000275525',
   'cpi_9606.ENSP00000276198',
   'cpi_9606.ENSP00000276414',
   'cpi_9606.ENSP00000276431',
   'cpi_9606.ENSP00000276449',
   'cpi_9606.ENSP00000276571',
   'cpi_9606.ENSP00000276590',
   'cpi_9606.ENSP00000276651',
   'cpi_9606.ENSP00000277010',
   'cpi_9606.ENSP00000277120',
   'cpi_9606.ENSP00000277508',
   'cpi_9606.ENSP00000277541',
   'cpi_9606.ENSP00000277942',
   'cpi_9606.ENSP00000278175',
   'cpi_9606.ENSP00000278616',
   'cpi_9606.ENSP00000279178',
   'cpi_9606.ENSP00000279230',
   'cpi_9606.ENSP00000279387',
   'cpi_9606.ENSP00000279593',
   'cpi_9606.ENSP00000280155',
   'cpi_9606.ENSP00000280357',
   'cpi_9606.ENSP00000280701',
   'cpi_9606.ENSP00000280704',
   'cpi_9606.ENSP00000280706',
   'cpi_9606.ENSP00000281806',
   'cpi_9606.ENSP00000282018',
   'cpi_9606.ENSP00000282077',
   'cpi_9606.ENSP00000282091',
   'cpi_9606.ENSP00000282397',
   'cpi_9606.ENSP00000282561',
   'cpi_9606.ENSP00000282753',
   'cpi_9606.ENSP00000282841',
   'cpi_9606.ENSP00000282957',
   'cpi_9606.ENSP00000283254',
   'cpi_9606.ENSP00000283558',
   'cpi_9606.ENSP00000283635',
   'cpi_9606.ENSP00000283646',
   'cpi_9606.ENSP00000283916',
   'cpi_9606.ENSP00000284981',
   'cpi_9606.ENSP00000285238',
   'cpi_9606.ENSP00000285379',
   'cpi_9606.ENSP00000285381',
   'cpi_9606.ENSP00000285900',
   'cpi_9606.ENSP00000285930',
   'cpi_9606.ENSP00000285979',
   'cpi_9606.ENSP00000286091',
   'cpi_9606.ENSP00000286301',
   'cpi_9606.ENSP00000286355',
   'cpi_9606.ENSP00000286479',
   'cpi_9606.ENSP00000286548',
   'cpi_9606.ENSP00000286621',
   'cpi_9606.ENSP00000286648',
   'cpi_9606.ENSP00000286719',
   'cpi_9606.ENSP00000286758',
   'cpi_9606.ENSP00000287641',
   'cpi_9606.ENSP00000287713',
   'cpi_9606.ENSP00000287766',
   'cpi_9606.ENSP00000287820',
   'cpi_9606.ENSP00000287878',
   'cpi_9606.ENSP00000287907',
   'cpi_9606.ENSP00000287936',
   'cpi_9606.ENSP00000288022',
   'cpi_9606.ENSP00000288135',
   'cpi_9606.ENSP00000288139',
   'cpi_9606.ENSP00000288602',
   'cpi_9606.ENSP00000289753',
   'cpi_9606.ENSP00000290349',
   'cpi_9606.ENSP00000290378',
   'cpi_9606.ENSP00000290541',
   'cpi_9606.ENSP00000290866',
   'cpi_9606.ENSP00000291294',
   'cpi_9606.ENSP00000291295',
   'cpi_9606.ENSP00000291565',
   'cpi_9606.ENSP00000291700',
   'cpi_9606.ENSP00000292095',
   'cpi_9606.ENSP00000292147',
   'cpi_9606.ENSP00000292174',
   'cpi_9606.ENSP00000292301',
   'cpi_9606.ENSP00000292303',
   'cpi_9606.ENSP00000292427',
   'cpi_9606.ENSP00000292513',
   'cpi_9606.ENSP00000292896',
   'cpi_9606.ENSP00000293190',
   'cpi_9606.ENSP00000293230',
   'cpi_9606.ENSP00000293272',
   'cpi_9606.ENSP00000293275',
   'cpi_9606.ENSP00000293288',
   'cpi_9606.ENSP00000293330',
   'cpi_9606.ENSP00000293404',
   'cpi_9606.ENSP00000293636',
   'cpi_9606.ENSP00000293745',
   'cpi_9606.ENSP00000293778',
   'cpi_9606.ENSP00000293813',
   'cpi_9606.ENSP00000293842',
   'cpi_9606.ENSP00000293897',
   'cpi_9606.ENSP00000294016',
   'cpi_9606.ENSP00000294728',
   'cpi_9606.ENSP00000294954',
   'cpi_9606.ENSP00000295137',
   'cpi_9606.ENSP00000295256',
   'cpi_9606.ENSP00000295400',
   'cpi_9606.ENSP00000295448',
   'cpi_9606.ENSP00000295452',
   'cpi_9606.ENSP00000295453',
   'cpi_9606.ENSP00000295454',
   'cpi_9606.ENSP00000295491',
   'cpi_9606.ENSP00000295589',
   'cpi_9606.ENSP00000295598',
   'cpi_9606.ENSP00000295619',
   'cpi_9606.ENSP00000295683',
   'cpi_9606.ENSP00000295731',
   'cpi_9606.ENSP00000295834',
   'cpi_9606.ENSP00000295897',
   'cpi_9606.ENSP00000295930',
   'cpi_9606.ENSP00000296026',
   'cpi_9606.ENSP00000296027',
   'cpi_9606.ENSP00000296028',
   'cpi_9606.ENSP00000296046',
   'cpi_9606.ENSP00000296122',
   'cpi_9606.ENSP00000296140',
   'cpi_9606.ENSP00000296271',
   'cpi_9606.ENSP00000296277',
   'cpi_9606.ENSP00000296350',
   'cpi_9606.ENSP00000296370',
   'cpi_9606.ENSP00000296411',
   'cpi_9606.ENSP00000296412',
   'cpi_9606.ENSP00000296511',
   'cpi_9606.ENSP00000296522',
   'cpi_9606.ENSP00000296545',
   'cpi_9606.ENSP00000296641',
   'cpi_9606.ENSP00000296674',
   'cpi_9606.ENSP00000296677',
   'cpi_9606.ENSP00000296754',
   'cpi_9606.ENSP00000296871',
   'cpi_9606.ENSP00000297258',
   'cpi_9606.ENSP00000297261',
   'cpi_9606.ENSP00000297268',
   'cpi_9606.ENSP00000297313',
   'cpi_9606.ENSP00000297316',
   'cpi_9606.ENSP00000297323',
   'cpi_9606.ENSP00000297350',
   'cpi_9606.ENSP00000297469',
   'cpi_9606.ENSP00000297494',
   'cpi_9606.ENSP00000297770',
   'cpi_9606.ENSP00000297785',
   'cpi_9606.ENSP00000297792',
   'cpi_9606.ENSP00000297991',
   'cpi_9606.ENSP00000298139',
   'cpi_9606.ENSP00000298171',
   'cpi_9606.ENSP00000298283',
   'cpi_9606.ENSP00000298352',
   'cpi_9606.ENSP00000298386',
   'cpi_9606.ENSP00000298440',
   'cpi_9606.ENSP00000298472',
   'cpi_9606.ENSP00000299178',
   'cpi_9606.ENSP00000299267',
   'cpi_9606.ENSP00000299727',
   'cpi_9606.ENSP00000299766',
   'cpi_9606.ENSP00000299847',
   'cpi_9606.ENSP00000299855',
   'cpi_9606.ENSP00000300060',
   'cpi_9606.ENSP00000300061',
   'cpi_9606.ENSP00000300093',
   'cpi_9606.ENSP00000300108',
   'cpi_9606.ENSP00000300151',
   'cpi_9606.ENSP00000300289',
   'cpi_9606.ENSP00000300738',
   'cpi_9606.ENSP00000300900',
   'cpi_9606.ENSP00000301071',
   'cpi_9606.ENSP00000301072',
   'cpi_9606.ENSP00000301141',
   'cpi_9606.ENSP00000301146',
   'cpi_9606.ENSP00000301178',
   'cpi_9606.ENSP00000301420',
   'cpi_9606.ENSP00000301633',
   'cpi_9606.ENSP00000301634',
   'cpi_9606.ENSP00000301645',
   'cpi_9606.ENSP00000301891',
   'cpi_9606.ENSP00000301908',
   'cpi_9606.ENSP00000301974',
   'cpi_9606.ENSP00000302079',
   'cpi_9606.ENSP00000302111',
   'cpi_9606.ENSP00000302150',
   'cpi_9606.ENSP00000302393',
   'cpi_9606.ENSP00000302441',
   'cpi_9606.ENSP00000302486',
   'cpi_9606.ENSP00000302564',
   'cpi_9606.ENSP00000302620',
   'cpi_9606.ENSP00000302665',
   'cpi_9606.ENSP00000302707',
   'cpi_9606.ENSP00000302728',
   'cpi_9606.ENSP00000302811',
   'cpi_9606.ENSP00000302846',
   'cpi_9606.ENSP00000302886',
   'cpi_9606.ENSP00000302961',

In [3]:
paths = [path for path in paths if "ten_mid" in path["dataset_name"]]
len(paths)

3

In [3]:
# # ONLY ONCE - DONE
# k = 10
# random_state = 42
# vouk_path = "C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds"
#
# for idx, path in enumerate(paths, start=1):
#     features = path["original_features"]
#     for label in path['label_set']:
#         run_config = f"Running with dataset:'{path["dataset_name"]}' and label:'{label}'"
#         print(run_config)
#         current_df = pd.read_csv(path["dataset_path"])
#         current_df = current_df[features + [label]].copy()
#         kf = KFold(n_splits=k, shuffle=True, random_state=random_state)
#         for fold, (train_idx, test_idx) in enumerate(kf.split(current_df), start=1):
#             print(f"\nFold {fold}/{k} ({path["dataset_name"]} {idx}/{len(paths)})")
#             train_dataset = current_df.iloc[train_idx]
#             test_dataset = current_df.iloc[test_idx]
#             train_path = f"{vouk_path}/{path['dataset_name']}_{label}_trainFold_{fold}.csv"
#             test_path = f"{vouk_path}/{path['dataset_name']}_{label}_testFold_{fold}.csv"
#             print(train_path, test_path)
#             train_dataset.to_csv(train_path, index=False)
#             test_dataset.to_csv(test_path, index=False)
#             save_to_arff(train_path, [label])
#             save_to_arff(test_path, [label])
# # 16m for 18 datasets

Running with dataset:'CPI+fingerprint_cardiac' and label:'se_C0016382'

Fold 1/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_trainFold_1.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_testFold_1.csv

Fold 2/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_trainFold_2.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_testFold_2.csv

Fold 3/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_trainFold_3.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_testFold_3.csv

Fold 4/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_trainFold_4.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_testFold_4.csv

Fold 5/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_trainFold_5.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_testFold_5.csv

Fold 6/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_trainFold_6.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_testFold_6.csv

Fold 7/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_trainFold_7.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_testFold_7.csv

Fold 8/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_trainFold_8.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_testFold_8.csv

Fold 9/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_trainFold_9.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_testFold_9.csv

Fold 10/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_trainFold_10.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0016382_testFold_10.csv
Running with dataset:'CPI+fingerprint_cardiac' and label:'se_C0018799'

Fold 1/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_trainFold_1.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_testFold_1.csv

Fold 2/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_trainFold_2.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_testFold_2.csv

Fold 3/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_trainFold_3.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_testFold_3.csv

Fold 4/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_trainFold_4.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_testFold_4.csv

Fold 5/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_trainFold_5.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_testFold_5.csv

Fold 6/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_trainFold_6.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_testFold_6.csv

Fold 7/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_trainFold_7.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_testFold_7.csv

Fold 8/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_trainFold_8.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_testFold_8.csv

Fold 9/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_trainFold_9.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_testFold_9.csv

Fold 10/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_trainFold_10.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018799_testFold_10.csv
Running with dataset:'CPI+fingerprint_cardiac' and label:'se_C0003811'

Fold 1/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_trainFold_1.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_testFold_1.csv

Fold 2/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_trainFold_2.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_testFold_2.csv

Fold 3/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_trainFold_3.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_testFold_3.csv

Fold 4/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_trainFold_4.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_testFold_4.csv

Fold 5/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_trainFold_5.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_testFold_5.csv

Fold 6/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_trainFold_6.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_testFold_6.csv

Fold 7/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_trainFold_7.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_testFold_7.csv

Fold 8/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_trainFold_8.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_testFold_8.csv

Fold 9/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_trainFold_9.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_testFold_9.csv

Fold 10/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_trainFold_10.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0003811_testFold_10.csv
Running with dataset:'CPI+fingerprint_cardiac' and label:'se_C0428977'

Fold 1/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_trainFold_1.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_testFold_1.csv

Fold 2/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_trainFold_2.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_testFold_2.csv

Fold 3/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_trainFold_3.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_testFold_3.csv

Fold 4/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_trainFold_4.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_testFold_4.csv

Fold 5/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_trainFold_5.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_testFold_5.csv

Fold 6/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_trainFold_6.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_testFold_6.csv

Fold 7/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_trainFold_7.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_testFold_7.csv

Fold 8/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_trainFold_8.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_testFold_8.csv

Fold 9/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_trainFold_9.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_testFold_9.csv

Fold 10/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_trainFold_10.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0428977_testFold_10.csv
Running with dataset:'CPI+fingerprint_cardiac' and label:'se_C0027051'

Fold 1/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_trainFold_1.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_testFold_1.csv

Fold 2/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_trainFold_2.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_testFold_2.csv

Fold 3/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_trainFold_3.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_testFold_3.csv

Fold 4/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_trainFold_4.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_testFold_4.csv

Fold 5/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_trainFold_5.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_testFold_5.csv

Fold 6/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_trainFold_6.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_testFold_6.csv

Fold 7/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_trainFold_7.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_testFold_7.csv

Fold 8/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_trainFold_8.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_testFold_8.csv

Fold 9/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_trainFold_9.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_testFold_9.csv

Fold 10/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_trainFold_10.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0027051_testFold_10.csv
Running with dataset:'CPI+fingerprint_cardiac' and label:'se_C0018790'

Fold 1/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018790_trainFold_1.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018790_testFold_1.csv

Fold 2/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018790_trainFold_2.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018790_testFold_2.csv

Fold 3/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018790_trainFold_3.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018790_testFold_3.csv

Fold 4/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018790_trainFold_4.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018790_testFold_4.csv

Fold 5/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018790_trainFold_5.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018790_testFold_5.csv

Fold 6/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018790_trainFold_6.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018790_testFold_6.csv

Fold 7/10 (CPI+fingerprint_cardiac 1/18)
C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018790_trainFold_7.csv C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds/CPI+fingerprint_cardiac_se_C0018790_testFold_7.csv

Fold 8/10 (CPI+fingerprint_cardiac 1/18)

In [4]:
def print_candidate_features_stats(candidate_features_for_all_labels: dict):
    for label, groups in candidate_features_for_all_labels.items():
        num_groups = len(groups)

        if num_groups == 0:
            print(f"Label: {label}, Number of groups: 0")
            continue

        lengths = [len(group) for group in groups]
        counts = Counter(lengths)

        avg_len = sum(lengths) / num_groups
        min_len = min(lengths)
        max_len = max(lengths)

        print(f"\nLabel: {label}")
        print(f"Number of groups: {num_groups}")
        print("Group length distribution:")

        for length in sorted(counts):
            print(f"  Length {length}: {counts[length]} groups")

        print(
            f"Avg length: {avg_len:.2f}, "
            f"Min length: {min_len}, "
            f"Max length: {max_len}"
        )
        return avg_len


def apply_max_size_to_full_list(candidate_features_for_all_labels, max_size):
    return {
        label: [group[:max_size] for group in groups]
        for label, groups in candidate_features_for_all_labels.items()
    }


def deduplicate_full_list_groups(candidate_features_capped):
    return {
        label: list({tuple(g): g for g in groups}.values())
        for label, groups in candidate_features_capped.items()
    }


def get_full_list_intersection(candidate_features_unique):
    first_label_groups = next(iter(candidate_features_unique.values()))
    other_sets = [
        set(tuple(group) for group in groups)
        for groups in list(candidate_features_unique.values())[1:]
    ]

    if not other_sets:
        return first_label_groups.copy()

    common = set.intersection(*other_sets)
    return {"intersection": [g for g in first_label_groups if tuple(g) in common]}


def get_full_list_union(candidate_features_unique):
    union = set()
    for groups in candidate_features_unique.values():
        for group in groups:
            union.add(tuple(group))  # convert to tuple for hashing
    return {"union": [list(group) for group in union]}


def get_full_list_vouk(candidate_features_for_all_labels, max_size):
    # print_candidate_features_stats(candidate_features_for_all_labels)
    candidate_features_capped = apply_max_size_to_full_list(candidate_features_for_all_labels, max_size)
    candidate_features_unique = deduplicate_full_list_groups(candidate_features_capped)
    candidate_features_union = get_full_list_union(candidate_features_unique)
    avg_features = print_candidate_features_stats(candidate_features_union)
    return candidate_features_union["union"], avg_features


def get_XofN_rules_vouk(candidate_features_for_all_labels):
    candidate_features_unique = deduplicate_XofN_list_groups(candidate_features_for_all_labels)
    candidate_features_union = get_XofN_rules_union(candidate_features_unique)
    avg_features = sum(len(g.split('and')) for g in candidate_features_union["union"]) / len(
        candidate_features_union["union"])
    return candidate_features_union["union"], avg_features


def get_XofN_combs_vouk(candidate_features_for_all_labels):
    candidate_features_unique = deduplicate_full_list_groups(candidate_features_for_all_labels)
    candidate_features_union = get_full_list_union(candidate_features_unique)
    avg_features = print_candidate_features_stats(candidate_features_union)
    return candidate_features_union["union"], avg_features


def deduplicate_XofN_list_groups(candidate_features):
    """
    Deduplicate feature groups per label (string form).
    """
    result = {}
    for label, groups in candidate_features.items():
        # use dict to preserve order
        result[label] = list({g: g for g in groups}.values())
    return result


def get_XofN_rules_union(candidate_features_unique):
    union = set()
    for groups in candidate_features_unique.values():
        for group_str in groups:
            union.add(group_str)
    return {"union": list(union)}


def split_conditions(rule):
    """
    Splits a rule string into atomic conditions.
    """
    return [c.strip() for c in re.split(r"\s+and\s+", rule)]


def add_rule_count_features_vectorized(df, rules, include_original=True, label_columns=None):
    """
    Adds numeric features counting satisfied conditions for each rule.
    Fully vectorized for performance (avoids row-wise loops).
    Labels are always at the end.
    """
    # Sanitize column names for evaluation
    df_sanitized = df.copy()
    df_sanitized.columns = [c.replace(".", "_") for c in df_sanitized.columns]
    rules_sanitized = [r.replace(".", "_") for r in rules]

    # Container for all rule-count series
    rule_count_dict = {}

    for rule in rules_sanitized:
        conditions = split_conditions(rule)
        # Evaluate all conditions into a boolean DataFrame
        condition_df = pd.DataFrame({cond.replace(" ", ""): df_sanitized.eval(cond).astype(int)
                                     for cond in conditions})
        # Sum across conditions ﷿﷿﷿ number of satisfied conditions
        col_name = rule.replace(" ", "").replace(".", "")
        rule_count_dict[col_name] = condition_df.sum(axis=1)

    # Create rule-count DataFrame
    rule_df = pd.DataFrame(rule_count_dict)

    # Combine with original features if requested
    if include_original:
        new_df = pd.concat([df_sanitized, rule_df], axis=1)
    else:
        new_df = rule_df.copy()

    # Always include label columns
    if label_columns is not None:
        for label_col in label_columns:
            new_df[label_col] = df[label_col]  # original labels
        # Move labels to the end
        cols = [c for c in new_df.columns if c not in label_columns] + label_columns
        new_df = new_df[cols]

    return new_df


def get_XofN_feat_groups(candidate_rules_for_all_labels):
    candidate_features_for_all_labels = candidate_rules_for_all_labels.copy()
    for label in candidate_features_for_all_labels:
        rules = candidate_features_for_all_labels[label]
        feature_groups = []
        for rule in rules:
            conditions = rule.split("and")
            XofN_groups = [(condition.replace(" ", "")
                            .replace(">=1", "")
                            .replace("<=1", "")
                            .replace(">=0", "")
                            .replace("<=0", "")
                            .replace("=0", "")
                            .replace("=1", "")
                            .replace("(", "")
                            .replace(")", "")) for condition in conditions]
            if len(conditions) > 1:
                feature_groups.append(XofN_groups)
        candidate_features_for_all_labels[label] = feature_groups
    candidate_features_unique = {
        label: list({tuple(g): g for g in groups}.values())
        for label, groups in candidate_features_for_all_labels.items()
    }
    union = set()
    for groups in candidate_features_unique.values():
        for group in groups:
            union.add(tuple(group))  # convert to tuple for hashing
    candidate_features_union = {"union": [list(group) for group in union]}
    avg_features = print_candidate_features_stats(candidate_features_union)
    return candidate_features_union["union"], avg_features


def get_used_count(org_features, XofN_groups):
    used_features = {feature for group in XofN_groups for feature in group}
    count_used = len(set(org_features) & used_features)
    unused = set(org_features) - used_features
    count_unused = len(unused)
    lengths = [len(group) for group in XofN_groups]
    max_length = max(lengths)
    min_length = min(lengths)
    return count_used, count_unused, max_length, min_length


def get_length_freq(XofN_groups):
    length_freq = {}
    lengths = [len(group) for group in XofN_groups]
    counts = Counter(lengths)
    for length in sorted(counts):
        length_freq[length] = counts[length]
    return length_freq

In [5]:
# tests
df = pd.DataFrame({
    "f_0": [0, 1, 0, 1, 1, 0, 1, 0, 1, 0],
    "f_1": [1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
    "f_2": [0, 1, 1, 0, 1, 0, 0, 1, 1, 0],
    "f_3": [1, 0, 1, 0, 0, 1, 1, 0, 0, 1],
    "f_4": [0, 1, 0, 1, 1, 0, 1, 1, 0, 0],
    "f_5": [0, 1, 0, 1, 1, 0, 1, 1, 0, 0],
    "f_6": [0, 1, 0, 1, 1, 0, 1, 1, 0, 0],
    "f_7": [0, 1, 0, 1, 1, 0, 1, 1, 0, 0],
    "f_8": [0, 1, 0, 1, 1, 0, 1, 1, 0, 0],
    "label": [1, 0, 1, 0, 1, 1, 0, 1, 0, 1]
})
rules = [
    "(f_0 >= 1) and (f_1 >= 1)",
    "(f_1 >= 1) and (f_2 <= 0)",
    "(f_3 >= 1)",
    "(f_3 <= 0) and (f_4 >= 1) and (f_0 >= 1)",
    "(f_1 >= 1) and (f_2 >= 1)",
    "(f_4 >= 1)"
]
result = add_rule_count_features_vectorized(df, rules, True, ["label"])

XofN_groups, avg = get_XofN_feat_groups({"label": rules})
features = ["f_0", "f_1", "f_2", "f_3", "f_4", "f_5", "f_6", "f_7", "f_8"]
used_count = get_used_count(features, XofN_groups)
print(used_count)

result

Label: union
Number of groups: 3
Group length distribution:
  Length 2: 2 groups
  Length 3: 1 groups
Avg length: 2.33, Min length: 2, Max length: 3
(5, 4, 3, 2)

,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,(f_0>=1)and(f_1>=1),(f_1>=1)and(f_2<=0),(f_3>=1),(f_3<=0)and(f_4>=1)and(f_0>=1),(f_1>=1)and(f_2>=1),(f_4>=1),label
0,0,1,0,1,0,0,0,0,0,1,2,1,0,1,0,1
1,1,0,1,0,1,1,1,1,1,1,0,0,3,1,1,0
2,0,1,1,1,0,0,0,0,0,1,1,1,0,2,0,1
3,1,1,0,0,1,1,1,1,1,2,2,0,3,1,1,0
4,1,0,1,0,1,1,1,1,1,1,0,0,3,1,1,1
5,0,1,0,1,0,0,0,0,0,1,2,1,0,1,0,1
6,1,0,0,1,1,1,1,1,1,1,1,1,2,0,1,0
7,0,1,1,0,1,1,1,1,1,1,1,0,2,2,1,1
8,1,0,1,0,0,0,0,0,0,1,0,0,2,1,0,0
9,0,1,0,1,0,0,0,0,0,1,2,1,0,1,0,1

In [6]:
# tests
candidate_features_unique = {
    "se_C0016382": [
        ["f_347", "f_356"],
        ["f_178", "f_356", "f_380"],
    ],
    "se_C0003811": [["f_347", "f_356"]],
    "se_C0428977": [["f_347", "f_356"], ["f_347", "f_352"]],
    "se_C0027051": [["f_347", "f_356"], ["f_347", "f_355"]],
    "se_C0018790": [["f_347", "f_356"], ["f_347", "f_355"]]
}

intersection = get_full_list_intersection(candidate_features_unique)
print(intersection)

union = get_full_list_union(candidate_features_unique)
print(union)

candidate_features_unique = {
    "se_C0016382": [
        "f_347 and f_356",
        "f_178 and f_356 and f_380",
    ],
    "se_C0003811": ["f_347 and f_356"],
    "se_C0428977": ["f_347 and f_356", "f_347 and f_352"],
    "se_C0027051": ["f_347 and f_356", "f_347 and f_355"],
    "se_C0018790": ["f_347 and f_356", "f_347 and f_355"]
}

union = get_XofN_rules_vouk(candidate_features_unique)
print(union)

candidate_features_unique = {
    "se_C0016382": [
        ["f_347", "f_356"],
        ["f_178", "f_356", "f_380"],
    ],
    "se_C0003811": [["f_347", "f_356"]],
    "se_C0428977": [["f_347", "f_356"], ["f_347", "f_352"]],
    "se_C0027051": [["f_347", "f_356"], ["f_347", "f_355"]],
    "se_C0018790": [["f_347", "f_356"], ["f_347", "f_355"]]
}

union = get_XofN_combs_vouk(candidate_features_unique)
print(union)

{'intersection': [['f_347', 'f_356']]}
{'union': [['f_347', 'f_356'], ['f_178', 'f_356', 'f_380'], ['f_347', 'f_355'], ['f_347', 'f_352']]}
(['f_347 and f_352', 'f_347 and f_355', 'f_347 and f_356', 'f_178 and f_356 and f_380'], 2.25)

Label: union
Number of groups: 4
Group length distribution:
  Length 2: 3 groups
  Length 3: 1 groups
Avg length: 2.25, Min length: 2, Max length: 3
([['f_347', 'f_356'], ['f_178', 'f_356', 'f_380'], ['f_347', 'f_355'], ['f_347', 'f_352']], 2.25)

In [7]:
k = 10
random_state = 42
performances = []
include_original_features_options = [True, False]
training_algorithm = "Variance Reduction"
eval_criteria = ["averageAUROC", "HammingLoss", "SubsetAccuracy", "RankingLoss", "MacroPrecision", "MacroRecall",
                 "MacroFOne"]
max_size = 5
cv_results = []
vouk_path = "C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds"

for idx, path in enumerate(paths, start=1):
    run_config = f"\n--- Running with label:'{path["label_set"]}' max_size:'{max_size}' ---"
    print(run_config)
    run_config_name = "_".join(
        [
            path["dataset_name"],
            "_".join(eval_criteria),
            str(max_size),
        ]
    )

    # Load dataset
    current_df = pd.read_csv(path["dataset_path"])
    features = get_features(current_df, path["label_set"])
    # current_df = current_df[features[:10] + path["label_set"]]
    kf = KFold(n_splits=k, shuffle=True, random_state=random_state)
    for fold, (train_idx, test_idx) in enumerate(kf.split(current_df), start=1):
        title = f"\nFold {fold}/{k} ({path["dataset_name"]} {idx}/{len(paths)})"
        print(title)
        # if "Fold 1/10 (CPI+fingerprint_cardiac 1/12)" not in title or fold != 1:
        #     continue
        train_dataset = current_df.iloc[train_idx]
        test_dataset = current_df.iloc[test_idx]
        candidate_features_for_all_labels = {}
        candidate_rules_for_all_labels = {}
        for label in path["label_set"]:
            print(label)
            candidate_features_path = f"{vouk_path}/{path["dataset_name"]}_{label}_trainFold_{fold}.arff-XofNCombs.json"
            with open(candidate_features_path) as f:
                candidate_features_for_label = json.load(f)
                candidate_features_for_all_labels[label] = candidate_features_for_label
            candidate_rules_path = f"{vouk_path}/{path["dataset_name"]}_{label}_trainFold_{fold}.arff-XofNRules.json"
            with open(candidate_rules_path) as f:
                candidate_rules_for_label = json.load(f)
                candidate_rules_for_all_labels[label] = candidate_rules_for_label
            gen_XofN_time_path = f"{vouk_path}/{path["dataset_name"]}_{label}_trainFold_{fold}.arff-time.txt"
            with open(gen_XofN_time_path, "r", encoding="utf-8") as f:
                string_time = f.read().strip()
                if string_time.count('.') > 1:
                    gen_XofN_time = float('.'.join(string_time.split('.', 2)[:2]))
                else:
                    gen_XofN_time = float(string_time)
        XofN_groupings, avg_features, = get_XofN_feat_groups(candidate_rules_for_all_labels)
        count_used, count_unused, max_length, min_length = get_used_count(features, XofN_groupings)
        XofN_rules, avg_rules = get_XofN_rules_vouk(candidate_rules_for_all_labels)
        if len(XofN_rules) == 0:
            print("no XofN groupings were created")
        else:
            for include_original_features in include_original_features_options:
                current_train_dataset = add_rule_count_features_vectorized(
                    train_dataset,
                    XofN_rules,
                    include_original_features,
                    path["label_set"]
                )

                current_test_dataset = add_rule_count_features_vectorized(
                    test_dataset,
                    XofN_rules,
                    include_original_features,
                    path["label_set"]
                )

                current_train_dataset.to_csv(f"vouk/tmp/train_dataset.csv", index=False)
                current_test_dataset.to_csv(f"vouk/tmp/test_dataset.csv", index=False)

                training_start = time.perf_counter()
                original_res, pruned_res, training_time = run_PCT(clus_path,
                                                                  "vouk/tmp/train_dataset.csv",
                                                                  path["label_set"],
                                                                  eval_criteria,
                                                                  test_dataset_path=f"vouk/tmp/test_dataset.csv")
                pruned_performance = get_fold_results(pruned_res, eval_criteria, True, fold, include_original_features,
                                                      XofN_groupings,
                                                      gen_XofN_time,
                                                      training_time, path["dataset_name"])
                pruned_performance["#used"] = count_used
                pruned_performance["#unused"] = count_unused
                pruned_performance["group_max_len"] = max_length
                pruned_performance["group_min_len"] = min_length

                performances.append(pruned_performance)
                performance = get_fold_results(original_res, eval_criteria, False, fold, include_original_features,
                                               XofN_groupings,
                                               gen_XofN_time,
                                               training_time, path["dataset_name"])
                performance["#used"] = count_used
                performance["#unused"] = count_unused
                performance["group_max_len"] = max_length
                performance["group_min_len"] = min_length
                performances.append(performance)

    if len(performances) == 0:
        print("no XofN groupings were created in any fold")
    else:
        final_perf_df = pd.DataFrame(performances)
        averages = final_perf_df.groupby(["pruning", 'include_original_features', 'dataset'])[
            eval_criteria + ['nodes', 'leaves', 'groups',
                             'avg_group_features', 'gen_XofN_time', 'training_time', "#used",
                             "#unused", "group_max_len", "group_min_len"]].mean().reset_index()
        print(averages)
        cv_results.append(averages)
        performances = []
# paths[0] - features[:10] desktop 0.23m
# laptop ??m
# desktop 4h
cv_results

--- Running with label:'['se_C0009676', 'se_C0041657', 'se_C0002994', 'se_C0042571', 'se_C0004604', 'se_C0041834', 'se_C0085631', 'se_C0040822', 'se_C0042373', 'se_C0021053']' max_size:'5' ---

Fold 1/10 (CPI+fingerprint_ten_mid 1/3)
se_C0009676
se_C0041657
se_C0002994
se_C0042571
se_C0004604
se_C0041834
se_C0085631
se_C0040822
se_C0042373
se_C0021053

Label: union
Number of groups: 164
Group length distribution:
  Length 2: 81 groups
  Length 3: 36 groups
  Length 4: 26 groups
  Length 5: 19 groups
  Length 6: 2 groups
Avg length: 2.93, Min length: 2, Max length: 6
pruning: True, include_original_features: with_org, averageAUROC: 0.5584955, HammingLoss: 0.3741, SubsetAccuracy: 0.11511, RankingLoss: 0.35178, MacroPrecision: 0.46395, MacroRecall: 0.27008, MacroFOne: 0.33582,
pruning: False, include_original_features: with_org, averageAUROC: 0.5934919, HammingLoss: 0.4036, SubsetAccuracy: 0.064748, RankingLoss: 0.33272, MacroPrecision: 0.43794, MacroRecall: 0.46238, MacroFOne: 0.4462,
pruning: True, include_original_features: no_org, averageAUROC: 0.5769147, HammingLoss: 0.35827, SubsetAccuracy: 0.1223, RankingLoss: 0.35737, MacroPrecision: 0.51008, MacroRecall: 0.33737, MacroFOne: 0.40132,
pruning: False, include_original_features: no_org, averageAUROC: 0.5592727, HammingLoss: 0.43669, SubsetAccuracy: 0.05036, RankingLoss: 0.3728, MacroPrecision: 0.41299, MacroRecall: 0.49102, MacroFOne: 0.4465,

Fold 2/10 (CPI+fingerprint_ten_mid 1/3)
se_C0009676
se_C0041657
se_C0002994
se_C0042571
se_C0004604
se_C0041834
se_C0085631
se_C0040822
se_C0042373
se_C0021053

Label: union
Number of groups: 130
Group length distribution:
  Length 2: 57 groups
  Length 3: 34 groups
  Length 4: 27 groups
  Length 5: 9 groups
  Length 6: 2 groups
  Length 7: 1 groups
Avg length: 2.98, Min length: 2, Max length: 7
pruning: True, include_original_features: with_org, averageAUROC: 0.6393868, HammingLoss: 0.32014, SubsetAccuracy: 0.10791, RankingLoss: 0.32647, MacroPrecision: 0.5444, MacroRecall: 0.35412, MacroFOne: 0.42552,
pruning: False, include_original_features: with_org, averageAUROC: 0.6261834, HammingLoss: 0.39209, SubsetAccuracy: 0.05036, RankingLoss: 0.31535, MacroPrecision: 0.44641, MacroRecall: 0.59107, MacroFOne: 0.5063,
pruning: True, include_original_features: no_org, averageAUROC: 0.5997255, HammingLoss: 0.33957, SubsetAccuracy: 0.093525, RankingLoss: 0.32306, MacroPrecision: 0.5069, MacroRecall: 0.30399, MacroFOne: 0.37889,
pruning: False, include_original_features: no_org, averageAUROC: 0.612704, HammingLoss: 0.38633, SubsetAccuracy: 0.05036, RankingLoss: 0.32239, MacroPrecision: 0.44402, MacroRecall: 0.53739, MacroFOne: 0.48384,

Fold 3/10 (CPI+fingerprint_ten_mid 1/3)
se_C0009676
se_C0041657
se_C0002994
se_C0042571
se_C0004604
se_C0041834
se_C0085631
se_C0040822
se_C0042373
se_C0021053

Label: union
Number of groups: 207
Group length distribution:
  Length 2: 103 groups
  Length 3: 55 groups
  Length 4: 38 groups
  Length 5: 9 groups
  Length 6: 2 groups
Avg length: 2.80, Min length: 2, Max length: 6
pruning: True, include_original_features: with_org, averageAUROC: 0.5779782, HammingLoss: 0.3741, SubsetAccuracy: 0.1223, RankingLoss: 0.38608, MacroPrecision: 0.54142, MacroRecall: 0.25245, MacroFOne: 0.34213,
pruning: False, include_original_features: with_org, averageAUROC: 0.5602111, HammingLoss: 0.42662, SubsetAccuracy: 0.035971, RankingLoss: 0.37143, MacroPrecision: 0.44904, MacroRecall: 0.46136, MacroFOne: 0.45271,
pruning: True, include_original_features: no_org, averageAUROC: 0.5706896, HammingLoss: 0.3777, SubsetAccuracy: 0.093525, RankingLoss: 0.36724, MacroPrecision: 0.53657, MacroRecall: 0.23278, MacroFOne: 0.32107,
pruning: False, include_original_features: no_org, averageAUROC: 0.5492858, HammingLoss: 0.43453, SubsetAccuracy: 0.057554, RankingLoss: 0.40053, MacroPrecision: 0.44031, MacroRecall: 0.42171, MacroFOne: 0.4289,

Fold 4/10 (CPI+fingerprint_ten_mid 1/3)
se_C0009676
se_C0041657
se_C0002994
se_C0042571
se_C0004604
se_C0041834
se_C0085631
se_C0040822
se_C0042373
se_C0021053

Label: union
Number of groups: 163
Group length distribution:
  Length 2: 79 groups
  Length 3: 50 groups
  Length 4: 22 groups
  Length 5: 11 groups
  Length 6: 1 groups
Avg length: 2.80, Min length: 2, Max length: 6
pruning: True, include_original_features: with_org, averageAUROC: 0.5583502, HammingLoss: 0.35108, SubsetAccuracy: 0.10791, RankingLoss: 0.39859, MacroPrecision: 0.41055, MacroRecall: 0.18438, MacroFOne: 0.2523,
pruning: False, include_original_features: with_org, averageAUROC: 0.5517323, HammingLoss: 0.41942, SubsetAccuracy: 0.028777, RankingLoss: 0.39093, MacroPrecision: 0.37584, MacroRecall: 0.42134, MacroFOne: 0.39523,
pruning: True, include_original_features: no_org, averageAUROC: 0.5551899, HammingLoss: 0.34245, SubsetAccuracy: 0.1223, RankingLoss: 0.39852, MacroPrecision: 0.44381, MacroRecall: 0.19327, MacroFOne: 0.2671,
pruning: False, include_original_features: no_org, averageAUROC: 0.5752323, HammingLoss: 0.41007, SubsetAccuracy: 0.035971, RankingLoss: 0.35453, MacroPrecision: 0.3994, MacroRecall: 0.507, MacroFOne: 0.4456,

Fold 5/10 (CPI+fingerprint_ten_mid 1/3)
se_C0009676
se_C0041657
se_C0002994
se_C0042571
se_C0004604
se_C0041834
se_C0085631
se_C0040822
se_C0042373
se_C0021053

Label: union
Number of groups: 135
Group length distribution:
  Length 2: 73 groups
  Length 3: 30 groups
  Length 4: 19 groups
  Length 5: 11 groups
  Length 6: 2 groups
Avg length: 2.81, Min length: 2, Max length: 6
pruning: True, include_original_features: with_org, averageAUROC: 0.6080319, HammingLoss: 0.32158, SubsetAccuracy: 0.10072, RankingLoss: 0.36286, MacroPrecision: 0.55979, MacroRecall: 0.28735, MacroFOne: 0.37666,
pruning: False, include_original_features: with_org, averageAUROC: 0.6047024, HammingLoss: 0.39424, SubsetAccuracy: 0.035971, RankingLoss: 0.36362, MacroPrecision: 0.43208, MacroRecall: 0.52915, MacroFOne: 0.47215,
pruning: True, include_original_features: no_org, averageAUROC: 0.5866673, HammingLoss: 0.34388, SubsetAccuracy: 0.093525, RankingLoss: 0.35786, MacroPrecision: 0.48535, MacroRecall: 0.28039, MacroFOne: 0.35288,
pruning: False, include_original_features: no_org, averageAUROC: 0.5796939, HammingLoss: 0.40144, SubsetAccuracy: 0.021583, RankingLoss: 0.34467, MacroPrecision: 0.41476, MacroRecall: 0.4551, MacroFOne: 0.43197,

Fold 6/10 (CPI+fingerprint_ten_mid 1/3)
se_C0009676
se_C0041657
se_C0002994
se_C0042571
se_C0004604
se_C0041834
se_C0085631
se_C0040822
se_C0042373
se_C0021053

Label: union
Number of groups: 193
Group length distribution:
  Length 2: 78 groups
  Length 3: 64 groups
  Length 4: 32 groups
  Length 5: 17 groups
  Length 6: 1 groups
  Length 7: 1 groups
Avg length: 2.97, Min length: 2, Max length: 7
pruning: True, include_original_features: with_org, averageAUROC: 0.6009419, HammingLoss: 0.35755, SubsetAccuracy: 0.15827, RankingLoss: 0.34134, MacroPrecision: 0.54113, MacroRecall: 0.24141, MacroFOne: 0.33166,
pruning: False, include_original_features: with_org, averageAUROC: 0.6163547, HammingLoss: 0.37626, SubsetAccuracy: 0.086331, RankingLoss: 0.32378, MacroPrecision: 0.49636, MacroRecall: 0.50865, MacroFOne: 0.50086,
pruning: True, include_original_features: no_org, averageAUROC: 0.598128, HammingLoss: 0.33165, SubsetAccuracy: 0.16547, RankingLoss: 0.33564, MacroPrecision: 0.6276, MacroRecall: 0.26933, MacroFOne: 0.37568,
pruning: False, include_original_features: no_org, averageAUROC: 0.6182372, HammingLoss: 0.38633, SubsetAccuracy: 0.079137, RankingLoss: 0.31142, MacroPrecision: 0.48352, MacroRecall: 0.53246, MacroFOne: 0.50585,

Fold 7/10 (CPI+fingerprint_ten_mid 1/3)
se_C0009676
se_C0041657
se_C0002994
se_C0042571
se_C0004604
se_C0041834
se_C0085631
se_C0040822
se_C0042373
se_C0021053

Label: union
Number of groups: 142
Group length distribution:
  Length 2: 60 groups
  Length 3: 50 groups
  Length 4: 27 groups
  Length 5: 5 groups
Avg length: 2.84, Min length: 2, Max length: 5
pruning: True, include_original_features: with_org, averageAUROC: 0.5990461, HammingLoss: 0.28551, SubsetAccuracy: 0.21739, RankingLoss: 0.31715, MacroPrecision: 0.57098, MacroRecall: 0.26305, MacroFOne: 0.35925,
pruning: False, include_original_features: with_org, averageAUROC: 0.6124902, HammingLoss: 0.37536, SubsetAccuracy: 0.036232, RankingLoss: 0.2937, MacroPrecision: 0.40721, MacroRecall: 0.49329, MacroFOne: 0.44397,
pruning: True, include_original_features: no_org, averageAUROC: 0.6134434, HammingLoss: 0.28333, SubsetAccuracy: 0.21014, RankingLoss: 0.31574, MacroPrecision: 0.5792, MacroRecall: 0.22414, MacroFOne: 0.32115,
pruning: False, include_original_features: no_org, averageAUROC: 0.5804148, HammingLoss: 0.38333, SubsetAccuracy: 0.057971, RankingLoss: 0.299, MacroPrecision: 0.38955, MacroRecall: 0.45495, MacroFOne: 0.41883,

Fold 8/10 (CPI+fingerprint_ten_mid 1/3)
se_C0009676
se_C0041657
se_C0002994
se_C0042571
se_C0004604
se_C0041834
se_C0085631
se_C0040822
se_C0042373
se_C0021053

Label: union
Number of groups: 206
Group length distribution:
  Length 2: 106 groups
  Length 3: 63 groups
  Length 4: 29 groups
  Length 5: 6 groups
  Length 6: 2 groups
Avg length: 2.71, Min length: 2, Max length: 6
pruning: True, include_original_features: with_org, averageAUROC: 0.5906454, HammingLoss: 0.35072, SubsetAccuracy: 0.086957, RankingLoss: 0.33246, MacroPrecision: 0.52475, MacroRecall: 0.2171, MacroFOne: 0.30323,
pruning: False, include_original_features: with_org, averageAUROC: 0.5609228, HammingLoss: 0.4442, SubsetAccuracy: 0.028986, RankingLoss: 0.37102, MacroPrecision: 0.40195, MacroRecall: 0.48569, MacroFOne: 0.43697,
pruning: True, include_original_features: no_org, averageAUROC: 0.6122413, HammingLoss: 0.35072, SubsetAccuracy: 0.086957, RankingLoss: 0.33686, MacroPrecision: 0.52835, MacroRecall: 0.26053, MacroFOne: 0.34522,
pruning: False, include_original_features: no_org, averageAUROC: 0.5921587, HammingLoss: 0.40652, SubsetAccuracy: 0.050725, RankingLoss: 0.35646, MacroPrecision: 0.44971, MacroRecall: 0.54819, MacroFOne: 0.49202,

Fold 9/10 (CPI+fingerprint_ten_mid 1/3)
se_C0009676
se_C0041657
se_C0002994
se_C0042571
se_C0004604
se_C0041834
se_C0085631
se_C0040822
se_C0042373
se_C0021053

Label: union
Number of groups: 197
Group length distribution:
  Length 2: 90 groups
  Length 3: 61 groups
  Length 4: 31 groups
  Length 5: 14 groups
  Length 6: 1 groups
Avg length: 2.86, Min length: 2, Max length: 6
pruning: True, include_original_features: with_org, averageAUROC: 0.5735786, HammingLoss: 0.36522, SubsetAccuracy: 0.11594, RankingLoss: 0.33018, MacroPrecision: 0.46286, MacroRecall: 0.30057, MacroFOne: 0.36205,
pruning: False, include_original_features: with_org, averageAUROC: 0.5811974, HammingLoss: 0.41232, SubsetAccuracy: 0.036232, RankingLoss: 0.34056, MacroPrecision: 0.42156, MacroRecall: 0.47955, MacroFOne: 0.44704,
pruning: True, include_original_features: no_org, averageAUROC: 0.6152445, HammingLoss: 0.3529, SubsetAccuracy: 0.11594, RankingLoss: 0.33525, MacroPrecision: 0.46683, MacroRecall: 0.29186, MacroFOne: 0.35454,
pruning: False, include_original_features: no_org, averageAUROC: 0.600159, HammingLoss: 0.39348, SubsetAccuracy: 0.050725, RankingLoss: 0.34459, MacroPrecision: 0.44102, MacroRecall: 0.52249, MacroFOne: 0.47717,

Fold 10/10 (CPI+fingerprint_ten_mid 1/3)
se_C0009676
se_C0041657
se_C0002994
se_C0042571
se_C0004604
se_C0041834
se_C0085631
se_C0040822
se_C0042373
se_C0021053

Label: union
Number of groups: 225
Group length distribution:
  Length 2: 93 groups
  Length 3: 73 groups
  Length 4: 40 groups
  Length 5: 14 groups
  Length 6: 5 groups
Avg length: 2.96, Min length: 2, Max length: 6
pruning: True, include_original_features: with_org, averageAUROC: 0.6282675, HammingLoss: 0.3058, SubsetAccuracy: 0.13768, RankingLoss: 0.3495, MacroPrecision: 0.53046, MacroRecall: 0.33055, MacroFOne: 0.40137,
pruning: False, include_original_features: with_org, averageAUROC: 0.6533757, HammingLoss: 0.36232, SubsetAccuracy: 0.065217, RankingLoss: 0.31562, MacroPrecision: 0.45498, MacroRecall: 0.60004, MacroFOne: 0.51517,
pruning: True, include_original_features: no_org, averageAUROC: 0.6454781, HammingLoss: 0.3058, SubsetAccuracy: 0.14493, RankingLoss: 0.31798, MacroPrecision: 0.53045, MacroRecall: 0.39262, MacroFOne: 0.44822,
pruning: False, include_original_features: no_org, averageAUROC: 0.6113591, HammingLoss: 0.39348, SubsetAccuracy: 0.036232, RankingLoss: 0.33187, MacroPrecision: 0.41921, MacroRecall: 0.57784, MacroFOne: 0.48443,
   pruning include_original_features                  dataset  averageAUROC  \
0    False                    no_org  CPI+fingerprint_ten_mid      0.587852
1    False                  with_org  CPI+fingerprint_ten_mid      0.596066
2     True                    no_org  CPI+fingerprint_ten_mid      0.597372
3     True                  with_org  CPI+fingerprint_ten_mid      0.593472

   HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
0     0.403220        0.049062     0.343826        0.429449     0.504815
1     0.400643        0.046883     0.341873        0.432337     0.503252
2     0.338627        0.124861     0.344552        0.521514     0.278628
3     0.340580        0.127019     0.349641        0.515029     0.270106

   MacroFOne   nodes  leaves  groups  avg_group_features  gen_XofN_time  \
0   0.461511  1017.6   509.3   176.2             2.86697      19.444921
1   0.461660  1015.2   508.1   176.2             2.86697      19.444921
2   0.356607    93.2    47.1   176.2             2.86697      19.444921
3   0.348999   106.6    53.8   176.2             2.86697      19.444921

   training_time  #used  #unused  group_max_len  group_min_len
0       0.907588  149.8   1997.2            6.1            2.0
1       3.404018  149.8   1997.2            6.1            2.0
2       0.907588  149.8   1997.2            6.1            2.0
3       3.404018  149.8   1997.2            6.1            2.0

--- Running with label:'['se_C0009676', 'se_C0041657', 'se_C0002994', 'se_C0042571', 'se_C0004604', 'se_C0041834', 'se_C0085631', 'se_C0040822', 'se_C0042373', 'se_C0021053']' max_size:'5' ---

Fold 1/10 (CPI_ten_mid 2/3)
se_C0009676
se_C0041657
se_C0002994
se_C0042571
se_C0004604
se_C0041834
se_C0085631
se_C0040822
se_C0042373
se_C0021053

Label: union
Number of groups: 289
Group length distribution:
  Length 2: 182 groups
  Length 3: 77 groups
  Length 4: 21 groups
  Length 5: 3 groups
  Length 6: 4 groups
  Length 7: 1 groups
  Length 8: 1 groups
Avg length: 2.54, Min length: 2, Max length: 8
pruning: True, include_original_features: with_org, averageAUROC: 0.5730025, HammingLoss: 0.38829, SubsetAccuracy: 0.072072, RankingLoss: 0.39166, MacroPrecision: 0.50469, MacroRecall: 0.32246, MacroFOne: 0.38324,
pruning: False, include_original_features: with_org, averageAUROC: 0.572947, HammingLoss: 0.40901, SubsetAccuracy: 0.054054, RankingLoss: 0.38409, MacroPrecision: 0.47848, MacroRecall: 0.52827, MacroFOne: 0.49944,
pruning: True, include_original_features: no_org, averageAUROC: 0.5641538, HammingLoss: 0.37477, SubsetAccuracy: 0.081081, RankingLoss: 0.4165, MacroPrecision: 0.54732, MacroRecall: 0.27251, MacroFOne: 0.35348,
pruning: False, include_original_features: no_org, averageAUROC: 0.5760125, HammingLoss: 0.38919, SubsetAccuracy: 0.072072, RankingLoss: 0.35467, MacroPrecision: 0.49917, MacroRecall: 0.47312, MacroFOne: 0.48032,

Fold 2/10 (CPI_ten_mid 2/3)
se_C0009676
se_C0041657
se_C0002994
se_C0042571
se_C0004604
se_C0041834
se_C0085631
se_C0040822
se_C0042373
se_C0021053

Label: union
Number of groups: 298
Group length distribution:
  Length 2: 197 groups
  Length 3: 75 groups
  Length 4: 19 groups
  Length 5: 4 groups
  Length 6: 3 groups
Avg length: 2.46, Min length: 2, Max length: 6
pruning: True, include_original_features: with_org, averageAUROC: 0.6078937, HammingLoss: 0.32252, SubsetAccuracy: 0.14414, RankingLoss: 0.3511, MacroPrecision: 0.68203, MacroRecall: 0.2845, MacroFOne: 0.38598,
pruning: False, include_original_features: with_org, averageAUROC: 0.5870654, HammingLoss: 0.4009, SubsetAccuracy: 0.081081, RankingLoss: 0.33124, MacroPrecision: 0.46779, MacroRecall: 0.47149, MacroFOne: 0.46691,
pruning: True, include_original_features: no_org, averageAUROC: 0.5787861, HammingLoss: 0.34414, SubsetAccuracy: 0.11712, RankingLoss: 0.3406, MacroPrecision: 0.59617, MacroRecall: 0.26071, MacroFOne: 0.3445,
pruning: False, include_original_features: no_org, averageAUROC: 0.6057665, HammingLoss: 0.37387, SubsetAccuracy: 0.081081, RankingLoss: 0.32861, MacroPrecision: 0.50225, MacroRecall: 0.42713, MacroFOne: 0.45994,

Fold 3/10 (CPI_ten_mid 2/3)
se_C0009676
se_C0041657
se_C0002994
se_C0042571
se_C0004604
se_C0041834
se_C0085631
se_C0040822
se_C0042373
se_C0021053

Label: union
Number of groups: 319
Group length distribution:
  Length 2: 207 groups
  Length 3: 86 groups
  Length 4: 24 groups
  Length 5: 1 groups
  Length 6: 1 groups
Avg length: 2.44, Min length: 2, Max length: 6
pruning: True, include_original_features: with_org, averageAUROC: 0.5699226, HammingLoss: 0.37207, SubsetAccuracy: 0.081081, RankingLoss: 0.3799, MacroPrecision: 0.50824, MacroRecall: 0.25832, MacroFOne: 0.34008,
pruning: False, include_original_features: with_org, averageAUROC: 0.5641647, HammingLoss: 0.3955, SubsetAccuracy: 0.063063, RankingLoss: 0.35861, MacroPrecision: 0.48456, MacroRecall: 0.45205, MacroFOne: 0.4655,
pruning: True, include_original_features: no_org, averageAUROC: 0.5776409, HammingLoss: 0.36757, SubsetAccuracy: 0.09009, RankingLoss: 0.39428, MacroPrecision: 0.53444, MacroRecall: 0.25981, MacroFOne: 0.34732,
pruning: False, include_original_features: no_org, averageAUROC: 0.5690919, HammingLoss: 0.40631, SubsetAccuracy: 0.054054, RankingLoss: 0.35551, MacroPrecision: 0.46698, MacroRecall: 0.40176, MacroFOne: 0.43122,

Fold 4/10 (CPI_ten_mid 2/3)
se_C0009676
se_C0041657
se_C0002994
se_C0042571
se_C0004604
se_C0041834
se_C0085631
se_C0040822
se_C0042373
se_C0021053

Label: union
Number of groups: 270
Group length distribution:
  Length 2: 188 groups
  Length 3: 64 groups
  Length 4: 15 groups
  Length 5: 2 groups
  Length 6: 1 groups
Avg length: 2.39, Min length: 2, Max length: 6
pruning: True, include_original_features: with_org, averageAUROC: 0.5674353, HammingLoss: 0.37748, SubsetAccuracy: 0.09009, RankingLoss: 0.33651, MacroPrecision: 0.47329, MacroRecall: 0.29332, MacroFOne: 0.35644,
pruning: False, include_original_features: with_org, averageAUROC: 0.5576458, HammingLoss: 0.43063, SubsetAccuracy: 0.045045, RankingLoss: 0.3384, MacroPrecision: 0.42138, MacroRecall: 0.47018, MacroFOne: 0.44333,
pruning: True, include_original_features: no_org, averageAUROC: 0.5369477, HammingLoss: 0.4009, SubsetAccuracy: 0.072072, RankingLoss: 0.38383, MacroPrecision: 0.4011, MacroRecall: 0.21679, MacroFOne: 0.2769,
pruning: False, include_original_features: no_org, averageAUROC: 0.5364747, HammingLoss: 0.44595, SubsetAccuracy: 0.036036, RankingLoss: 0.36181, MacroPrecision: 0.39855, MacroRecall: 0.42393, MacroFOne: 0.40976,

Fold 5/10 (CPI_ten_mid 2/3)
se_C0009676
se_C0041657
se_C0002994
se_C0042571
se_C0004604
se_C0041834
se_C0085631
se_C0040822
se_C0042373
se_C0021053

Label: union
Number of groups: 242
Group length distribution:
  Length 2: 174 groups
  Length 3: 54 groups
  Length 4: 9 groups
  Length 5: 4 groups
  Length 6: 1 groups
Avg length: 2.36, Min length: 2, Max length: 6
pruning: True, include_original_features: with_org, averageAUROC: 0.6174988, HammingLoss: 0.30631, SubsetAccuracy: 0.10811, RankingLoss: 0.3518, MacroPrecision: 0.51369, MacroRecall: 0.30274, MacroFOne: 0.37775,
pruning: False, include_original_features: with_org, averageAUROC: 0.5751535, HammingLoss: 0.39189, SubsetAccuracy: 0.027027, RankingLoss: 0.34865, MacroPrecision: 0.39101, MacroRecall: 0.44279, MacroFOne: 0.41379,

[   pruning include_original_features                  dataset  averageAUROC  \
 0    False                    no_org  CPI+fingerprint_ten_mid      0.587852
 1    False                  with_org  CPI+fingerprint_ten_mid      0.596066
 2     True                    no_org  CPI+fingerprint_ten_mid      0.597372
 3     True                  with_org  CPI+fingerprint_ten_mid      0.593472

    HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
 0     0.403220        0.049062     0.343826        0.429449     0.504815
 1     0.400643        0.046883     0.341873        0.432337     0.503252
 2     0.338627        0.124861     0.344552        0.521514     0.278628
 3     0.340580        0.127019     0.349641        0.515029     0.270106

    MacroFOne   nodes  leaves  groups  avg_group_features  gen_XofN_time  \
 0   0.461511  1017.6   509.3   176.2             2.86697      19.444921
 1   0.461660  1015.2   508.1   176.2             2.86697      19.444921
 2   0.356607    93.2    47.1   176.2             2.86697      19.444921
 3   0.348999   106.6    53.8   176.2             2.86697      19.444921

    training_time  #used  #unused  group_max_len  group_min_len
 0       0.907588  149.8   1997.2            6.1            2.0
 1       3.404018  149.8   1997.2            6.1            2.0
 2       0.907588  149.8   1997.2            6.1            2.0
 3       3.404018  149.8   1997.2            6.1            2.0  ,
    pruning include_original_features      dataset  averageAUROC  HammingLoss  \
 0    False                    no_org  CPI_ten_mid      0.573231     0.406507
 1    False                  with_org  CPI_ten_mid      0.572139     0.405571
 2     True                    no_org  CPI_ten_mid      0.570984     0.354561
 3     True                  with_org  CPI_ten_mid      0.577320     0.358534

    SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  MacroFOne  nodes  \
 0        0.058706     0.351524        0.442990     0.435887   0.436201  627.8
 1        0.047830     0.346000        0.446567     0.467511   0.454298  767.8
 2        0.112071     0.374618        0.523884     0.265687   0.345613   57.6
 3        0.109352     0.365202        0.516205     0.288532   0.361943   75.2

    leaves  groups  avg_group_features  gen_XofN_time  training_time  #used  \
 0   314.4   292.6            2.450513      14.848584       1.018486  125.7
 1   384.4   292.6            2.450513      14.848584       2.953684  125.7
 2    29.3   292.6            2.450513      14.848584       1.018486  125.7
 3    38.1   292.6            2.450513      14.848584       2.953684  125.7

    #unused  group_max_len  group_min_len
 0   1481.3            6.6            2.0
 1   1481.3            6.6            2.0
 2   1481.3            6.6            2.0
 3   1481.3            6.6            2.0  ,
    pruning include_original_features              dataset  averageAUROC  \
 0    False                    no_org  fingerprint_ten_mid      0.577190
 1    False                  with_org  fingerprint_ten_mid      0.573790
 2     True                    no_org  fingerprint_ten_mid      0.575116
 3     True                  with_org  fingerprint_ten_mid      0.570466

    HammingLoss  SubsetAccuracy  RankingLoss  MacroPrecision  MacroRecall  \
 0     0.416483        0.041175     0.344481        0.422841     0.518177
 1     0.418851        0.038914     0.346224        0.417535     0.498259
 2     0.359186        0.115966     0.351840        0.473041     0.234398
 3     0.369263        0.110618     0.353624        0.448874     0.251586

    MacroFOne  nodes  leaves  groups  avg_group_features  gen_XofN_time  \
 0   0.461898  974.6   487.8   152.9            2.923478       4.471284
 1   0.450480  984.4   492.7   152.9            2.923478       4.471284
 2   0.307942   80.4    40.7   152.9            2.923478       4.471284
 3   0.314417  102.8    51.9   152.9            2.923478       4.471284

    training_time  #used  #unused  group_max_len  group_min_len
 0       0.812904  131.9    408.1            7.3            2.0
 1       1.427772  131.9    408.1            7.3            2.0
 2       0.812904  131.9    408.1            7.3            2.0
 3       1.427772  131.9    408.1            7.3            2.0  ]

In [8]:
# All results
save_path = "vouk/"
final_grouped_res = pd.DataFrame()
for df in cv_results:
    final_grouped_res = pd.concat([final_grouped_res, df])
final_grouped_res.sort_values(by='dataset', ascending=False, inplace=True)
final_grouped_res = final_grouped_res.reset_index(drop=True)
final_grouped_res.to_csv(save_path + "all_results.csv")
final_grouped_res

,pruning,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,RankingLoss,MacroPrecision,MacroRecall,MacroFOne,nodes,leaves,groups,avg_group_features,gen_XofN_time,training_time,#used,#unused,group_max_len,group_min_len
0,False,no_org,fingerprint_ten_mid,0.577190,0.416483,0.041175,0.344481,0.422841,0.518177,0.461898,974.6,487.8,152.9,2.923478,4.471284,0.812904,131.9,408.1,7.3,2.0
1,False,with_org,fingerprint_ten_mid,0.573790,0.418851,0.038914,0.346224,0.417535,0.498259,0.450480,984.4,492.7,152.9,2.923478,4.471284,1.427772,131.9,408.1,7.3,2.0
2,True,no_org,fingerprint_ten_mid,0.575116,0.359186,0.115966,0.351840,0.473041,0.234398,0.307942,80.4,40.7,152.9,2.923478,4.471284,0.812904,131.9,408.1,7.3,2.0
3,True,with_org,fingerprint_ten_mid,0.570466,0.369263,0.110618,0.353624,0.448874,0.251586,0.314417,102.8,51.9,152.9,2.923478,4.471284,1.427772,131.9,408.1,7.3,2.0
4,False,no_org,CPI_ten_mid,0.573231,0.406507,0.058706,0.351524,0.442990,0.435887,0.436201,627.8,314.4,292.6,2.450513,14.848584,1.018486,125.7,1481.3,6.6,2.0
5,False,with_org,CPI_ten_mid,0.572139,0.405571,0.047830,0.346000,0.446567,0.467511,0.454298,767.8,384.4,292.6,2.450513,14.848584,2.953684,125.7,1481.3,6.6,2.0
6,True,no_org,CPI_ten_mid,0.570984,0.354561,0.112071,0.374618,0.523884,0.265687,0.345613,57.6,29.3,292.6,2.450513,14.848584,1.018486,125.7,1481.3,6.6,2.0
7,True,with_org,CPI_ten_mid,0.577320,0.358534,0.109352,0.365202,0.516205,0.288532,0.361943,75.2,38.1,292.6,2.450513,14.848584,2.953684,125.7,1481.3,6.6,2.0
8,False,no_org,CPI+fingerprint_ten_mid,0.587852,0.403220,0.049062,0.343826,0.429449,0.504815,0.461511,1017.6,509.3,176.2,2.866970,19.444921,0.907588,149.8,1997.2,6.1,2.0
9,False,with_org,CPI+fingerprint_ten_mid,0.596066,0.400643,0.046883,0.341873,0.432337,0.503252,0.461660,1015.2,508.1,176.2,2.866970,19.444921,3.404018,149.8,1997.2,6.1,2.0
10,True,no_org,CPI+fingerprint_ten_mid,0.597372,0.338627,0.124861,0.344552,0.521514,0.278628,0.356607,93.2,47.1,176.2,2.866970,19.444921,0.907588,149.8,1997.2,6.1,2.0
11,True,with_org,CPI+fingerprint_ten_mid,0.593472,0.340580,0.127019,0.349641,0.515029,0.270106,0.348999,106.6,53.8,176.2,2.866970,19.444921,3.404018,149.8,1997.2,6.1,2.0

In [9]:
# Table ready (with pruning, rounded, compact)
save_path = "vouk/"
rounded_final_grouped_res = pd.read_csv(save_path + "all_results.csv", index_col=0)
res = pd.read_csv(save_path + "all_results.csv", index_col=0)
table_results = get_table_results(res, eval_criteria, get_dataset_paths())
table_results.to_csv(save_path + "table_results.csv")
table_results

,include_original_features,dataset,averageAUROC,HammingLoss,SubsetAccuracy,RankingLoss,MacroPrecision,MacroRecall,MacroFOne,#used,#unused,group_max_len,group_min_len,Nodes; Leaves,#XofN; #Feat/XofN,# Ung. Feats,XofN time (s); PCT tr. time (s)
2,no_org,fingerprint_ten_mid,0.575,0.359,0.116,0.352,0.473,0.234,0.308,131.9,408.1,7.3,2.0,80.4; 40.7,152.9; 2.9,408.1,4.5; 0.8
3,with_org,fingerprint_ten_mid,0.570,0.369,0.111,0.354,0.449,0.252,0.314,131.9,408.1,7.3,2.0,102.8; 51.9,152.9; 2.9,408.1,4.5; 1.4
6,no_org,CPI_ten_mid,0.571,0.355,0.112,0.375,0.524,0.266,0.346,125.7,1481.3,6.6,2.0,57.6; 29.3,292.6; 2.5,1481.3,14.8; 1.0
7,with_org,CPI_ten_mid,0.577,0.359,0.109,0.365,0.516,0.289,0.362,125.7,1481.3,6.6,2.0,75.2; 38.1,292.6; 2.5,1481.3,14.8; 3.0
10,no_org,CPI+fingerprint_ten_mid,0.597,0.339,0.125,0.345,0.522,0.279,0.357,149.8,1997.2,6.1,2.0,93.2; 47.1,176.2; 2.9,1997.2,19.4; 0.9
11,with_org,CPI+fingerprint_ten_mid,0.593,0.341,0.127,0.350,0.515,0.270,0.349,149.8,1997.2,6.1,2.0,106.6; 53.8,176.2; 2.9,1997.2,19.4; 3.4

In [ ]:
k = 10
random_state = 42
vouk_path = "C:/Users/Voror/Projects/Personal/sep/SIDER_dataset/datasets/clean_multi_label_datasets/vouk_folds"
length_frequency = {}
for idx, path in enumerate(paths, start=1):
    run_config = f"\n--- Running with label:'{path["label_set"]}' ---"
    print(run_config)
    run_config_name = path["dataset_name"]

    # Load dataset
    current_df = pd.read_csv(path["dataset_path"])
    features = get_features(current_df, path["label_set"])
    # current_df = current_df[features[:10] + path["label_set"]]
    kf = KFold(n_splits=k, shuffle=True, random_state=random_state)
    for fold, (train_idx, test_idx) in enumerate(kf.split(current_df), start=1):
        title = f"\nFold {fold}/{k} ({path["dataset_name"]} {idx}/{len(paths)})"
        print(title)
        train_dataset = current_df.iloc[train_idx]
        test_dataset = current_df.iloc[test_idx]
        candidate_features_for_all_labels = {}
        candidate_rules_for_all_labels = {}
        for label in path["label_set"]:
            candidate_features_path = f"{vouk_path}/{path["dataset_name"]}_{label}_trainFold_{fold}.arff-XofNCombs.json"
            with open(candidate_features_path) as f:
                candidate_features_for_label = json.load(f)
                candidate_features_for_all_labels[label] = candidate_features_for_label
            candidate_rules_path = f"{vouk_path}/{path["dataset_name"]}_{label}_trainFold_{fold}.arff-XofNRules.json"
            with open(candidate_rules_path) as f:
                candidate_rules_for_label = json.load(f)
                candidate_rules_for_all_labels[label] = candidate_rules_for_label
            gen_XofN_time_path = f"{vouk_path}/{path["dataset_name"]}_{label}_trainFold_{fold}.arff-time.txt"
            with open(gen_XofN_time_path, "r", encoding="utf-8") as f:
                gen_XofN_time = float(f.read().strip())
        XofN_groupings, avg_features, = get_XofN_feat_groups(candidate_rules_for_all_labels)
        count_used, count_unused, max_length, min_length = get_used_count(features, XofN_groupings)
        histogram = get_length_freq(XofN_groupings)
        print(histogram)
        if path["dataset_name"] not in length_frequency:
            length_frequency[path["dataset_name"]] = {}
        length_frequency[path["dataset_name"]][fold] = histogram
        XofN_rules, avg_rules = get_XofN_rules_vouk(candidate_rules_for_all_labels)

length_frequency

In [ ]:
import pandas as pd

rows = []

for dataset, folds in length_frequency.items():
    for fold, lengths in folds.items():
        for length, freq in lengths.items():
            rows.append((dataset, fold, length, freq))

df = pd.DataFrame(rows, columns=["dataset", "fold", "length", "freq"])

avg_df = df.groupby(["dataset", "length"])["freq"].mean().reset_index()
avg_df["avg_freq"] = avg_df["freq"].round(2)
avg_df.drop("freq", axis=1, inplace=True)
avg_df.to_csv("length_frequency_histogram.csv", index=False)