In [1]:
import pandas as pd

In [2]:
meddra_all_se = pd.read_csv("meddra_all_se.tsv", sep="\t")
meddra_all_se = meddra_all_se.drop_duplicates()
print(len(meddra_all_se))
print(meddra_all_se["MedDRA_ADR_id"].unique().size)
meddra_all_se.head()

309849
6061

,CID1,CID0,UMLS_ADR_id,MedDRA_ADR_level,MedDRA_ADR_id,MedDRA_ADR_name
0,CID100000085,CID000010917,C0000729,LLT,C0000729,Abdominal cramps
1,CID100000085,CID000010917,C0000729,PT,C0000737,Abdominal pain
2,CID100000085,CID000010917,C0000737,LLT,C0000737,Abdominal pain
3,CID100000085,CID000010917,C0000737,PT,C0687713,Gastrointestinal pain
4,CID100000085,CID000010917,C0000737,PT,C0000737,Abdominal pain

In [3]:
meddra_all_se_drop_LLT = meddra_all_se[meddra_all_se["MedDRA_ADR_level"] == "PT"]
meddra_all_se_drop_LLT = meddra_all_se_drop_LLT.drop_duplicates()
print(len(meddra_all_se_drop_LLT))
print(meddra_all_se_drop_LLT["MedDRA_ADR_id"].unique().size)
meddra_all_se_drop_LLT.head()

163206
4251

,CID1,CID0,UMLS_ADR_id,MedDRA_ADR_level,MedDRA_ADR_id,MedDRA_ADR_name
1,CID100000085,CID000010917,C0000729,PT,C0000737,Abdominal pain
3,CID100000085,CID000010917,C0000737,PT,C0687713,Gastrointestinal pain
4,CID100000085,CID000010917,C0000737,PT,C0000737,Abdominal pain
6,CID100000085,CID000010917,C0002418,PT,C0002418,Amblyopia
8,CID100000085,CID000010917,C0002871,PT,C0002871,Anaemia

In [4]:
meddra_all_se_filtered = meddra_all_se_drop_LLT.drop(
    columns=[
        "CID0",
        "UMLS_ADR_id",
        "MedDRA_ADR_level",
    ]
)
meddra_all_se_filtered = meddra_all_se_filtered.drop_duplicates()
print("rows:", len(meddra_all_se_filtered))
print("drugs:", meddra_all_se_filtered["CID1"].unique().size)
print("ADRs:", meddra_all_se_filtered["MedDRA_ADR_id"].unique().size)
meddra_all_se_filtered.head()

rows: 145321
drugs: 1430
ADRs: 4251

            CID1 MedDRA_ADR_id        MedDRA_ADR_name
1   CID100000085      C0000737         Abdominal pain
3   CID100000085      C0687713  Gastrointestinal pain
6   CID100000085      C0002418              Amblyopia
8   CID100000085      C0002871                Anaemia
10  CID100000085      C0232462     Decreased appetite

In [5]:
ADR_frequency = meddra_all_se_filtered["MedDRA_ADR_id"].value_counts()
ADR_frequency_df = ADR_frequency.reset_index()
ADR_frequency_df.columns = ["MedDRA_ADR_id", "Count"]
ADR_names = meddra_all_se_filtered[
    ["MedDRA_ADR_id", "MedDRA_ADR_name"]
].drop_duplicates()
ADR_frequency_df = ADR_frequency_df.merge(ADR_names, on="MedDRA_ADR_id", how="left")
ADR_frequency_df["Percentage"] = ADR_frequency_df["Count"] / len(ADR_frequency_df)
ADR_frequency_df.to_csv("SIDER_dataset_ADR_frequency", index=False)
ADR_frequency_df.head(10)

  MedDRA_ADR_id  Count   MedDRA_ADR_name  Percentage
0      C0027497   1207            Nausea    0.283933
1      C0018681   1115          Headache    0.262291
2      C0011603   1096        Dermatitis    0.257822
3      C0015230   1088              Rash    0.255940
4      C0042963   1087          Vomiting    0.255705
5      C0012833   1035         Dizziness    0.243472
6      C0011991    981         Diarrhoea    0.230769
7      C0033774    948          Pruritus    0.223006
8      C0004093    910          Asthenia    0.214067
9      C0020517    904  Hypersensitivity    0.212656

In [6]:
SIDER_dataset = meddra_all_se_filtered.drop(columns=["MedDRA_ADR_name"])
SIDER_dataset = pd.get_dummies(
    SIDER_dataset, columns=["MedDRA_ADR_id"], prefix="se_", dtype=int
)
print("rows:", len(SIDER_dataset))
print("drugs:", SIDER_dataset["CID1"].unique().size)
SIDER_dataset = SIDER_dataset.groupby("CID1", as_index=False).max()
print("rows:", len(SIDER_dataset))
print("drugs:", SIDER_dataset["CID1"].unique().size)
SIDER_dataset.to_csv("./SIDER_dataset.csv", index=None)
SIDER_dataset.head()

rows: 145321
drugs: 1430
rows: 1430
drugs: 1430

,CID1,se__C0000727,se__C0000731,se__C0000735,se__C0000737,se__C0000768,se__C0000772,se__C0000786,se__C0000814,se__C0000817,...,se__C3665347,se__C3665356,se__C3665418,se__C3665444,se__C3665473,se__C3665624,se__C3665770,se__C3665795,se__C3665818,se__C3665888
0,CID100000085,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CID100000119,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CID100000137,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CID100000143,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CID100000146,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0